### ISSUE TITLE
[Documentation Feedback] Problem on /ops#dagster.AssetMaterialization page

### ISSUE THREAD

**Issue by mwlee9** [dagster-io/dagster#5945] opened 2021-12-13 20:19 UTC
Seems like link has been broken - clicking from the dagstermill docs doesn't show the AssetMaterialization documentation

**Comment by yuhan** [comment] 2021-12-15 19:10
surprised the broken link test didn't capture this. will investigate!

**Comment by yuhan** [comment] 2022-02-22 19:22
seems broken since 0.12.14 and blames to https://github.com/dagster-io/internal/pull/360

**Comment by prha** [comment] 2022-02-23 21:11
Should be fixed in the next release: https://github.com/dagster-io/internal/pull/1208

**Comment by prha** [comment] 2022-02-25 17:05
Confirmed that this is now fixed on the latest docs.

**Closed by prha** 2022-02-25 17:05 UTC
