### ISSUE TITLE
Build execution subset only

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1982] opened 2019-12-11 17:56 UTC
Right now we build the entire execution plan even to execute a single step within a process. This leads to a lot of unnecessary compute in large execution plans. For example one builds the execution plan N times in the multiprocessing case.

**Comment by natekupp** [comment] 2020-05-27 21:58
Closing as a dupe of #812

**Closed by natekupp** 2020-05-27 21:58 UTC
Labels: core
