### ISSUE TITLE
Cannot visualize MetaDataTable on Output Metadata

### ISSUE THREAD

**Issue by C0DK** [dagster-io/dagster#10661] opened 2022-11-21 15:20 UTC
### Dagster version

1.1.2

### What's the issue?

```python
@asset()
def broken_asset(context: InputContext) -> int:
    context.add_output_metadata(
        {
            "errors": MetadataValue.table(
                records=[
                    TableRecord(code="invalid-data-type", row=2, col="name"),
                    TableRecord(code="invalid-data-typez", row=1, col="fest"),
                    TableRecord(code="invalid-data-typer", row=3, col="test"),
                ],
                schema=TableSchema(
                    columns=[
                        TableColumn(name="code", type="string"),
                        TableColumn(name="row", type="int"),
                        TableColumn(name="col", type="string"),
                    ]
                ),
            ),
        }
    )

    return 1
```
The above asset taken from your docs https://docs.dagster.io/_apidocs/ops#dagster.MetadataValue.table throws an exception:

```
2022-11-21 16:12:46 +0100 - dagster - ERROR - __ASSET_JOB - 9b9e985f-ab25-4a52-b07b-2bee7b799986 - 1043670 - RUN_FAILURE - Execution of run for "__ASSET_JOB" failed. An exception was thrown during execution.

TypeError: TableRecord.__new__() takes 1 positional argument but 2 were given

Stack Trace:
  File "/home/cdk/.local/share/virtualenvs/dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/execution/api.py", line 1091, in pipeline_execution_iterator
    for event in pipeline_context.executor.execute(pipeline_context, execution_plan):
  File "/home/cdk/.local/share/virtualenvs/dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/executor/multiprocess.py", line 214, in execute
    event_or_none = next(step_iter)
  File "/home/cdk/.local/share/virtualenvs/dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/executor/multiprocess.py", line 330, in execute_step_out_of_process
    for ret in execute_child_process_command(multiproc_ctx, command):
  File "/home/cdk/.local/share/virtualenvs/dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/executor/child_process_executor.py", line 151, in execute_child_process_command
    event = _poll_for_event(process, event_queue)
  File "/home/cdk/.local/share/virtualenvs/dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/executor/child_process_executor.py", line 95, in _poll_for_event
    return event_queue.get(block=True, timeout=TICK)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
```

### What did you expect to happen?

To get a pretty table like shown in your examples. It also visualizes nothing. the error isn't shown in dagit, but rather in the console on my machine when running locally.

### How to reproduce?

Copy the following asset:
```python
@asset()
def broken_asset(context: InputContext) -> int:
    context.add_output_metadata(
        {
            "errors": MetadataValue.table(
                records=[
                    TableRecord(code="invalid-data-type", row=2, col="name"),
                    TableRecord(code="invalid-data-typez", row=1, col="fest"),
                    TableRecord(code="invalid-data-typer", row=3, col="test"),
                ],
                schema=TableSchema(
                    columns=[
                        TableColumn(name="code", type="string"),
                        TableColumn(name="row", type="int"),
                        TableColumn(name="col", type="string"),
                    ]
                ),
            ),
        }
    )

    return 1
```

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2022-11-21 16:39
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues?q=is%3Aissue+is%3Aopen+tablerecord. @smackesey - mind taking a look?

**Closed by sryza** 2022-11-21 16:39 UTC
Labels: bug

**Comment by dwallace0723** [comment] 2022-11-21 19:49
Hitting this as well.
