### ISSUE TITLE
Allow to CREATE OR REPLACE TABLE with duckdb/pandas IOManager on handle output

### ISSUE THREAD

**Issue by malow106** [dagster-io/dagster#18561] opened 2023-12-07 16:25 UTC
### What's the use case?

Hi, 

When my source schema change, I have to manually delete table generated by duckdb OI Manager assets to avoid incompatible schema error.

In the raw code I see that if the table exist, we assume it has the same schema as we perform an `INSERT INTO` . It make sense as we can use it with partionned assets.

```python
def handle_output(
    self, context: OutputContext, table_slice: TableSlice, obj: pd.DataFrame, connection
):
    """Stores the pandas DataFrame in duckdb."""
    connection.execute(
        f"create table if not exists {table_slice.schema}.{table_slice.table} as select * from"
        " obj;"
    )
    if not connection.fetchall():
        # table was not created, therefore already exists. Insert the data
        connection.execute(
            f"insert into {table_slice.schema}.{table_slice.table} select * from obj"
        )
```

  

### Ideas of implementation

Allow an asset level IO Manager config to force a `CREATE OR REPLACE TABLE` statement instead of `INSERT INTO`

### Additional information

Thanks !

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment] 2023-12-07 16:34
duplicate of https://github.com/dagster-io/dagster/issues/13098

**Closed by jamiedemaria** 2023-12-07 16:34 UTC
Labels: type: feature-request
