### ISSUE TITLE
vers 0.11.3: dagit's Tick History chart doesn't show actual execution run time, but scheduled run time

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#4010] opened 2021-04-07 16:29 UTC
I have a pipeline that is normally ran on a schedule for 8:05 am, but didn't actually run due to network drop.  So after daemon was re-launched, the pipeline didn't actually run until 11:11am.  The tick history is showing that the pipeline ran at 8:05am, instead of the actual run time of 11:11am.  Per Slack conversation, it is expected to show actual run time (11:11am).

![image](https://user-images.githubusercontent.com/3989299/113901074-7fd09300-979c-11eb-8c6e-bc5ccf059304.png)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment] 2021-06-01 20:29
Closing as this is an expected behavior not a bug

**Closed by yuhan** 2021-06-01 20:29 UTC
Labels: bug, practitioner
