### ISSUE TITLE
Should support backfilling partitions for which there was not a previous run

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3031] opened 2020-10-06 07:55 UTC
Currently, dagster can only backfill partitions for which there was a previous run

**Comment by sryza** [comment] 2020-10-07 00:07
Is this purely a problem with what backfills can be triggered in Dagit?  Or an issue with how backfills work more deeply?

**Comment by catherinewu** [comment] 2020-10-13 15:52
cc @prha -- could you add the insight that you shared last month during the customer meeting?

**Comment by prha** [comment] 2020-10-16 18:40
Any step subselection with a backfill that takes in inputs will need to copy intermediates from a previous run context.

For orgs that only use `Nothing` inputs, this is not an issue.  I think we're going to enable it via UI and just have errors for steps subselections that do take inputs.

**Comment by sryza** [comment] 2020-10-23 17:41
It seems like Dagit actually does support backfilling partitions without a previous run.

The issue is with step subsets, which is tracked here: https://github.com/dagster-io/dagster/issues/3092.  I'm going to close this.

**Closed by sryza** 2020-10-23 17:41 UTC
Labels: backfills, core, emerald-high-pri, emerald-ux
