### ISSUE TITLE
Dagit interface is partially broken on a PC without internet

### ISSUE THREAD

**Issue by NicolasPA** [dagster-io/dagster#5515] opened 2021-11-03 14:42 UTC
## Summary

It seems like Dagit has been relying on an internet connection to download some part of its GUI since #4867 (https://github.com/dagster-io/dagster/issues/5026) and it continues with the new design introduced in 0.13.

This how it appears on a Chrome browser on a PC without internet:
![image](https://user-images.githubusercontent.com/22459427/140081310-096c2625-ec6d-41c7-a327-5722d2d59105.png)

Having software that works without an internet connection is a regulatory requirement in our case and it's one of the reasons why we chose Dagster.

Functionalities are not broken as far as I can tell, it's just the graphics.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment] 2021-11-04 17:16
Wow thanks for reporting this - this is super interesting because it looks like it's all styled correctly except where we use the CSS `gap` property. (Which is responsible for the padding between the tabs and between the logo + search bar, etc) 

It looks like support was added n Chrome v84 (https://caniuse.com/?search=gap), any chance this machine is locked to an older version of Chrome?

Will try to repro this without an internet connection this afternoon but it seems likely it's a browser CSS support issue.

**Comment by bengotow** [comment] 2021-11-04 17:29
Hey folks! So far it seems Dagit is OK with internet access disabled and doesn't make any web requests except for it's Inconsolata font (which I think we can fix), but I am able to reproduce this UI rendering in Chromium from May 2020 (before the release with `gap` support in July 2020)  


<img width="1199" alt="image" src="https://user-images.githubusercontent.com/1037212/140389394-52f06766-31ec-457a-8063-8b1ed6db2678.png">

**Comment by NicolasPA** [comment] 2021-11-04 19:03
Hey, I think you're correct, this Chrome is indeed stuck in version 79! That's almost two years old, but not that old! (software obsolescence 👹)
I don't know if a fallback to an older solution is possible?

**Comment by bengotow** [comment] 2021-11-16 22:06
Hey @NicolasPA! We talked through this as a team and decided that our bandwidth is too limited to test + maintain backwards compatibility with older versions of Chrome.  I'm going to close this as a wontfix, but in the future we'll wait a bit longer before rolling out shiny new CSS techniques.

I think v79 should work (other than the `gap` CSS issue), but we're also leveraging websockets and a few other things that have changed in the last two years and there might be other things that would be fixed by upgrading Chrome if it's possible!

Cheers, thanks for reporting this—

**Closed by bengotow** 2021-11-16 22:06 UTC
Labels: bug, flow:dev+test, dagit
