### ISSUE TITLE
In the AssetGraph view, descriptions containing underscores are escaped

### ISSUE THREAD

**Issue by OwenKephart** [dagster-io/dagster#10649] opened 2022-11-18 23:34 UTC
### Dagster version

1.1.2

### What's the issue?

```
@asset
def test_c():
    """
    abc_123_abc
    """
    pass
```
![Screen Shot 2022-11-18 at 3 34 25 PM](https://user-images.githubusercontent.com/22457492/202820393-ad32b167-6763-4945-b4b6-166726b81e88.png)

### What did you expect to happen?

The escaping backslashes are unnecessary, and not present in other views

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2022-11-23 21:52
Duplicate of https://github.com/dagster-io/dagster/issues/10331

**Closed by sryza** 2022-11-23 21:52 UTC
Labels: bug, dagit
