### ISSUE TITLE
Unexpected GraphQL error: InstanceWarningQuery

### ISSUE THREAD

**Issue by afparsons** [dagster-io/dagster#4343] opened 2021-07-08 14:51 UTC
## Summary

- opened Dagit to check on a long-running pipeline
- clicked on a red pop-up error in the upper-right corner (something like "Unexpected GraphQL error")
- shown the following stacktrace

## Stacktrace
```
Operation name: InstanceWarningQuery

Message: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT daemon_heartbeats.daemon_type, daemon_heartbeats.daemon_id, daemon_heartbeats.timestamp, daemon_heartbeats.body 
FROM daemon_heartbeats]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

Path: ["instance","daemonHealth","allDaemonStatuses"]

Locations: [{"line":19,"column":3}]

Stack Trace:
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python3.8/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dagster_graphql/schema/instance.py", line 83, in resolve_allDaemonStatuses
    return [
  File "/usr/local/lib/python3.8/site-packages/dagster_graphql/schema/instance.py", line 84, in <listcomp>
    GrapheneDaemonStatus(get_daemon_status(self._instance, daemon_type, ignore_errors=True))
  File "/usr/local/lib/python3.8/site-packages/dagster/daemon/controller.py", line 338, in get_daemon_status
    heartbeats = instance.get_daemon_heartbeats()
  File "/usr/local/lib/python3.8/site-packages/dagster/core/instance/__init__.py", line 1529, in get_daemon_heartbeats
    return self._run_storage.get_daemon_heartbeats()
  File "/usr/local/lib/python3.8/site-packages/dagster/core/storage/runs/sql_run_storage.py", line 698, in get_daemon_heartbeats
    rows = conn.execute(db.select(DaemonHeartbeatsTable.columns))
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
```

## Reproduction
I'm not yet sure how to reproduce this.

## Additional Info about Your Environment
- Ubuntu Server 20.04
- Docker Swarm deployment based on [multi-container documentation](https://docs.dagster.io/deployment/guides/docker#multi-container-docker-deployment)
- Dagster/Dagit 0.11.15

--
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment] 2022-05-03 02:23
Closing because no reproduction - feel free to reopen if you encounter this in 0.14.x.

**Closed by rexledesma** 2022-05-03 02:23 UTC
Labels: bug, platform
