### ISSUE TITLE
--path-prefix in dagit in 0.11.4 graphql endpoint is incorrect

### ISSUE THREAD

**Issue by joshuataylor** [dagster-io/dagster#4028] opened 2021-04-12 00:43 UTC
## Summary
When using --path-prefix, the websocket URL is set to `/graphql` instead of `/mypath/graphql`.

## Reproduction
1. Use dagit --path-prefix /foo
2. Access dagit
3. It does not work as expected

## Dagit UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/225131/114327337-233df100-9b6b-11eb-9a33-45d3630aed39.png)

## Additional Info about Your Environment
Dagit 0.11.4
0.11.3 works.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment] 2021-04-12 13:18
cc @mgasner

**Comment by mgasner** [comment] 2021-04-12 17:43
Having trouble reproducing this... how are you running Dagit?

**Comment by mgasner** [comment] 2021-04-12 17:43
Are you behind a proxy of some kind?

**Comment by joshuataylor** [comment] 2021-04-13 03:19
I am in production, but this happens even without one, on local. I'm running 0.11.4, and when using --path=/bar, on dev tools type graphql and the path is showing as /graphql instead of /bar/graphql.

0.11.4:
![image](https://user-images.githubusercontent.com/225131/114491927-15ab6880-9c4a-11eb-85a6-be3ce3ea80b1.png)

0.11.3 (works):
![image](https://user-images.githubusercontent.com/225131/114491959-26f47500-9c4a-11eb-84f4-cf1b3b614af5.png)

**Comment by lamielle** [comment] 2021-04-15 16:15
I am seeing a similar issue with `0.11.4`.  I did not have Dagster configured with a path prefix before the `0.11.4` upgrade so I cannot confirm if it was working before this version.

Generally I've found some issues with the path prefix functionality which may or may not be the same root cause as this issue.  For example, clicking Launch Execution on the Playground tab of a pipeline opens a new tab, but the path prefix is not maintained and the React app fails to load in the new tab.  The pipeline is launched successfully, though.

Happy to provide more details and/or upgrade when a fix is released and test it out!

**Comment by alangenfeld** [comment] 2021-04-15 17:47
So I was able to reproduce sort-of against the published package for `0.11.4` 
If I manually enter a url like `/instance/runs` instead of the expected `/foo/instance/runs` I see the graphql requests being made without `/foo`

I was not able to reproduce this behavior on a prod build on master - so I am speculating the issue may resolved with the release today. Not sure what the cause could have been though.

**Comment by alangenfeld** [comment] 2021-04-15 18:05
ah found the fixing rev - https://dagster.phacility.com/D7369

this should be resolved in `0.11.5` coming out later today so closing

**Closed by alangenfeld** 2021-04-15 18:05 UTC
Labels: bug

**Comment by hellendag** [comment] 2021-04-15 19:09
> For example, clicking Launch Execution on the Playground tab of a pipeline opens a new tab, but the path prefix is not maintained and the React app fails to load in the new tab. The pipeline is launched successfully, though.

It looks like this may have been broken due to the same issue, as I'm able to repro on 0.11.4 but not on the upcoming `0.11.5` release.

Please feel free to open a new issue if you continue seeing problems with `--path-prefix`. Thanks!

**Comment by lamielle** [comment] 2021-04-15 19:55
Thanks for the quick replies @alangenfeld and @hellendag.  I'll watch for `0.11.5` and report back after I upgrade and test it out!

**Comment by joshuataylor** [comment] 2021-04-20 10:58
Confirmed this is fixed in 0.11.5. Thanks so much for the amazing turnaround :D

**Comment by lamielle** [comment] 2021-04-20 15:14
Same here, upgraded to 0.11.5 yesterday afternoon and have confirmed this is fixed for us.  Thanks for the help in this issue!

I have found one location where a link in the UI doesn't include a path prefix, I'll file a new issue on this since it's not directly related to this one.
