### ISSUE TITLE
Test dagster on Python 3.10

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3393] opened 2020-12-10 21:20 UTC
Trying to get ahead of the curve here. 3.10 is currently alpha 3 and scheduled for final release on 2021-10-04. See https://www.python.org/dev/peps/pep-0619/

**Comment by alangenfeld** [comment] 2021-03-31 21:01
dupe of #2778

**Closed by alangenfeld** 2021-03-31 21:01 UTC
Labels: dependencies, six, systems, test
