### ISSUE TITLE
Disallow typing types in python_type argument PythonObjectDagsterType

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2121] opened 2020-02-07 00:08 UTC
This ends up calling check.type_param where typing types can pass in some cases and not in others. These would end up failing the instanceof check in the body of the function as well.

**Comment by sryza** [comment] 2023-04-20 04:28
Closing this because this is no longer a recommended pattern and the issue is relatively minor. Feel free to reopen if you disagree.

**Closed by sryza** 2023-04-20 04:28 UTC
Labels: core, type-system
