### ISSUE TITLE
Possible memory leak on very long running `dagster-webserver`/Daemon containers

### ISSUE THREAD

**Issue by cody-scott** [dagster-io/dagster#21307] opened 2024-04-19 13:40 UTC
### Dagster version

1.7.1

### What's the issue?

Web UI and Daemon when running for a long period of time (months) without restarting, progressively uses additional memory until restarted.

Example here is we had an older version of dagster running (1.6.0) since February. When we updated to the newest version this week it released a large amount of memory and recovered back up to the original starting point.

Running OSS on Ubuntu in docker on a single machine.

![image](https://github.com/dagster-io/dagster/assets/13374836/53e047bd-9aa9-43ad-a230-ff798c55e0b5)

### Deployment type

None

### Deployment details

Ubuntu 22.04
docker compose for webserver + daemon images

### Additional information

Unclear if this is a docker issue holding on to memory, or if this is a dagster daemon/webserver holding on. Will let it run again to see if it appears.

Additionally, is the best practice to frequently restart the webserver/daemons to avoid this.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment] 2024-04-19 19:58
This could be a duplicate of [https://github.com/dagster-io/dagster/issues/18997](https://github.com/dagster-io/dagster/issues/18997), and [the solution in there](https://github.com/dagster-io/dagster/issues/18997#issuecomment-2043485762) is to downgrade and pin the grpcio python package to 1.57.0. 

We have a fix in the works for this[ in this PR](https://github.com/dagster-io/internal/commit/63e777ac0d7a4dff58d07370ff0f3548bf6d3756).

**Comment by cody-scott** [comment] 2024-04-19 20:45
Perfect! I'll try it out next week.

**Comment by shivonchain** [comment] 2024-04-23 19:32
> We have a fix in the works[ in this PR](https://github.com/dagster-io/internal/commit/63e777ac0d7a4dff58d07370ff0f3548bf6d3756).

@garethbrickman, the link you referenced points to an internal repo, is there a publicly accessible PR to track progress on this? Thanks!

**Comment by garethbrickman** [comment] 2024-04-23 19:49
@shivonchain Ah my apologies I linked that erroneously and have removed it. It was not a fix but an internal test.

**Closed** 2024-08-02 18:28 UTC
Labels: type: bug
