### ISSUE TITLE
asset selection passed to run status sensor is None for scheduled Runs

### ISSUE THREAD

**Issue by simonvanderveldt** [dagster-io/dagster#13543] opened 2023-04-12 10:08 UTC
### Dagster version

1.2.4

### What's the issue?

`context.dagster_run.asset_selection` is correctly set when manually materializing an asset, but it's set to `None` for scheduled Runs.

Example value for a manually triggered run:
```
context.dagster_run.asset_selection=frozenset({AssetKey(['asset1'])})
```
Example value from a scheduled run:
```
asset_selection=None
```

### What did you expect to happen?

The asset selection should be populated irrespective of how the run is started/triggered.

### How to reproduce?

Create a file with the following contents and run it using `dagster dev -f <filename>`

```
from dagster import (
    asset, define_asset_job, AssetSelection, ScheduleDefinition, DefaultScheduleStatus,
    run_status_sensor, DagsterRunStatus, DefaultSensorStatus, repository
)

@asset
def asset1():
    return [1, 2, 3]

job = define_asset_job("asset1_job", AssetSelection.groups("some_asset_group"))

schedule = ScheduleDefinition(job=job, cron_schedule="* * * * *",
                              default_status=DefaultScheduleStatus.RUNNING)

@run_status_sensor(run_status=DagsterRunStatus.STARTED, monitor_all_repositories=True,
                   minimum_interval_seconds=60, default_status=DefaultSensorStatus.RUNNING)
def run_started_sensor(context):
    context.log.info(context.dagster_event)
    context.log.info(context.dagster_run)
    asset_name = next(iter(context.dagster_run.asset_selection)).to_python_identifier()
    context.log.info(asset_name)

@repository
def repo():
    return [asset1, job, schedule, run_started_sensor]
```

- Let it trigger a run automatically and manually materialize "asset1" as well
- Look at the sensor and check the sensor logs (the experimental sensor logging feature needs to be enabled).
- You will see one failure (this is from the scheduled run, it fails because the asset selection isn't populated) and one requested (this is from the manual run)
![image](https://user-images.githubusercontent.com/204286/231425919-b987adef-61f8-4066-9d92-90f53bb2d0e9.png)
Click on the "View Logs" for each and you will see that only the manually triggered run has the asset selection populated
![image](https://user-images.githubusercontent.com/204286/231426409-92d46741-253f-485d-9f24-f2d8676e402e.png)
![image](https://user-images.githubusercontent.com/204286/231426313-99659eff-62d1-4891-b3a4-53c87b9c0dd5.png)

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by tacastillo** [comment] 2023-04-12 22:50
Hi! Thanks for reporting this! Let me @ @sryza onto the issue to start triaging this.

**Comment by sryza** [comment] 2023-04-13 21:49
What's going on here is that the `asset_selection` on a `DagsterRun` refers to the sub-selection that's provided when launching the run. In cases where the run targets all assets, there's no sub-selection provided.

I wrote up a short discussion on how to find the assets targeted by a run in a reliable way: https://github.com/dagster-io/dagster/discussions/13626

**Comment by sryza** [comment] 2023-05-29 17:07
I'm going to close this because this is currently the expected behavior.

**Closed by sryza** 2023-05-29 17:07 UTC
Labels: bug
