### ISSUE TITLE
Tables in dagit get misaligned

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1811] opened 2019-10-04 19:50 UTC
Pretty rough user experience.

![Screenshot 2019-10-04 12 48 41](https://user-images.githubusercontent.com/28738937/66235672-79dc8c00-e6a5-11e9-87a8-83a24c078e02.png)

**Comment by prha** [comment] 2019-10-11 22:18
Duplicate of #1825

**Closed by prha** 2019-10-11 22:18 UTC
Labels: dagit
