### ISSUE TITLE
New additional DAG files in the code location repository are not visible in the Dagster Cloud UI.

### ISSUE THREAD

**Issue by jaiganeshs21** [dagster-io/dagster#20782] opened 2024-03-28 09:57 UTC
### Dagster version

1.6.13

### What's the issue?

In my code repository, initially, I had one file containing a single DAG workflow. Subsequently, after deploying the repository, I added two additional DAG workflow files within the same repository location. However, these new DAGs fail to reflect without redeploying the repository in Dagster Cloud.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment] 2024-03-28 14:22
Not a bug, addressed in your other issue #20781

**Closed by garethbrickman** 2024-03-28 14:22 UTC
