### ISSUE TITLE
Backfill never completes on Hooli

### ISSUE THREAD

**Issue by petehunt** [dagster-io/dagster#13680] opened 2023-04-17 15:00 UTC
### Dagster version

dagster, version 1.2.7

### What's the issue?

I wanted to try out the [hooli-data-eng-pipelines](https://github.com/dagster-io/hooli-data-eng-pipelines) example. I loaded it up in gitpod, installed the deps and launched the project.

I asked the author of the project how to try it out. He told me to hit "materialize all" and just select the latest partition so that's what I did.

The backfill launched but never completed.

### What did you expect to happen?

I expected a backfill to launch and then eventually complete. 

### How to reproduce?

[Here's a Loom](https://www.loom.com/share/27490883b36a469cb76cb8104b301f5b) (watch it sped up since it's long and mostly boring)

I also [zipped up my DAGSTER_HOME dir](https://drive.google.com/file/d/1LOf0M2g6B99KHGIDl2m8aFXiqTAlD2Gx/view?usp=sharing), however, I did play around with materializing some assets manually afterwards which was not included in the Loom.

### Deployment type

Local

### Deployment details

Launched on gitpod via this URL: https://gitpod.io/#https://github.com/dagster-io/hooli-data-eng-pipelines

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-04-17 22:11
I'm trying to reproduce this, but keep getting failures during the backfill.

Errors include:
```
IO Error: Could not set lock on file "/Users/sryza/hooli-data-eng-pipelines/dbt_project/example.duckdb": Resource temporarily unavailable
```
and
```Exception: API time out
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_solid_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/sryza/hooli-data-eng-pipelines/hooli_data_eng/assets/raw_data/__init__.py", line 34, in users
    resp = api.get_users(partition)
  File "/Users/sryza/.pyenv/versions/3.9.11/envs/dagster-3.9.11/lib/python3.9/site-packages/responses/__init__.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "/Users/sryza/hooli-data-eng-pipelines/hooli_data_eng/resources/api.py", line 47, in get_users
    raise Exception("API time out")
```

@slopp - do you have any tips on how to sidestep some of these?

**Comment by sryza** [comment] 2023-04-17 22:35
Actually, I think I understand what's going on here. It's related to https://github.com/dagster-io/dagster/issues/13694.

The graph has hourly assets that are upstream of daily assets. The latest partition of the hourly assets is upstream of a daily partition that doesn't yet exist.  I.e. I'm writing this at 3:30 pm on Monday, April 17th.  There's a partition for 2 pm - 3 pm on this date, because that time window has already passed, but there's not a partition for this entire date in the daily-partitioned assets, because this day has not yet entirely passed.

It seems like different parts of the framework are acknowledging / not acknowledging that fact:
- The `AssetBackfillData` object has these entries for the daily-partitioned assets:
```
                AssetKey(["ANALYTICS", "daily_order_summary"]): TimeWindowPartitionsSubset([]),
                AssetKey(["ANALYTICS", "order_stats"]): TimeWindowPartitionsSubset([]),
```
- However, the UI is claiming that there's 1 partition each targeted by the backfill for each of these assets.

**Comment by sryza** [comment] 2023-04-22 05:39
I'm going to close this because I'm pretty confident that https://github.com/dagster-io/dagster/issues/13694 tracks the underlying issue

**Closed by sryza** 2023-04-22 05:39 UTC
Labels: bug
