### ISSUE TITLE
[Dagit] Dark mode

### ISSUE THREAD

**Issue by nancydyc** [dagster-io/dagster#3541] opened 2021-01-15 06:36 UTC
Feedback from a community member on 1/11/2021.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment] 2021-01-15 15:31
closing as dupe of #1890

**Closed by alangenfeld** 2021-01-15 15:31 UTC
Labels: dagit, feature-request
