### ISSUE TITLE
Dagit syntax highlighting is wonky

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1418] opened 2019-06-02 22:26 UTC
These s3:// gs:// prefixes occur within strings, so they should not be highlighted as if they were YAML keys:

![image](https://user-images.githubusercontent.com/609349/58768119-beff7e80-854a-11e9-8e5f-4b34a713dd64.png)

**Comment by natekupp** [comment] 2019-06-21 20:32
![image](https://user-images.githubusercontent.com/609349/59949780-06ca4500-9429-11e9-8cf1-c8dedb5c38c6.png)
another examples from @Eronarn

**Comment by mgasner** [comment] 2019-07-15 20:49
I think the colon issue is going to be tricky, since these are valid YAML lines:

```
foo: [foo: bar]
zip: {zowie: zop}
```

equiv to:

```
foo:
  - foo: bar
zip:
  zowie:
    zop
```

**Comment by mgasner** [comment] 2019-07-15 20:50
hmm, tho we don't allow these compact nestings

**Comment by mgasner** [comment] 2019-07-15 20:56
actually, i can't reproduce the issue in https://github.com/dagster-io/dagster/issues/1418#issue-451241578

**Comment by mgasner** [comment] 2019-07-15 22:09
Both reproduced, both fixed in https://dagster.phacility.com/D617

**Closed** 2019-07-16 16:27 UTC
Labels: dagit
