### ISSUE TITLE
Enabling multiple instances of an output (ends up being map reduce)

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#100] opened 2018-08-24 03:46 UTC
We need to enable multiple instances of an output. This will allow a "streaming batch" semantic in the pipeline that spawns multiple copies of a downstream DAG. There are a lot of challenges to solve here as you would also want a way to coalesce multiple outstanding subdags. This is essentially map-reduce.

**Comment by mgasner** [comment] 2019-01-12 00:06
Closing as a duplicate of #462

**Closed by mgasner** 2019-01-12 00:06 UTC
