### ISSUE TITLE
wrong step_context in IO manager's InputContext.upstream_output

### ISSUE THREAD

**Issue by aroig** [dagster-io/dagster#7900] opened 2022-05-14 16:35 UTC
## Summary

IO manager's `load_input` gets wrong `context.upstream_output.step_context`. In the example below, when loading input `val_a` for `op_b`, I would expect `context.upstream_output.step_context` to be the context of `op_a`, that generated `val_a` asset. Instead, we get the context of `op_b`.

## Reproduction

The following code reproduces the issue

```
import dagster

class CustomIOManager(dagster.IOManager):

    def handle_output(self, context, obj):
        pass

    def load_input(self, context):
        print(f"[load_input] input_name={context.name}, "
              f"op_config={context.upstream_output.step_context.op_config}")
        return 1

@dagster.io_manager
def custom_io_manager(_):
    return CustomIOManager()

@dagster.op
def op_a():
    return 1

@dagster.op
def op_b(val_a: int) -> int:
    return 2

@dagster.job(
    resource_defs={"io_manager": custom_io_manager},
)
def the_job():
    op_b(op_a())

run_config = {
    "ops": {
        "op_a": {"config": {"config_key": "A"}},
        "op_b": {"config": {"config_key": "B"}},
    }
}

the_job.execute_in_process(run_config=run_config)
```

 I woud expect it to print

```
[load_input] input_name=val_a, op_config={'config_key': 'A'}
```

yet it prints
```
[load_input] input_name=val_a, op_config={'config_key': 'B'}
```

## Further discussion
This example surfaces the problem through run_config, which gets delivered to IO manager through `step_context`. Here are some consequences of this problem:

Both `mem_io_manager` as well as `fs_io_manager` for assets, derive asset paths using `context.upstream_output` in `load_input`. Obtaining partition_key relies on op config, which is wrong in the `upstream_output` context. In the usual case, where `partition_defs` and output names in upstream and downstream assets is the same, then the relevant `step_context` is the same, and the problem is hidden. However, it becomes manifest in those circumstances:

1. chain of assets with different partition_defs and a partition_mapping. Since partition_key will be different upstream and downstream, wrong step_context causes wrong partition_key choices.
2. attempt to extend @multi_asset to support partitions. In this case, the output names may differ from upstream and downstream assets, which again surfaces the problem.

## Possible fixes
I am happy to submit a PR for this. Potential fixes that I could come up:

1. Construct an `InputContext` where `upstream_output.step_context = None`. Then adjust IO managers for assets to get partition_key from the input context, instead of `context.upstream_output`.
2. Somehow, get the correct step_context for the upstream op.

Option 1 seems simpler, yet it can break people's custom io managers. option 2 seems messy to implement, as when the InputContext is constructed [here](https://github.com/dagster-io/dagster/blob/91b6c0f29c583542c5bbb66efb94b64ef2d18ffc/python_modules/dagster/dagster/core/execution/context/system.py#L485), we seem to have no access to the step_context's for the ops that generate the inputs. Not sure if the extra complexity is justified.

Some feedback on how to proceed would be appreciated.

**Comment by jamiedemaria** [comment] 2022-05-16 21:33
thanks for bringing this up! we'll get it in our backlog and discuss an implementation strategy

**Comment by sryza** [comment] 2022-05-16 22:53
I think that, in general, it won't make sense to include the full upstream step context when loading the contents. That's because the upstream step might have resources and loggers that aren't loaded for the downstream step.

Is your main goal here to access the config for the upstream op? If so, it might make sense for us to offer methods that enable that directly.

**Comment by aroig** [comment] 2022-05-17 00:03
No, I don't care about the upstream config actually. I care about asset_partition_key & friends which currently use that config. 

My goal was to fix the situations where the wrong step_context has bad consequences, like with partitioned multi_assets.

I think I agree about not including the full upstream step context. As you suggest,  maybe we could support the asset_partition_key & friends directly, by keeping the partition data in the OutputContext object, instead of accessing it through config.

**Comment by sryza** [comment] 2022-05-18 14:36
@aroig got it - that makes sense. After the PR you submitted, are those bad consequences still there? If so, would it be easy for you to include a code sample that reproduces them?

**Comment by aroig** [comment] 2022-05-18 17:42
@sryza #7958 is an attempt to address this. It still needs some more work though.

**Comment by sryza** [comment] 2022-06-06 14:34
@aroig I'm going to close this because I believe you addressed the problem in other pull requests. Feel free to reopen if I'm misunderstanding.

**Closed by sryza** 2022-06-06 14:34 UTC
Labels: bug
