### ISSUE TITLE
Importing assets throws DagsterInvalidDefinitionError

### ISSUE THREAD

**Issue by marcelteraflow** [dagster-io/dagster#11734] opened 2023-01-16 14:16 UTC
### Dagster version

1.1.10

### What's the issue?

Importing an asset as a module throws `dagster._core.errors.DagsterInvalidDefinitionError` when materializing from CLI.

```shell
python complex_asset_graph.py
```
```console
Traceback (most recent call last):
  File "/Users/marcel/Work/Experiments/dagster/complex_asset_graph.py", line 35, in <module>
    materialize([cereal_protein_fractions])
  File "/Users/marcel/Work/Experiments/dagster/venv/lib/python3.11/site-packages/dagster/_core/definitions/materialize.py", line 70, in materialize
    return build_assets_job(
           ^^^^^^^^^^^^^^^^^
  File "/Users/marcel/Work/Experiments/dagster/venv/lib/python3.11/site-packages/dagster/_annotations.py", line 107, in inner
    return target(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcel/Work/Experiments/dagster/venv/lib/python3.11/site-packages/dagster/_core/definitions/assets_job.py", line 153, in build_assets_job
    resolved_asset_deps = ResolvedAssetDependencies(assets, resolved_source_assets)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcel/Work/Experiments/dagster/venv/lib/python3.11/site-packages/dagster/_core/definitions/resolved_asset_deps.py", line 23, in __init__
    self._deps_by_assets_def_id = resolve_assets_def_deps(assets_defs, source_assets)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcel/Work/Experiments/dagster/venv/lib/python3.11/site-packages/dagster/_core/definitions/resolved_asset_deps.py", line 107, in resolve_assets_def_deps
    raise DagsterInvalidDefinitionError(
dagster._core.errors.DagsterInvalidDefinitionError: Input asset '["cereals"]' for asset '["cereal_protein_fractions"]' is not produced by any of the provided asset ops and is not one of the provided sources
```

### What did you expect to happen?

Same if I had all the assets defined in the same module.

### How to reproduce?

Use the cereals tutorial as an example:

**main.py**
```python
import csv
from typing import Dict, List

import requests

from dagster import asset, materialize


@asset
def cereals() -> List[Dict]:
    response = requests.get("https://docs.dagster.io/assets/cereal.csv")
    lines = response.text.split("\n")
    cereal_rows = [row for row in csv.DictReader(lines)]
    return cereal_rows
```

**complex_asset_graph.py**
```python
from cereal import cereals
from dagster import asset, materialize
from serial_asset_graph import nabisco_cereals



@asset
def cereal_protein_fractions(cereals):
    """For each serial, record its protein content as a fraction of its total mass"""
    result = {}
    for cereal in cereals:
        total_grams = float(cereal["weight"]) * 28.35
        result[cereal["name"]] = float(cereal["protein"]) / total_grams
    return result


@asset
def highest_protein_nabisco_cereal(nabisco_cereals, cereal_protein_fractions):
    """The name of the nabisco cereal that has the highest protein content."""
    sorted_by_protein = sorted(
        nabisco_cereals, key=lambda cereal: cereal_protein_fractions[cereal["name"]]
    )
    return sorted_by_protein[-1]["name"]


@asset
def lowest_protein_nabisco_cereal(nabisco_cereals, cereal_protein_fractions):
    """The name of the nabisco cereal that has the lowest protein content."""
    sorted_by_protein = sorted(
        nabisco_cereals, key=lambda cereal: cereal_protein_fractions[cereal["name"]]
    )
    return sorted_by_protein[0]["name"]


if __name__ == "__main__":
    materialize([cereal_protein_fractions])
```

then run 
```shell
python complex_asset_graph.py
```

**Comment by mkleinbort-ic** [comment] 2023-04-13 09:41
I find that the order in which the assets are defined within the .py files is the cause/fix of this issue

**Comment by sryza** [comment] 2023-04-13 16:26
@marcelteraflow the issue here is that `materialize` needs to know about the `cereals` Python object in order to know how to load the `cereals` asset.

If you want to materialize just `cereal_protein_fractions`, you can do it like this:

```python
    materialize([cereals, cereal_protein_fractions], selection=[cereal_protein_fractions])
```

I'm going to close this, but feel free to reopen or open a new issue if you have other issues.

**Closed by sryza** 2023-04-13 16:26 UTC
Labels: bug
