### ISSUE TITLE
Document persistent storage/instance requirements for Dask, Celery, etc.

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#1952] opened 2019-11-29 18:29 UTC
probably need base utilities of some kind for all of these out-of-process executors

**Comment by catherinewu** [comment] 2021-03-03 03:13
seems somewhat like a duplicate of https://github.com/dagster-io/dagster/issues/1748 which is closed

**Closed by catherinewu** 2021-03-03 03:13 UTC
Labels: core, dask
