### ISSUE TITLE
unexpected error while trying to get the run details

### ISSUE THREAD

**Issue by adarsh-activbytes** [dagster-io/dagster#25489] opened 2024-10-24 07:03 UTC
### What's the issue?

pasting the error below: 

Operation name: {PipelineRunLogsSubscription}

Message: BaseObserver.schedule() takes 3 positional arguments but 4 were given

Path: 

Locations: 

### Dagster version

version 1.8.9

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by garethbrickman** [comment] 2024-10-24 20:51
This looks like a duplicate of https://github.com/dagster-io/dagster/issues/23957 which would have been fixed in 1.8.4. 

Are you sure you're running 1.8.9? Something else to try is you can try is adding a version pin for `Watchdog` in your `setup.py` or `requirements.txt` file with watchdog<5 to see if that resolves the issue.

**Closed** 2024-10-25 13:35 UTC
Labels: type: bug
