### ISSUE TITLE
Auto-materialization policy should consider code and data versions to avoid unnecessary materializations

### ISSUE THREAD

**Issue by jadenhpark** [dagster-io/dagster#15137] opened 2023-07-06 19:10 UTC
### What's the use case?

**Current Behavior:**
The auto-materialization policy seems to be ignoring the versions of code and data when materializing assets. This results in the assets being materialized every time regardless of whether there have been any changes in code or data versions.

**Expected Behavior:**
Ideally, the auto-materialization policy should take into account the versions of code and data. If the versions are identical to a previously materialized state, it should recognize this and avoid re-materializing the subsequent assets. This could save processing time and resources.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by jamiedemaria** [comment] 2023-07-06 19:24
cc @johannkm

**Comment by sryza** [comment] 2023-07-19 18:36
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/14893. We're aiming to address this soon.

**Closed** 2023-07-19 18:36 UTC
Labels: feature-request, auto-materialize
