### ISSUE TITLE
[dagster-airflow] run storage contention

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2082] opened 2020-01-24 19:12 UTC
In the default setup of using the system temp directory for a local DagsterInstance - we observe race conditions around `get_or_create` against the local sqlite runs db. 

https://gist.github.com/amandajcrawford/1a70923fe1903b0d0a825a0dbe357d47

**Comment by mgasner** [comment] 2020-01-28 19:13
https://dagster.phacility.com/D1889, dupe of #2085

**Closed by mgasner** 2020-01-28 19:13 UTC
Labels: bug, duplicate
