### ISSUE TITLE
dbt Cloud integration

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#3402] opened 2020-12-11 00:20 UTC

**Comment by mgasner** [comment] 2020-12-11 01:34
https://app.swaggerhub.com/apis-docs/Sinter/api_v2/2.0.0a1

**Comment by alangenfeld** [comment] 2021-03-31 21:12
dupe of #3382

**Closed by alangenfeld** 2021-03-31 21:12 UTC
Labels: dagster-dbt, feature-request, integrations, project

**Comment by remigabillet** [comment] 2021-12-04 07:51
I just noticed that dbtCloud support was added in [this PR](https://github.com/dagster-io/dagster/pull/5524). 🥳
