### ISSUE TITLE
ECSRunLauncher tasks stuck in "starting" state (occasionally)

### ISSUE THREAD

**Issue by sebtrack** [dagster-io/dagster#6708] opened 2022-02-18 13:54 UTC
## Summary

Most tasks just run fine. But from time to time a task gets created by the ECSRunLauncher and is stuck in "starting" state for hours, if the job is not terminated manually it will slowly but surely take up the whole queue size. I suspect there goes something wrong in the communication with AWS Fargate and the ECSRunLauncher isn't made to handle it.

Can you come up with a way to debug this?

## Reproduction

Unfortunately it's not deterministic.

## Dagit UI/UX Issue Screenshots

Two environments:

![Screenshot 2022-02-18 at 13 46 14](https://user-images.githubusercontent.com/83225744/154695969-a28593d7-c3c2-47db-8b7e-bb416e1adfe8.png)

![Screenshot 2022-02-18 at 13 44 38](https://user-images.githubusercontent.com/83225744/154694626-5c4941f5-f117-4903-838e-26c94afd27c3.png)

## Additional Info about Your Environment

We currently run 0.13.10.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment] 2022-02-20 19:58
Hi @sebtrack, are there any logs from the ECS task in the event log when this happens? Usually when this happens there's some kind of clue there.

We're also working on the ability to monitoring these 'failed during startup' runs within Dagster and automatically remove them from the queue, to help with the issue you mentioned where they 'fill up' the queue.

**Comment by morfien101** [comment] 2022-02-28 10:29
We have this issue too. The error that we see is: If the task was killed in a non graceful way, then the task will stay running in the UI. However the container itself has been terminated.
Our issue is generally memory related and we know this because we can see in the logs with the process manager we use in the container an exit code of 137 for the Dagster process.

I guess the issue is about knowing both if the process is running in the container and if there has been nothing for some time checking to see if the task is running.

I can confirm this is still an issue in 0.14.1.

**Comment by jamiedemaria** [comment] 2022-05-13 19:28
We've added a health check to the ECS run launcher that should provide some visibility into your ECS tasks. It will be included in next week's release. We're planning on monitoring the health check over the next few weeks/months and adding improvements. Closing this task for now, but open a new issue if you run into more issues or have feature requests!

**Closed by jamiedemaria** 2022-05-13 19:28 UTC
Labels: bug, platform

**Comment by PascalStehling** [comment] 2022-06-09 15:08
The same Problem is also occuring in the DockerRunLauncher in Version 0.14.17. Should I make an extra Issue for that, as its nearly the same Problem.

**Comment by jamiedemaria** [comment] 2022-06-09 16:55
> Should I make an extra Issue for that, as its nearly the same Problem.

yes, since it's DockerRunLauncher related making a new issue will help us track it more effectively. Any information you can provide about the behavior you're seeing, screenshots from dagit, daemon logs, whatever you're able to share would be very helpful for recreating and fixing the issue
