### ISSUE TITLE
metadata of asset in the UI

### ISSUE THREAD

**Issue by jburnich** [dagster-io/dagster#7628] opened 2022-04-28 15:53 UTC
## Summary
Hi Dasgter Team,
When booleans are used in the metadata, they are not displayed on the interface.

## Reproduction

```
@asset(metadata={"boolean" : True})
       def my_asset() :

```

## Dagit UI/UX Issue Screenshots
<img width="214" alt="Capture" src="https://user-images.githubusercontent.com/99728876/165792736-fe01a536-d539-44c1-822a-17620160d1e8.PNG">

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment] 2022-04-28 17:44
This is related to https://github.com/dagster-io/dagster/issues/6473

**Comment by sryza** [comment] 2022-05-02 20:28
I'm going to close this as a duplicate of https://github.com/dagster-io/dagster/issues/6473. I think we should fix this soon.

**Closed by sryza** 2022-05-02 20:28 UTC
Labels: bug
