### ISSUE TITLE
StringSource and brethren should allow for a default env variable to be set at schema definition time

### ISSUE THREAD

**Issue by mgasner** [dagster-io/dagster#4034] opened 2021-04-12 19:46 UTC

**Comment by alangenfeld** [comment] 2021-04-12 20:43
dupe of https://github.com/dagster-io/dagster/issues/3947 ?

**Comment by yuhan** [comment] 2021-05-26 19:57
seems dup^ closing. reopen if that's not the case

**Closed by yuhan** 2021-05-26 19:57 UTC
Labels: feature-request, practitioner
