### ISSUE TITLE
Clean-up for Kubernetes Job objects

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2157] opened 2020-02-13 20:36 UTC
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#ttl-mechanism-

we just need to add `ttlSecondsAfterFinished` or make it easy to choose to add it via `helm` values

**Comment by alangenfeld** [comment] 2020-02-13 21:28
update: we set this https://dagster.phacility.com/source/dagster/browse/master/python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py$197
but it doesnt seem to work

**Comment by mgasner** [comment] 2020-02-25 01:37
I believe in order for this to work, kube-apiserver and kube-controller-manager must be started with `--feature-gates="...,TTLAfterFinished=true"`

**Comment by mgasner** [comment] 2020-02-25 01:39
In kind: https://kind.sigs.k8s.io/docs/user/quick-start/#enable-feature-gates-in-your-cluster

**Comment by mgasner** [comment] 2020-02-25 01:39
`minikube start --feature-gates`

**Comment by mgasner** [comment] 2020-02-25 01:40
cc @natekupp

**Comment by natekupp** [comment] 2020-05-02 19:38
Some additional notes here - K8s Job TTL doesn't work properly in most K8s installations, as it is marked alpha and disabled by default in most K8s cases.

So, we need to come up with some way to manage job lifecycle. Some other ideas:

- Could specify a K8s cron job that periodically cleans up old jobs, but this is another infra component to deploy and maintain.
- Could delete job objects at step or pipeline termination time, but this is problematic -- it's useful to keep jobs around for diagnosis / debugging. Once pods are deleted, we cannot access any logs or diagnostics.

**Comment by AndersonReyes** [comment] 2020-06-05 13:09
What if you only delete on success? Hmmm ehhh still that would leave the user having to manually. What if it's a separate k8s job that does some barebones pod culling that can be configured through the helm chart?

**Comment by natekupp** [comment] 2020-06-08 21:24
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

**Comment by catherinewu** [comment] 2021-06-08 17:19
marking as duplicate of https://github.com/dagster-io/dagster/issues/3948

**Closed by catherinewu** 2021-06-08 17:19 UTC
Labels: documentation, emerald, k8s, ops+monitoring, platform, test
