### ISSUE TITLE
Exception in run launcher doesn't include stack trace

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#2523] opened 2020-05-31 19:55 UTC
<img width="596" alt="image" src="https://user-images.githubusercontent.com/609349/83361450-e8114580-a33d-11ea-85ea-d693f5845085.png">

Looking at the console I see the stack trace—would be nice to have this included in the modal pop-up:

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/609349/83361461-f7908e80-a33d-11ea-8042-268a91267af2.png">

**Comment by schrockn** [comment] 2020-06-19 16:56
dupe of https://github.com/dagster-io/dagster/issues/2525

**Closed by schrockn** 2020-06-19 16:56 UTC
Labels: dagit
