### ISSUE TITLE
Eliminate hard-coded tag check in instance/__init__.py

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#2497] opened 2020-05-21 03:01 UTC
```
        if tags and IS_AIRFLOW_INGEST_PIPELINE_STR in tags:
            if AIRFLOW_EXECUTION_DATE_STR not in tags:
                tags[AIRFLOW_EXECUTION_DATE_STR] = get_current_datetime_in_utc().isoformat()
```

we have this hardcoded snippet right now, which is pretty lame. There should be no reference this to any integration in our core.

A more proper fix is likely to mode airflow execution date as a resource to flow it through the computation.

**Comment by mgasner** [comment] 2020-05-21 17:13
this is a duplicate of #2403

**Comment by schrockn** [comment] 2020-05-21 18:42
ah. i was confused because there was no comment pointing to issue.

added them here:
https://dagster.phacility.com/D3020

Sent via Superhuman ( https://sprh.mn/?vip=schrockn@elementl.com )

**Closed** 2020-05-21 18:41 UTC
Labels: integrations, refactor
