### ISSUE TITLE
[Dagster docker] Missing dagster-mysql

### ISSUE THREAD

**Issue by phuongdinh1411** [dagster-io/dagster#8024] opened 2022-05-24 03:42 UTC
## Summary

Dagster-mysql is missed in dagster-celery-k8s docker image.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment] 2022-05-24 03:47
Duplicate of https://github.com/dagster-io/dagster/issues/4610. Currently in the helm chart, we assume postgres as your storage backend.

**Closed by rexledesma** 2022-05-24 03:47 UTC
Labels: bug
