### ISSUE TITLE
Canonicalize spacing in dagster instance rendering

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3346] opened 2020-12-06 19:54 UTC
## Summary

Right now if you view the Dagster instance config in dagit the spacing can get messed up.

A possible solution would be to canonicalize spacing.

## Reproduction

![Screen Shot 2020-12-06 at 11 52 52 AM](https://user-images.githubusercontent.com/28738937/101290880-b4feb180-37b9-11eb-8ebf-411846afba87.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by schrockn** [comment] 2020-12-06 19:55
Unclear if I triaged correctly. Assigning to @natekupp who is tracking/managing project ontology

**Comment by rexledesma** [comment] 2020-12-07 18:25
Duplicate of https://github.com/dagster-io/dagster/issues/3166

**Comment by natekupp** [comment] 2020-12-14 18:40
Closing this as dupe

**Closed by natekupp** 2020-12-14 18:40 UTC
Labels: bug, dagit
