### ISSUE TITLE
Reload the code location files without redeploying the code location repository 

### ISSUE THREAD

**Issue by jaiganeshs21** [dagster-io/dagster#20781] opened 2024-03-28 09:40 UTC
### What's the use case?

Hi,

In my code location repository, initially I have one file, basically one DAG workflow. After deploying the repository, I added two more DAG workflows  file in the same code location repository. Will the changes show automatically without redeploying the code location in dagster cloud?

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment] 2024-03-28 14:20
At this time when you make changes to your code location repository, these changes will not automatically be reflected in  Dagit, the Dagster UI. You will need to redeploy your code location for the changes to take effect and for the new workflows to be visible.

**Comment by rexledesma** [comment] 2024-03-28 17:34
Duplicate of https://github.com/dagster-io/dagster/issues/3337.

**Closed by rexledesma** 2024-03-28 17:34 UTC
Labels: type: feature-request, area: code-locations
