### ISSUE TITLE
Metadata provided on output object not available to context object in IOManager

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#12873] opened 2023-03-10 01:07 UTC
The metadata field in `OutputContext` only retrieves metadata from the output definition. Need to update it to also retrieve metadata from the relevant incoming output event.

**Comment by sryza** [comment] 2023-03-10 01:21
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/9076

**Closed by sryza** 2023-03-10 01:21 UTC
