### ISSUE TITLE
Partitioned assets not marked as stale when upstream data changes

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#14385] opened 2023-05-22 13:19 UTC
### Dagster version

1.3.5

### What's the issue?

When an upstream asset is materialized (new data) I expect the assets generated by the partitioned asset to be marked as stale. Currently they are not marked as stale, nor are their decedents. 

This is causing stale data to get mixed in with our fresh data when relying on AutoMaterializations and/or reconciliation sensors. 

Here is a minimal example:

```python

@asset
def all_of_the_latest_ocean_data()->pd.DataFrame:
    data = pd.read_csv('https://get/the/current/ocean/data.csv') # Made up URL
    return data.set_index('ocean_name')

oceans_partitions_def = StaticPartitionsDefinition(
    ["arctic", "atlantic", "indian", "pacific", "southern"]
)

@asset(partitions_def=oceans_partitions_defs)
def current_ocean_mean_temperature(context, all_of_the_latest_ocean_data):

    ocean_name = context.asset_partition_key_for_output()
    ocean_data = all_of_the_latest_ocean_data.loc[ocean_name]
    
    return ocean_data['temperature'].mean()
    
```

### What did you expect to happen?

I'd expect all the partitions in this statically partitioned asset (and it's children) to be marked as stale.

### How to reproduce?

```python

@asset
def all_of_the_latest_ocean_data()->pd.DataFrame:
    data = pd.DataFrame({
   'ocean_name': ["arctic", "atlantic", "indian", "pacific", "southern"],
   'temp': [1,2,3,4,5]
      })
    return data 

oceans_partitions_def = StaticPartitionsDefinition(
    ["arctic", "atlantic", "indian", "pacific", "southern"]
)

@asset(partitions_def=oceans_partitions_defs)
def current_ocean_mean_temperature(context, all_of_the_latest_ocean_data):

    ocean_name = context.asset_partition_key_for_output()
    ocean_data = all_of_the_latest_ocean_data.loc[ocean_name]
    
    return ocean_data['temperature'].mean()
    
```
 On manually re-materializing `all_of_the_latest_ocean_data` I'd expect `current_ocean_mean_temperature` to be marked as stale.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment] 2023-05-22 20:47
Hi @mkleinbort-ic ! Thanks for creating the issue -- I'm closing this as a duplicate of https://github.com/dagster-io/dagster/issues/9374, but this is something we are actively working on implementing. The main constraining factor is  performance, as if you have a large number of partitions, each of those needs to be independently validated, which can add up pretty quickly.

For the initial version of this feature, the status will be rendered on the asset details page only.

**Closed** 2023-05-22 20:47 UTC
Labels: feature-request, partitions
