### ISSUE TITLE
ExecuteInProcessResult.output_value method always fails

### ISSUE THREAD

**Issue by FelixDent** [dagster-io/dagster#5478] opened 2021-10-31 00:40 UTC
**Version 0.13.2**

## Summary
Method docstring: _Retrieves output of top-level graph, if an output is returned._

However, it always seems to fail with:

`CheckError: Failure condition: Could not find output mapping result`

## Reproduction

```python
from dagster import graph, op, job

@op
def return_one(context) -> int:
    return 1

@op
def add_one(context, number: int):
    return number + 1

@op
def adder(context, a: int, b: int) -> int:
    return a + b

@graph
def inputs_and_outputs():
    value = return_one()
    a = add_one(value)
    b = add_one(value)
    return adder(a, b)

@job
def demo_job():
    inputs_and_outputs()

if __name__ == "__main__":
     res = demo_job.execute_in_process()
     res.output_value()
```
output:
```
Traceback (most recent call last):
  File "sandbox.py", line 31, in <module>
    res.output_value()
  File "/home/dentf/repos/agent-alpha/.venv/lib/python3.8/site-packages/dagster/core/execution/execute_in_process_result.py", line 79, in output_value
    output_mapping = graph_def.get_output_mapping(output_name)
  File "/home/dentf/repos/agent-alpha/.venv/lib/python3.8/site-packages/dagster/core/definitions/graph.py", line 298, in get_output_mapping
    check.failed(f"Could not find output mapping {output_name}")
  File "/home/dentf/repos/agent-alpha/.venv/lib/python3.8/site-packages/dagster/check/__init__.py", line 119, in failed
    raise CheckError("Failure condition: {desc}".format(desc=desc))
dagster.check.CheckError: Failure condition: Could not find output mapping result
```
Also possibly relevant:
```python
print(res._node_def._output_mappings)
# []
```

**Comment by dpeng817** [comment] 2021-11-02 18:35
Hi Felix! In the code example you posted, `output_value` erroring is the intended behavior, because `demo_job` doesn't have an output (ie isn't directly returning anything). However, the error message and docstring definitely do not communicate this sufficiently.

**Comment by FelixDent** [comment] 2021-11-02 21:47
@dpeng817 ah ok, thank you for the clarification 🙂 I thought it was referring to the top-level graph _within_ the job.

**Comment by dpeng817** [comment] 2021-11-03 16:02
Landed some improvements to the documentation + error messaging, so going to close this. Thanks again for surfacing!

**Closed by dpeng817** 2021-11-03 16:02 UTC
Labels: bug, graph-job-op
