### ISSUE TITLE
Incompatibility between currently required protobuf and grpc modules

### ISSUE THREAD

**Issue by imrehg** [dagster-io/dagster#8079] opened 2022-05-26 08:13 UTC
## Summary

Recently an issue popped up, when freshly installed version of dagster thrown an error when used in our testing pipeline, along the lines of the log below.

It seems to be an issue with how some of the packages in dagster pinned or not, mainly [`protobuf` (just minimum version supplied)](https://github.com/dagster-io/dagster/blob/1e411ad2f4cdb07fc2288c6076bd5d3bc51f8bd5/python_modules/dagster/setup.py#L75) and [`grpcio-health-checking` (with max version also set)](https://github.com/dagster-io/dagster/blob/1e411ad2f4cdb07fc2288c6076bd5d3bc51f8bd5/python_modules/dagster/setup.py#L71):

```
test_job.py:1: in <module>
    from dagster import ExecuteInProcessResult
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/__init__.py:227: in <module>
    from dagster.core.launcher import DefaultRunLauncher
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/core/launcher/__init__.py:1: in <module>
    from .base import (
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/core/launcher/base.py:8: in <module>
    from dagster.core.workspace.workspace import IWorkspace
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/core/workspace/__init__.py:1: in <module>
    from .context import IWorkspaceProcessContext, WorkspaceProcessContext
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/core/workspace/context.py:16: in <module>
    from dagster.core.host_representation import (
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/core/host_representation/__init__.py:50: in <module>
    from .repository_location import (
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/core/host_representation/repository_location.py:9: in <module>
    from dagster.api.list_repositories import sync_list_repositories_grpc
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/api/list_repositories.py:6: in <module>
    from dagster.grpc.types import ListRepositoriesResponse
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/grpc/__init__.py:11: in <module>
    from .client import DagsterGrpcClient, ephemeral_grpc_api_client
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/dagster/grpc/client.py:9: in <module>
    from grpc_health.v1 import health_pb2
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/grpc_health/v1/health_pb2.py:34: in <module>
    _descriptor.EnumValueDescriptor(
/opt/anaconda/envs/Python3/lib/python3.8/site-packages/google/protobuf/descriptor.py:755: in __new__
    _message.Message._CheckCalledFromGeneratedFile()
E   TypeError: Descriptors cannot not be created directly.
E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
E   If you cannot immediately regenerate your protos, some other possible workarounds are:
E    1. Downgrade the protobuf package to 3.20.x or lower.
E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
E   
E   More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

## Reproduction

```shell
pip install dagster==0.14.16
python -c "from dagster import ExecuteInProcessResult"
```

## Additional Info about Your Environment

Linux environment, checked both Python 3.8.12 and 3.10.4.
Versions of relevant libraries mentioned above, that get installed when `dagster` is installed:

```
grpcio==1.46.3
grpcio-health-checking==1.43.0
protobuf==4.21.0
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by imrehg** [comment] 2022-05-26 09:16
A current workaround is defining `protobuf<3.21.0` explicitly when installing `dagster` to all into the right version range.

**Comment by smackesey** [comment] 2022-05-26 11:50
Thanks for the report, this will be fixed today by #8078

**Closed by smackesey** 2022-05-26 11:50 UTC
Labels: bug

**Comment by enryls** [comment] 2022-05-26 15:43
Thanks guys, you saved today's deployment!

**Comment by dluo-sig** [comment] 2024-06-05 20:34
It looks like this has resurfaced, but there is no version that satisfies both requirements.

`ERROR: grpcio-health-checking 1.64.1 has requirement protobuf<6.0dev,>=5.26.1, but you'll have protobuf 4.25.3 which is incompatible.`

If I reinstall according to those requirements, I then get this:

`ERROR: dagster 1.7.8 has requirement protobuf<5,>=3.20.0; python_version < "3.11", but you'll have protobuf 5.27.0 which is incompatible.`

There's no overlap between the two ranges.

**Comment by garethbrickman** [comment] 2024-06-06 20:34
@dluo-sig Would you mind sharing the output of `pip freeze` for your environment and a code snippet to repro?

**Comment by dluo-sig** [comment] 2024-06-06 20:39
This happened as I was running through the tutorial.

`admin@dagster-poc:~/dagster/tutorial$ pip freeze
alembic==1.13.1
annotated-types==0.7.0
attrs==19.3.0
Automat==0.8.0
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==23.4.4
colorama==0.4.3
coloredlogs==14.0
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
croniter==2.0.5
cryptography==2.8
dagster==1.7.8
dagster-pipes==1.7.8
dbus-python==1.2.16
distro==1.4.0
distro-info==0.23+ubuntu1.1
docstring-parser==0.16
entrypoints==0.3
filelock==3.14.0
fsspec==2024.6.0
greenlet==3.0.3
grpcio==1.64.1
grpcio-health-checking==1.64.1
httplib2==0.14.0
humanfriendly==10.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
importlib-resources==6.4.0
incremental==16.10.1
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
Mako==1.3.5
markdown-it-py==3.0.0
MarkupSafe==1.1.0
mdurl==0.1.2
more-itertools==4.2.0
netifaces==0.10.4
oauthlib==3.1.0
packaging==24.0
pendulum==2.1.2
pexpect==4.6.0
protobuf==4.25.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pydantic==2.7.3
pydantic-core==2.18.4
pygments==2.18.0
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparted==3.11.2
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.9.0.post0
python-debian==0.1.36+ubuntu1.1
python-dotenv==1.0.1
pytz==2024.1
pytzdata==2020.1
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
rich==13.7.1
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sos==4.5.6
SQLAlchemy==2.0.30
ssh-import-id==5.10
structlog==24.2.0
systemd-python==234
tabulate==0.9.0
tomli==2.0.1
toposort==1.10
tqdm==4.66.4
Twisted==18.9.0
typing-extensions==4.12.1
ubuntu-pro-client==8001
ufw==0.36
unattended-upgrades==0.1
universal-pathlib==0.2.2
urllib3==1.25.8
wadllib==1.3.3
WALinuxAgent==2.2.46
watchdog==4.0.1
zipp==3.19.2
zope.interface==4.7.1
admin@dagster-poc:~/dagster/tutorial$ pip install -force-reinstall "protobuf<6.0dev,>=5.26.1"
Looking in links: orce-reinstall
WARNING: Url 'orce-reinstall' is ignored. It is either a non-existing path or lacks a specific scheme.
Collecting protobuf<6.0dev,>=5.26.1
  Downloading protobuf-5.27.1-cp38-abi3-manylinux2014_x86_64.whl (309 kB)
     |████████████████████████████████| 309 kB 23.0 MB/s
ERROR: dagster 1.7.8 has requirement protobuf<5,>=3.20.0; python_version < "3.11", but you'll have protobuf 5.27.1 which is incompatible.
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.3
    Uninstalling protobuf-4.25.3:
      Successfully uninstalled protobuf-4.25.3
Successfully installed protobuf-5.27.1
admin@dagster-poc:~/dagster/tutorial$ pip install -force-reinstall "protobuf<5,>=3.20.0"
Looking in links: orce-reinstall
WARNING: Url 'orce-reinstall' is ignored. It is either a non-existing path or lacks a specific scheme.
Collecting protobuf<5,>=3.20.0
  Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
ERROR: grpcio-health-checking 1.64.1 has requirement protobuf<6.0dev,>=5.26.1, but you'll have protobuf 4.25.3 which is incompatible.Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.27.1
    Uninstalling protobuf-5.27.1:
      Successfully uninstalled protobuf-5.27.1
Successfully installed protobuf-4.25.3`

**Comment by garethbrickman** [comment] 2024-06-20 02:47
@dluo-sig Circling back here- I stepped through the [tutorial setup](https://docs.dagster.io/tutorial/setup) but I wasn't able to reproduce this error.

Could you try using a virtual environment so that the dependencies are not colliding with what's installed in your local environment? I used [pyenv](https://github.com/pyenv/pyenv) and made a virtual environment using Python version 3.12.2.

**Comment by dluo-sig** [comment] 2024-06-20 14:15
It might just be that.  I have done it several times since reporting this, but haven't run into it again.  Definitely thought I had the venv activated already, though.
