### ISSUE TITLE
Less brutalist color scheme on dagit selection

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1467] opened 2019-06-10 23:55 UTC
![Screenshot 2019-06-10 16 55 07](https://user-images.githubusercontent.com/28738937/59234215-973e9500-8ba0-11e9-9bb9-28d7356c5489.png)

pretty rough

**Comment by mgasner** [comment] 2019-10-08 18:18
Duplicate of #1168

**Closed by mgasner** 2019-10-08 18:18 UTC
Labels: dagit
