### ISSUE TITLE
`Eager` Auto-materialization won't trigger a run after parent data update

### ISSUE THREAD

**Issue by marcilj** [dagster-io/dagster#18012] opened 2023-11-14 19:54 UTC
### Dagster version

dagster, version 1.5.1

### What's the issue?

I've configured `eager` auto-materialization on a couple of assets and even if I have the tag `Upstream Data` that identify that a parent has changed, my auto-materialization policy won't trigger a run.

<img width="299" alt="image" src="https://github.com/dagster-io/dagster/assets/89793010/f4dda3ce-a460-4ac6-9fb5-b4ba600a3af9">

<img width="711" alt="image" src="https://github.com/dagster-io/dagster/assets/89793010/136b318c-1bf4-402d-b9d3-08f8ca2e5282">

<img width="631" alt="image" src="https://github.com/dagster-io/dagster/assets/89793010/d2a926e7-0146-43f8-be5b-1cf2c67da799">

<img width="1454" alt="image" src="https://github.com/dagster-io/dagster/assets/89793010/ee6528e4-1693-44f6-aa50-974db09da092">

### What did you expect to happen?

That since a parent changed, the `eager` policy would trigger a run when doing the evaluation.

### How to reproduce?

I've configured `observable_source_asset` on all sources that I don't control with `Dagster` and then configured all downstream asset with the default `eager` configuration.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-11-15 17:11
Hey @marcilj - thanks for the detailed report. This looks unexpected. Does this reproduce reliably? Were there any runs launched (auto-materialize or otherwise) for the downstream asset since the upstream asset updated.

**Comment by marcilj** [comment] 2023-11-16 14:53
Hey @sryza, sadly this version of the code was lost while doing all my tests.

I've reproduce something similar here https://github.com/dagster-io/dagster/issues/18042 with a small code change on the `fully-featured-project` so it's easier to reproduce.

I've explain what I changed in the description of the issue.

**Comment by sryza** [comment] 2023-12-04 16:24
I'm going to close this for now because it's not clear where to continue down the trail. Please reopen if you're able to reproduce this.

**Closed by sryza** 2023-12-04 16:24 UTC
Labels: type: bug, area: auto-materialize
