### ISSUE TITLE
UI hangs rendering Globla Lineage Graph of only 200 assets

### ISSUE THREAD

**Issue by cohenj20** [dagster-io/dagster#20634] opened 2024-03-21 20:27 UTC
### Dagster version

dagster, version 1.6.11

### What's the issue?

I'm running into a strange dagster UI problem. 

I'm using dagster to visualize a dependency graph for objects in my company's DW. I essentially am using an asset factory pattern that receives a csv of different objects and their parents and iteratively generates assets with the proper dependencies. The dagster deployment loads without issues, and navigating the assets within the deployment I can see that the asset factory correctly grouped assets and linked them to their parents/children. When I go to load the global lineage graph, however, graph hangs on "Rendering a large number of assets, please wait…" and never renders. 

### What did you expect to happen?

I expect that the lineage graph renders quickly, as according to [this blogpost](https://dagster.io/blog/scaling-dag-visualization) dagster should be capable of rapidly rendering far more than 200 assets now.

### How to reproduce?

Use the below asset factory code (`asset.py`) and the `__init__.py` definition code below in a generic dagster project, placing the attached `test_hierarchy.csv` in the directory and startup the UI. Go to global lineage graph to see whether the assets render. 

[test_hierarchy.csv](https://github.com/dagster-io/dagster/files/14706781/test_hierarchy.csv)

```py

# assets.py

from importlib.metadata import metadata
import json
import os
from tokenize import group
from unicodedata import name

from dagster import asset, Output, MetadataValue, AssetExecutionContext # import the `dagster` library
import pandas as pd
from pandas import DataFrame
from sqlalchemy import create_engine

view_df = pd.read_csv('../test_hierarchy.csv')

single_parent_df = view_df[view_df['parent_count'] == 1]

multiple_parent_df = view_df[view_df['parent_count'] > 1]

assets = []

for i, view in single_parent_df.iterrows():
    if single_parent_df['parentname'][i] == 'None':
        @asset(name=single_parent_df['objectname'][i], group_name=single_parent_df['objectschema'][i]) # add the asset decorator to tell Dagster this is an asset
        def compute(context: AssetExecutionContext):

            context.add_output_metadata({
                "data_preview" : MetadataValue.md(view_df.head().to_markdown())
            })

        assets.append(compute)
    else:
        @asset(name=single_parent_df['objectname'][i], deps=[single_parent_df['parentname'][i]], group_name=single_parent_df['objectschema'][i]) # add the asset decorator to tell Dagster this is an asset
        def compute(context: AssetExecutionContext):

            context.add_output_metadata({
                "data_preview" : MetadataValue.md(view_df.head().to_markdown())
            })
        
        assets.append(compute)


for object in list(multiple_parent_df['objectname'].unique()):

    deps = list(view_df[view_df['objectname'] == object]['parentname'])

    object_schema = list(multiple_parent_df[multiple_parent_df['objectname'] == object]['objectschema'])[0]

    @asset(name=object, deps=deps, group_name=object_schema) # add the asset decorator to tell Dagster this is an asset
    def compute(context: AssetExecutionContext):
        # table_preview = pd.read_sql(f"SELECT TOP 10 * FROM {view_df['objectschema'][i]}.{view_df['objectname'][i]}", con)

        pass

    assets.append(compute)

```

```python

# __init__.py

from dagster import Definitions, load_assets_from_modules

from .assets import assets

all_assets = load_assets_from_modules([assets])

defs = Definitions(
    assets=(assets),
)

```

### Deployment type

Local

### Deployment details

Running dagster locally. Using a python venv.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by bengotow** [comment] 2024-04-02 21:06
Hey folks, I pulled down the sample above (thank you for the clear repro!) and loaded it up, but I'm not able to reproduce the UI hanging on the latest `master` branch. I tried opening/closing the asset groups, etc. We did update Dagre in the last two weeks, so it's possible that impacted this behavior. I'm going to revert that dagre upgrade and see if this repro'd with the old version.


<img width="1728" alt="image" src="https://github.com/dagster-io/dagster/assets/1037212/bd3e4e92-b5e6-4cdb-a3d1-91b77682abab">

**Comment by cohenj20** [comment] 2024-04-10 13:09
Hey @bengotow

> We did update Dagre in the last two weeks, so it's possible that impacted this behavior. I'm going to revert that dagre upgrade and see if this repro'd with the old version.

Was there any change in the UI behavior after reverting?

**Comment by cohenj20** [comment] 2024-04-10 14:45
I uninstalled and re-installed `dagster`, `dagster-webserver`, and `dagster-pandas` and the problem was resolved.

**Comment by cohenj20** [comment] 2024-04-10 14:55
Unfortunately, in the test I ran before closing the issue I used the wrong dependency table (not the one I provided for reproduction when I opened the issue). Usig the proper data set the problem seems to have persisted through the version upgrades.

![image](https://github.com/dagster-io/dagster/assets/156207045/3ba51d1c-b3ac-4a2b-90da-0e5e9ae1d72e)

**Comment by salazarm** [comment] 2024-04-10 16:00
Hi @cohenj20, We're aware of an [issue with dagre ](https://github.com/dagrejs/dagre/issues/234) (the layout library we use) and are trying to figure out how to mitigate it. For now the best I can offer is a work-around. If you update the URl to be `/asset-groups?expanded=fake` (The key here is the `expanded=fake`) this will reset all of the groups to closed. The issue only happens when certain combinations of groups are open so try not to open all of the groups at once.

**Comment by salazarm** [comment] 2024-04-10 16:15
@cohenj20 Try `/asset-groups?expanded=fake&open-nodes%5B%5D=fake`

**Comment by cohenj20** [comment] 2024-04-10 16:21
@salazarm No dice :/

I also tried creating a fresh dagster project, but it still hangs.

**Comment by cohenj20** [comment] 2024-04-10 16:24
@salazarm I may have discovered something...

I was messing around with which combinations of asset groups cause the issue, and I noticed that if the `report` asset group is selected, even if it's the only asset group selected, the UI hangs. As long as `report` is unselected, all assets display instantly on the graph.

**Comment by salazarm** [comment] 2024-04-10 16:25
@cohenj20 Do you see any errors in the developer console? If so can you share them here

**Comment by cohenj20** [comment] 2024-04-10 16:27
@salazarm I do not see anything.

**Comment by salazarm** [comment] 2024-04-10 16:29
Would you be open to a zoom call so I can take a look? Keen on getting to the bottom of this.

**Comment by salazarm** [comment] 2024-04-10 16:30
> I was messing around with which combinations of asset groups cause the issue, and I noticed that if the report asset group is selected, even if it's the only asset group selected, the UI hangs. As long as report is unselected, all assets display instantly on the graph.

I will pull on this thread

**Comment by salazarm** [comment] 2024-04-10 16:34
@cohenj20 Yes that would work for me. Feel free to pop into https://meet.google.com/zje-xrev-vig?hs=122&authuser=0, I'll be waiting in there.

**Comment by salazarm** [comment] 2024-04-10 16:56
@cohenj20 I believe the issue you're facing is that the screen just looks blank? Correct? If so, I think there isn't actually a bug, it's just the default zooming took you to a spot where there where no assets. Try clicking on an asset in the sidebar to see if it zooms you to it.

**Comment by cohenj20** [comment] 2024-04-10 17:43
For visibility, on the zoom call @salazarm and I confirmed there was the following error in the developer console:

```
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://127.0.0.1:3000/_next/static/chunks/framework-d6095a5336d3e425.js' failed to load.
    at __webpack_require__.f.i (http://127.0.0.1:3000/_next/static/chunks/358.85428c524e2522c9.js:1:2431)
    at http://127.0.0.1:3000/_next/static/chunks/358.85428c524e2522c9.js:1:1317
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (http://127.0.0.1:3000/_next/static/chunks/358.85428c524e2522c9.js:1:1265)
    at Array.map (<anonymous>)
    at __webpack_require__.x (http://127.0.0.1:3000/_next/static/chunks/358.85428c524e2522c9.js:1:2853)
    at http://127.0.0.1:3000/_next/static/chunks/358.85428c524e2522c9.js:1:2935
    at http://127.0.0.1:3000/_next/static/chunks/358.85428c524e2522c9.js:1:2939
```

**Comment by salazarm** [comment] 2024-04-10 17:43
This will be fixed by https://github.com/dagster-io/dagster/pull/19046

**Comment by salazarm** [comment] 2024-04-10 17:51
https://github.com/dagster-io/dagster/pull/21129/ *

**Closed** 2024-04-10 17:54 UTC
Labels: type: bug, type: UI/UX usability, area: UI/UX
