### ISSUE TITLE
Disable re-execution of solid subselection if in-memory storage is used

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3625] opened 2021-01-29 03:16 UTC
## Summary

Otherwise, new pipeline will fail with a weird error: https://www.loom.com/share/35e58726b4a54ef3838eb2194d861fac

I think this is a regression? from IOManagers?

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment] 2021-02-15 17:24
Yeah it looks like this is actually a graphql-level regression - if you run with in memory persistence, `run.executionPlan.artifactsPersisted` is still `true`, which causes the options to be enabled. Going to see if I can track this down!

**Comment by bengotow** [comment] 2021-02-15 17:35
OK, I think I've tracked this down but I'm not sure what the appropriate fix is.

On the backend, `plan.artifacts_persisted` seems to have changed meanings slightly. The doc now reads:

```
        Check if all the border steps of the current run have non-in-memory IO managers for reexecution.

        Border steps: all the steps that don't have upstream steps to execute, i.e. indegree is 0).
```

This seems to be checking that the step subset you've selected to run has persisted upstream inputs, NOT whether the step subset you are about to run is persisting it's outputs.

Given a full-pipeline execution of longitudinal_pipeline with in_memory persistence, this function looks at the first two steps (ingest_traffic and ingest_costs), sees that they have no `step.step_inputs` and returns without checking any IO manager types.

**Comment by bengotow** [comment] 2021-02-15 17:38
cc @sryza + @yuhan, curious what you guys think!

**Comment by yuhan** [comment] 2021-02-16 20:04
> OK, I think I've tracked this down but I'm not sure what the appropriate fix is.
> 
> On the backend, `plan.artifacts_persisted` seems to have changed meanings slightly. The doc now reads:
> 
> ```
>         Check if all the border steps of the current run have non-in-memory IO managers for reexecution.
> 
>         Border steps: all the steps that don't have upstream steps to execute, i.e. indegree is 0).
> ```
> 
> This seems to be checking that the step subset you've selected to run has persisted upstream inputs, NOT whether the step subset you are about to run is persisting it's outputs.
> 
> Given a full-pipeline execution of longitudinal_pipeline with in_memory persistence, this function looks at the first two steps (ingest_traffic and ingest_costs), sees that they have no `step.step_inputs` and returns without checking any IO manager types.
> 
> I think this should likely change to check the step outputs for persistence rather than the inputs and do it for the entire graph and not steps_to_execute level 0?

@bengotow it was caused by https://dagster.phacility.com/D5696 which wasn't a perfect solution. I'm happy to change it.

The tricky part was to determine the real value of "artifactsPersisted" from the execution plan. In the current IO manager world, IO managers can be configured at step output level, so whether to enable the re-execution button will differ by the step output. For example, say we have a pipeline like this:
![image](https://user-images.githubusercontent.com/4531914/108114550-cbdd4200-704d-11eb-981a-e6cc0f1fb90c.png)
where `solidA.output1` uses non-persistent IO manager and `solidA.output2` uses persistent IO manager. In this case, the different re-execution cases are:
1. we will disable the re-execution for `solidB*` because `solidA.output1` isn't a persisted artifact. 
2. we can enable the re-execution for `solidC*` because `solidA.output2` is a persisted artifact.  
3. full pipeline re-execution is always enabled.
4. it doesn't matter whether `solidD.output` is persistent for re-execution of `solidB*` or `solidC*`, because they only depend on solidA's outputs. If we do a full scan of the entire graph, we will disable the `solidC*` re-execution which is actually able to be re-executed.

To cover these cases, we ended up checking the edges of the graph in https://dagster.phacility.com/D5696.

This wasn't a problem in the old intermediate storage world. The intermediate storage is configured at the pipeline level, so given a persistent intermediate storage(e.g. filesystem intermediate storage), we will know every step output's artifactsPersisted is true, so we could enable the step re-execution for all cases.

**Comment by yuhan** [comment] 2021-02-16 20:11
As for this specific problem, i think it entered a weird the intermediate storage deprecation edge case. I took a look at the root pipeline run (`13f6a426`), the run config says it's using filesystem intermediate storage. When using intermediate storage, it shouldn't go to the io manager re-execution check at all. The error was raised from [object_store.cp_object](https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/core/storage/object_store.py#L172:27), which shouldn't be called on the io manager path either.

I will dig into it more today (sorry i shouldve looked into this earlier)- should have a fix by tomorrow.

**Comment by yuhan** [comment] 2021-02-17 08:11
ran the pipeline with the s3 intermediate storage (see the following run config) and partial re-execution worked. 
```
storage:
  s3:
    config:
      s3_bucket: ...
      s3_prefix: ...
```

the problem here isn't about io managers. it is because the pipeline didn't use the proper intermediate storage config, which is tracked here https://github.com/dagster-io/dagster/issues/3133

**Comment by yuhan** [comment] 2021-02-17 19:03
Closing this issue.

Summary: This issue is purely about intermediate storage’s compatibility with run launchers.
Landed a fix just now. Will track mid-term solution in https://github.com/dagster-io/dagster/issues/3133 (intermediate storage will be removed after this deprecation cycle so it's only a mid-term solution)

-----

This issue also surfaces the confusion of whether the pipeline run used io managers or intermediate storage. The InMemoryIOManager resource will always be init (even when it's not being used), which means users will see that shows up in the logs. This behavior confuses debugging, esp when debugging this issue. This confusion should only happen in this intermediate storage deprecation period, but I will explore a better way to surface the error to avoid the confusion.

**Closed by yuhan** 2021-02-17 19:03 UTC
Labels: bug, dagit
