### ISSUE TITLE
Cache capability for solids

### ISSUE THREAD

**Issue by ido-tera-group** [dagster-io/dagster#1993] opened 2019-12-15 08:50 UTC
Would be nice if there was a capability to cache the output of the solids in the pipeline in such a way that if I run the same pipeline but with a slightly different configuration (think hyper-parameter tuning), certain initial steps in the pipelines that are unaffected by the configuration changes will not be executed multiple times?

```Raw data -> CPU expensive preprocessing (A) -> model fitting (B) -> model```

I want to be able to run A once, but multiple variations of B.

I started working on a cache() decorator for this task, but it's not very straight-forward, as solids could be either functions or generators, etc...

**Comment by jdb78** [comment] 2020-03-15 15:37
This would be a really valuable feature in my view.

I implemented this once for a (slightly simpler) case and taking the hash of the entire (cleaned-up) source code that generated the output solved most of the problem. Another major challenge is to ensure only taking partial hashes of input arguments that are used, e.g. if you pass a config dictionary, you do not want to hash the entire dictionary but only the relevant/used parts. If you depend on data inputs, the data's timestamp should be also added to the hash.

**Comment by mgasner** [comment] 2020-03-29 22:48
#1784 #2303

**Comment by mgasner** [comment] 2020-05-27 22:01
closing as a duplicate of #1784

**Closed by mgasner** 2020-05-27 22:01 UTC
Labels: core
