### ISSUE TITLE
GraphQL bug

### ISSUE THREAD

**Issue by SeppBerkner** [dagster-io/dagster#23987] opened 2024-08-27 22:27 UTC
### Dagster version

1.8.2

### What's the issue?

When running `dagster dev` I get an error in a popup in dagster UI when starting a materialization of a job and whenever I come back to the run overview page with the following message:

```
Operation name: {PipelineRunLogsSubscription}

Message: FSEventsObserver.schedule() takes 3 positional arguments but 4 were given

Path: 

Locations:
``` 

![grafik](https://github.com/user-attachments/assets/b12b70a9-50f9-4610-a600-c1e01979bf3e)

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by cmpadden** [comment] 2024-08-27 22:30
Hi @SeppBerkner - I believe this is a duplicate of this error:

https://github.com/dagster-io/dagster/issues/23957

For the time being you can downgrade cloudwatch to <5.0.0, a fix has been applied for next release.

**Comment by SeppBerkner** [comment] 2024-08-27 22:47
Hi Colton. Yes, it seems so. It doesn't interfere with my work right now so I will wait patiently for the new release. :)

**Closed** 2024-08-28 14:12 UTC
Labels: type: bug
