### ISSUE TITLE
Backfills successful steps not colored in

### ISSUE THREAD

**Issue by j-hulbert** [dagster-io/dagster#3971] opened 2021-03-30 18:52 UTC
## Summary
Within the dagit backfill screen after two backfills were run only some of the steps are marked as green but all steps were executed successful
If you click on one of the other steps you can see it was executed successfully but it isn't colored in green

## Reproduction
Run backfill for multiple days. Once complete review the backfill screen.

## Dagit UI/UX Issue Screenshots
For last 2 partitions - some steps are white, some are green but all steps were successful
![backfill](https://user-images.githubusercontent.com/78444285/113040939-6067b380-9167-11eb-84a7-ec9f6e1888fb.png)
Step that was successful can be clicked on and see the results
![backfill2](https://user-images.githubusercontent.com/78444285/113040797-36ae8c80-9167-11eb-9b11-a1476eac9ada.png)
![backfill3](https://user-images.githubusercontent.com/78444285/113040804-38785000-9167-11eb-9ad4-01bcffbcc803.png)

## Additional Info about Your Environment
Dagster 0.11.2

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by j-hulbert** [comment] 2021-03-30 18:55
The steps that aren't colored in are composite solids so this may be a duplicate of #3961

**Comment by yuhan** [comment] 2021-04-13 20:43
duplicate of https://github.com/dagster-io/dagster/issues/3961

**Closed by yuhan** 2021-04-13 20:43 UTC
Labels: backfills, bug, dagit, partitions view, practitioner
