### ISSUE TITLE
Add configuration to disable colors in dbt run output

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#7150] opened 2022-03-21 18:48 UTC
## Use Case
When streaming event logs from the dagster dbt integration, there are ANSI escape sequences. These might be nice for local dev, but in production, there should be configuration to turn this off so that the event logs in Dagit are more readable. 

Or we could just default to no colors entirely.

## Ideas of Implementation
Use https://github.com/dbt-labs/dbt-core/pull/2622

## Additional Info

<img width="1148" alt="Screen Shot 2022-03-21 at 11 46 18 AM" src="https://user-images.githubusercontent.com/16431325/159342974-111bcdf3-1311-4da7-9a9f-2fe702d9678a.png">

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by sryza** [comment] 2022-03-29 21:09
Arguably a duplicate of https://github.com/dagster-io/dagster/issues/6961

**Closed** 2022-05-02 20:01 UTC
Labels: feature-request, dagster-dbt
