### ISSUE TITLE
DBT Assets fail to build when using model versions

### ISSUE THREAD

**Issue by ytoast** [dagster-io/dagster#17672] opened 2023-11-03 07:08 UTC
### Dagster version

dagster==1.4.5, dagster-dbt==0.20.5

### What's the issue?

My team is using dbt v1.5 that supports model versions
https://docs.getdbt.com/docs/collaborate/govern/model-versions

When we implement dbt model versioning, our dbt assets fail to create the dependencies on dagster with the following error:
```
 dagster._check.CheckError: Invariant failed. Description: Invalid asset dependencies:
```
I believe it's because of https://github.com/dagster-io/dagster/blob/f981a75013f9baad57e40e2984a6f86b58c6d2c8/python_modules/libraries/dagster-dbt/dagster_dbt/utils.py#L45-L48

### What did you expect to happen?

Assets should build correctly with or without model versioning

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment] 2023-11-03 14:39
Duplicate of https://github.com/dagster-io/dagster/issues/16046.

**Closed by rexledesma** 2023-11-03 14:39 UTC
Labels: type: bug
