### ISSUE TITLE
User logging does not show up

### ISSUE THREAD

**Issue by Oliver-Sellwood** [dagster-io/dagster#4226] opened 2021-05-28 03:28 UTC
## Summary

When logging within solids with `context.log`, the logs do not find their way to `stdout`.

Additionally, something in Dagster seems to be messing with the Python's built in logger as these also do not show up in logs. 

Not sure if related to #2808

## Reproduction

 Repro here https://gitlab.com/oliver-sellwood/logging-repro
Follow instructions in the `README.md`

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment] 2021-05-28 17:35
@prha do you have any guess about what's going on here?

**Comment by Oliver-Sellwood** [comment] 2021-06-04 00:10
Hi I did a little more digging and found some things; though I should record them here.

1. Within a docker container - running the pipeline using `dagster.execute_pipeline(count, config)` directly from Python and the logs are shown. (i.e without executing the runs through dagit)

2. Outside of a docker container - installing the project in a python virtual env and running through Dagit the logs do show up.

3. The logs do show up in `${DAGSTER_HOME}/storage/${RUN_ID}/compute_logs/${LOG_LEVEL}.out` when running through Dagit in Docker. Just not in `stdout`

4. Setting log level to debug does not show debug logs from `context.log.debug(...)` -- this is probably deserving of its own issue but it's just something I briefly noticed and haven't had a chance to verify and follow up on.

There is probably some incredibly stupid user error here where I have misunderstood some docs, would really appreciate a little input though.. I have spent so much time trying to debug this already

**Comment by alangenfeld** [comment] 2021-06-04 14:42
One thing to point out is that `stderr` is where the logs get sent https://github.com/dagster-io/dagster/issues/3566#issuecomment-852440404

> when running through Dagit in Docker

Can you be precise about how you are running things and where exactly you are looking for logs?

**Comment by Oliver-Sellwood** [comment] 2021-06-05 00:12
> when running through Dagit in Docker

please refer to reproduction steps in `README.md`  in [the reproducing repo](https://gitlab.com/oliver-sellwood/logging-repro )


from the issue you referenced, I do get these logs. i.e ones shown in this image

https://user-images.githubusercontent.com/12679869/105249277-df2be900-5b45-11eb-8826-0b66274c5762.png
  
whats missing is anything  from `context.log.{info|debug|error|warning}` logged within the solids

**Comment by alangenfeld** [comment] 2021-06-07 21:48
Thank you for the details, I was able to reproduce the issue. Unfortunately I was not able to figure out the exact cause.

It would seem the mechanisms that the default `LocalComputeLogManager` uses to tail & capture `stderr` are not working as expected in this context. I can see the log entries in the captured file in `$DAGSTER_HOME/storage/<run_id>/compute_logs/<solid_name>.err` but they are not correctly tailed back out to the original stderr.

One workaround for now is to disable the local compute log manager by setting up an instance configuration in `$DAGSTER_HOME/dagster.yaml` of
```
compute_logs:
    module: dagster.core.storage.noop_compute_log_manager
    class: "NoOpComputeLogManager"
```

**Comment by Oliver-Sellwood** [comment] 2021-06-08 21:07
Thank you!! This works :)

Two possibly unrelated observations from when I was debugging:
1. I am deploying with k8s, when I overload the system with pipeline runs some of the log messages were making it into my log collection system.
2. I implemented a custom `dagster.Logger` that added a handler that would send the logs to my log stack (Elasticsearch). This didn't work because and after putting debug statements through the log flush function I noticed the process would enter the flush function but never made it as far as the indexing call

**Comment by Oliver-Sellwood** [comment] 2021-06-08 21:21
@alangenfeld sorry to hijack this issue but would you mind looking at this question -- my deadline is fast approaching and I believe this is final outstanding Dagster issue

https://dagster.slack.com/archives/C01U954MEER/p1623187049065200

**Comment by sryza** [comment] 2021-06-17 18:16
@alangenfeld is there likely an underlying Dagster bug that's causing this issue?  Is there a more specific name for this issue that would capture the kinds of situations where we suspect this occurs?

**Comment by prha** [comment] 2021-06-17 18:25
@sryza this is because we're writing some events from outside a pipeline execution context (which instantiates the logger).  This class of events are generally written from the daemon process (run coordinator, sensor, schedule, backfill, etc).  We need to be able to configure an instance-level logger to capture these.

**Comment by sryza** [comment] 2022-03-21 21:02
I'm going to close this issue because I think it touches on a few different gaps, which are covered by separate issues.

**Closed by sryza** 2022-03-21 21:02 UTC
Labels: bug, logging
