### ISSUE TITLE
Dagster-dbt: DBT cli operators do not work for all relative paths

### ISSUE THREAD

**Issue by karelserruys-foodpairing** [dagster-io/dagster#16065] opened 2023-08-24 09:55 UTC
### Versions
Python 3.9.13
dagster 1.4.7
dagster-dbt 0.20.7
dbt 1.6.0

### Reproduce Issue
Setup dagster in the root of a new repository
Add a dbt project using `dbt init` to the repository root with name `test_dbt`

Create a simple job:
```
from dagster import job
from dagster_dbt import dbt_build_op, dbt_cli_resource

@job(resource_defs={"dbt": dbt_cli_resource})
def my_dbt_job() -> None:
    dbt_build_op()
```

Run `dagster dev` in your CLI
Start the job with configuration:
```
resources:
  dbt:
    config:
      bypass_cache: false
      capture_logs: true
      dbt_executable: dbt
      debug: false
      ignore_handled_error: false
      json_log_format: true
      project_dir: test_dbt
      target_path: target
      warn_error: false
```

The operation will fail because of the following lines:
https://github.com/dagster-io/dagster/blob/5a53770dd0a9fb2527604da937527614e0cc087a/python_modules/libraries/dagster-dbt/dagster_dbt/core/utils.py#L135..L140

### Solution
The dbt command used is the following: 
```
dbt --no-use-colors --log-format json build --project-dir test_dbt
```

But due to L140, we change the cwd where the command is being executed.
As a result, the paths passed for project-dir is not longer correct.

Currently there are two workarounds:
1. Use absolute paths, which is what I'll be doing because I'm tied to my current repository structure.
2. Setup dagster and dbt like it's done in the dagster+dbt tutorial, where dagster is run from folder `jaffle_dagster`. In the run config you set project_dir to `../test_dbt`. The folder you end up looking for the dbt_project.yml file is then the same if you're looking from withing `jaffle_dagster` or from within `test_dbt`... 

To solve the problem completely, removing L140 should do the trick.

**Comment by tacastillo** [comment] 2023-08-24 22:51
Hi! It looks like you're using deprecated functions. Our docs have the latest APIs on [how to use dbt and Dagster](https://docs.dagster.io/integrations/dbt).

**Comment by karelserruys-foodpairing** [comment] 2023-08-25 13:48
> Hi! It looks like you're using deprecated functions. Our docs have the latest APIs on [how to use dbt and Dagster](https://docs.dagster.io/integrations/dbt).

Thanks for your reply @tacastillo, I read the deprecation warning on function `dbt_cli_resource`, but I did not see one on DbtCliClient. Nor did I see one on `dbt_build_op`: https://docs.dagster.io/_apidocs/libraries/dagster-dbt#ops-dbt-core

Are these deprecated as well?

**Comment by tacastillo** [comment] 2023-08-25 15:15
Let me see if I can get you an accurate answer on that and if we need to add the deprecation warning to those APIs.

The current recommendation for running dbt is with the `DbtCliResource`'s [.cli()](https://docs.dagster.io/_apidocs/libraries/dagster-dbt#dagster_dbt.DbtCliResource.cli) method.

**Comment by rexledesma** [comment] 2023-08-28 19:32
Duplicate of https://github.com/dagster-io/dagster/issues/14069.

**Closed by rexledesma** 2023-08-28 19:32 UTC
