### ISSUE TITLE
dagster_celery_docker fails to receive stderr from container

### ISSUE THREAD

**Issue by michaelkrukov** [dagster-io/dagster#2754] opened 2020-07-27 16:13 UTC
We had issues inside of the worker container (couldn't import module). This caused the following error:

![image](https://user-images.githubusercontent.com/13236694/88562363-46565e00-d039-11ea-95ea-b3145b5518f6.png)

Looks like this line causes an error (https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-celery-docker/dagster_celery_docker/executor.py#L305) as `err.stderr` is `None` instead of the string. Running the command from the insides of the container showed usual python traceback with ModuleNotFound.

Dagster version: 0.8.8

**Comment by catherinewu** [comment] 2020-07-27 22:53
Hi @michaelkrukov, thanks for reporting this issue and digging in to find the cause! We'll have a fix out shortly https://dagster.phacility.com/D4019

**Comment by catherinewu** [comment] 2020-07-28 21:48
should be fixed

**Closed** 2020-07-28 21:48 UTC
