### ISSUE TITLE
Partition matrix does not show correct partition state after partial backfills

### ISSUE THREAD

**Issue by aroig** [dagster-io/dagster#10159] opened 2022-10-23 16:40 UTC
### Dagster version

commit ca87aa3c95204c7941e675318f714d24a4990132

### What's the issue?

On a repo with several partitioned assets, a backfill of only one asset would hide previous state of partitions in the asset x partition matrix on Job > Partitions > Show per-step status.

Here is  a picture of the partition matrix after a partial backfill. The dots for asset 1 which were previously green are now white. However, clicking one dot still shows the correct run history.
![after-partial-backfill](https://user-images.githubusercontent.com/1743143/197404078-8d26c052-a6b0-47ec-93fb-a30870445202.png)

### What did you expect to happen?

I would expect that after a partial backfill, the assets that were not touched, keep the state they had before (red or green color) on the partition matrix.

### How to reproduce?

With the following code

``` python
import dagster

partitions = dagster.StaticPartitionsDefinition(["A", "B", "C"])

@dagster.asset(
    partitions_def=partitions,
    group_name="all"
)
def asset_1():
    return 1

@dagster.asset(
    partitions_def=partitions,
    group_name="all"
)
def asset_2(asset_1: int):
    return asset_1 + 1

job_all = dagster.define_asset_job(
    name="all",
    selection=dagster.AssetSelection.groups("all")
)

@dagster.repository
def my_repository():
    return [
        asset_1,
        asset_2,
        job_all,
    ]
```
* Go to job "all" > Overview > Materialize button. Select all partitions, to materialize everything.
* Partitions page would show a green partition bar, and when expanding the asset x partition matrix, all dots are green.
* Go to job "all" > Overview. Select asset_2, and Materialize button. Then Select all partitions.
* After the backfill is complete, go to Partitions page. The partition bar shows all partitions green, as expected. However, if you expand the asset x partition matrix, all dots for asset_1 are blank now.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2022-10-24 21:19
@prha - does this look like the expected behavior to you?

I believe it may be the expected behavior, because the Partitions tab of the Job page takes a run-oriented view of partitions, rather than an asset-oriented view.  From the run-oriented perspective, the status of a Job partition is based on the most recent run that targeted that partition.

That said, for asset jobs I do believe it would be valuable to take an asset-oriented view here. In that world, the rows in the matrix should probably be assets instead of steps.  @braunjj @bengotow @hellendag - thoughts?

**Comment by prha** [comment] 2022-10-25 21:46
Yeah, this is expected behavior... The partitions view is run oriented, where the norm is that all the ops of a job are executed.

If we could detect that the job is an asset-based job, we might be able to do some sort of layered UI, where we see that asset A has at some point been materialized.

This partition view is especially problematic when dealing with partition-mappings where any given op is mapped to a unique partition space.

**Comment by aroig** [comment] 2022-10-27 06:39
Ok, thanks for the explanation! As a user, I find myself wanting to see the state of all my assets and partitions at a given point in time, and I keep wanting to use the asset x partition matrix view for that.

The other way I know to see the global state of partitions, is via the Materialize dialog, where the partitions bar can be expanded to a per-partition bar for the assets in the job.

For me, the current behaviour of the assets x partitions matrix of showing only last run has limited value. The only case where it is useful to me, is to track progress of a long backfill. It is also a bit counterintuitive.

But I understand that on a job without assets, with only ops, it makes sense to show state of last run / backfil.

So, I am actually asking a couple of things, I believe:
1. for asset-based jobs, track state of the asset, instead of success of failure of the associated op, which I think is the current behaviour.
2. Show the actual state of the asset, not what happened on last run.

As @prha suggested, point 1 may be messy if a job mixes assets with ops, which I think is possible.

Maybe a better solution would be to keep the Job > Partitions page as it is, run oriented, and then add an Asset > Partitions page, that shows global state of all the assets x partitions?

What do you think?

**Comment by sryza** [comment] 2022-10-28 14:58
> point 1 may be messy if a job mixes assets with ops, which I think is possible.

I don't think we need to worry about this, at least for a while. Right now, a job is either an asset job or an op job.

> So, I am actually asking a couple of things, I believe:

I agree with you on both of these. If our frontend engineers weren't busy with other things at the moment, I'd say we should make this change now.

**Comment by bengotow** [comment] 2022-10-28 21:21
I was talking with @braunjj last week about the future of the Partitions tab for asset-based jobs and we were thinking through the same changes.  The current state of things is definitely confusing and showing an `asset X partition` grid would be better and more consistent with other asset pages. 

We've got some other things to knock out first but I think we'll definitely be fixing this. Thanks for flagging it!

**Comment by NicolasPA** [comment] 2022-11-09 13:11
We already have a switch in the "Overview" tab to display an asset job graph as the underlying op job graph (which is really cool, especially for graph backed assets).
Why not also having a switch in the Partitions tab allowing to switch between the "last op run" view and the "asset partition completion" view?

**Comment by simonvanderveldt** [comment] 2022-11-14 14:38
> That said, for asset jobs I do believe it would be valuable to take an asset-oriented view here. In that world, the rows in the matrix should probably be assets instead of steps. @braunjj @bengotow @hellendag - thoughts?

@sryza How would this work in case of graph backed assets? IMHO it would be very desirable to be able to have an overview of the (current) status of all Ops per partition for graph backed Assets.

**Comment by prha** [comment] 2022-11-14 16:58
I was wrong about intended behavior.  We are fetching last run history, so we should be able to display some notion of previous state.  I just landed https://github.com/dagster-io/dagster/pull/10478 which should give some indication.  This will go out in the next release this week.

**Closed** 2023-05-11 21:23 UTC
Labels: bug, dagit
