### ISSUE TITLE
Dynamically construct N solids to execute in sequence

### ISSUE THREAD

**Issue by hui-zheng** [dagster-io/dagster#3530] opened 2021-01-12 18:18 UTC
## Use Case

Exciting about the upcoming dynamic orchestration mapping. I have a use case that I hope the dagster would support in the future. 

**A general concept**
I have a solid_A that generates N outputs. I would like the pipeline to dynamically construct N solids_B for each of the N outputs that could then execute in sequence (not in parallel). 
Those solid_Bs need to be executed in sequence, that is, solid_B_0 executes first, and then solid_B_1 follows, and then solid_B_2 follows. If a solid_B_i failed, all the subsequence solid_Bs could be skipped or failed.

Now each solid_B_i returns an output, item_b. After all solid_Bs execute, I have a list_B of solid_B_i_output.
I could then define a solid_C, which takes list_B , the results of all solid_Bs, to carry some work. which is like a reduce operation of the upstream solid_Bs.

**the real use case**
We have a pipeline that is backfilling some time-series data in BigQuery. Because the data is huge, it can not be done in one shot and have to divide the processing into several segments, and because of the time dependency, those segments need to be executed in sequence, one by one. In addition, because the period of backfill is provided as an input param which could be different every time, the flow won't be able to know the exact N number of the segments it need to process until at the run-time. 
So this pipeline first needs to (solid A) generate a sequence of backfill commands, which are dbt runs against BigQuery, and run each dbt-run in sequence (solid B), and finally to act on the success or failure result of overall backfill processing (solid C).

## Ideas of Implementation
We are currently using Prefect, which requires some work-around to achieve this use case. I don't have an idea yet how to implement it in Dagster.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by alangenfeld** [comment] 2021-03-31 22:01
this should be possible using the dynamic output & collect released in `0.11.0` and using the `in process` executor which will process solids serially

**Closed by alangenfeld** 2021-03-31 22:01 UTC
Labels: feature-request, practitioner

**Comment by MalteEbner** [comment] 2023-02-14 09:48
I tried it with this approach. However, it does not work if you want a sequence of ops to execute multiple times in sequence:

> Start -> A_0 -> B_0 -> A_1 -> B_1 -> ..... A_n -> B_n -> End

The problem is that A_1 starts as soon as A_0 has finished and does not wait till B_0 has finished.

Is there a solution for that?

**Comment by alangenfeld** [comment] 2023-02-14 15:44
https://github.com/dagster-io/dagster/discussions/8871
