### ISSUE TITLE
Installing dagster fails at setup.py docstring-parser==0.7.1

### ISSUE THREAD

**Issue by manoharuss** [dagster-io/dagster#3832] opened 2021-03-11 20:54 UTC
## Summary

Installation of dagster fails at `docstring-parser` from pypi.

```
$ pip install dagster==0.10.6
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting dagster==0.10.6
  Downloading dagster-0.10.6-py3-none-any.whl (926 kB)
     |████████████████████████████████| 926 kB 3.8 MB/s 
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.5/site-packages (from dagster==0.10.6) (2.8.1)
Collecting PyYAML
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting protobuf>=3.13.0
  Using cached protobuf-3.15.6-cp35-cp35m-manylinux1_x86_64.whl (1.0 MB)
Collecting toposort>=1.0
  Using cached toposort-1.6-py2.py3-none-any.whl (9.5 kB)
Collecting pytz<2021.0
  Downloading pytz-2020.5-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 13.2 MB/s 
Collecting Jinja2
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 10.1 MB/s 
Collecting watchdog>=0.8.3
  Downloading watchdog-0.10.6.tar.gz (99 kB)
     |████████████████████████████████| 99 kB 8.4 MB/s 
Collecting grpcio-health-checking>=1.32.0
  Using cached grpcio-health-checking-1.36.1.tar.gz (10 kB)
Collecting tqdm
  Using cached tqdm-4.59.0-py2.py3-none-any.whl (74 kB)
ERROR: Could not find a version that satisfies the requirement docstring-parser==0.7.1 (from dagster)
ERROR: No matching distribution found for docstring-parser==0.7.1
```

## Reproduction

Installing docstring-parser does not work for me for 0.7.1
```
$ pip install docstring-parser==0.7.1
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement docstring-parser==0.7.1
ERROR: No matching distribution found for docstring-parser==0.7.1
```

Installing 0.7.3 works fine

```
pip install docstring-parser==0.7.3
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting docstring-parser==0.7.3
  Downloading docstring_parser-0.7.3.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: docstring-parser
  Building wheel for docstring-parser (PEP 517) ... done
  Created wheel for docstring-parser: filename=docstring_parser-0.7.3-py3-none-any.whl size=19230 sha256=71ec740900ede234ba8921990c206b0f920d24d094e711f22091639e944bab85
  Stored in directory: /root/.cache/pip/wheels/76/ec/2c/c1194c14f8eb3e9724f0dbaf2c77babd534684f5709122600c
Successfully built docstring-parser
Installing collected packages: docstring-parser
Successfully installed docstring-parser-0.7.3
```

I think this is because the docstring-parser-0.7.1 download files are not there anymore in pypi https://pypi.org/project/docstring-parser/#files

## Additional Info about Your Environment

- This is in a docker container that uses Python version 3.5

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment] 2021-03-11 21:34
@manoharuss the download files are still here: https://pypi.org/project/docstring-parser/0.7.1/#files.

Note that Dagster supports Python 3.6 and above - since you're using 3.5, I will close this issue.

**Closed by rexledesma** 2021-03-11 21:34 UTC
Labels: bug

**Comment by htp84** [comment] 2021-07-12 14:44
## Summary
The docker example at [deploy docker](https://github.com/dagster-io/dagster/tree/0.12.1/examples/deploy_docker) fails and I think it is caused by this error. The example uses python 3.7. Because of pip's dependency resolver dagster 0.9.2 is installed. And in 0.9.2  is dagster-daemon not implemented.

```
380: starting container process caused: exec: "dagster-daemon": executable file not found in $PATH: unknown

ERROR: for docker_example_daemon  Cannot start service docker_example_daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "dagster-daemon": executable file not found in $PATH: unknown
```

## Environment
WSL2 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
Docker version 20.10.7, build f0df350

## Workaround
Install miniconda in the docker container, install docstring_parser via conda and the other requirements via pip with the --no-dependencies and --ignore-installed flags
