### ISSUE TITLE
Use job and repository as part of surrogate key

### ISSUE THREAD

**Issue by nico525** [dagster-io/dagster#6897] opened 2022-03-03 07:36 UTC
## Use Case
I have multiple repositories loaded via gRPC from various code sources - all defined in my workspace.yaml
The repositories are named differently (i.e. app1 and app2) but the jobs in there might be named equally (e.g. job_simple).
The current UI makes it difficult to differentiate between the repositories. Especially, when looking for runs of job_simple in repository1, i can also see the runs of job_simple in repository2 which might be doing something completely different

## Ideas of Implementation
Add the repository into each column where you reference runs or change the jobs names in the UI into {job_name}@{repository_name} to properly distinguish in the UI and run history.

**Comment by rexledesma** [comment] 2022-03-03 07:42
Duplicate of https://github.com/dagster-io/dagster/issues/6725

**Closed by rexledesma** 2022-03-03 07:42 UTC
Labels: feature-request
