### ISSUE TITLE
Dagit: improved handling for multiple repositories containing jobs with the same name

### ISSUE THREAD

**Issue by adam-bloom** [dagster-io/dagster#9445] opened 2022-08-22 18:04 UTC
### Dagster version

1.0.3

### What's the issue?

See discussion in https://dagster.slack.com/archives/C01U954MEER/p1660768492272479, but a few queries in dagit are presumably missing the parameter for the repository, and therefore returning any result for the matching job name instead.
1. Linking from the job launchpad page to both the active/last runs and assets at the top of that page
2. The timeline view for the dagster instance

### What did you expect to happen?

I expect each (repository, job) tuple to be treated independently, and jobs with the same name across repositories should not be aggregated.

### How to reproduce?

Create two repositories, each containing the a job with the same name. Run both jobs (maybe even create a schedule). You'll see some interesting things!

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by nathanskone** [comment] 2022-08-22 21:27
We have seen a similar issue with asset names across jobs and/or workspaces.

**Comment by dpeng817** [comment] 2022-08-25 19:25
Not going to close this issue, since I don't think it completely solves the problem, but I think that https://github.com/dagster-io/dagster/pull/9451 should make some improvements in this area (1.0.5 and up)

**Comment by adam-bloom** [comment] 2022-09-01 22:40
@dpeng817 @hellendag @bengotow FYI, that change actually doesn't work correctly for this use case. I just upgraded and enabled that feature flag, and I'm getting output like the screenshot below (names trimmed off) - you can see its selecting runs not just for that repo, but every repo still.

![image](https://user-images.githubusercontent.com/3771193/188024694-89058cb0-f649-41c7-b033-c98d685b2d9d.png)

**Comment by bengotow** [comment] 2022-09-14 03:07
Hey folks, just a heads up that I've been able to reproduce this with all the latest feature flags turned on. Strangely, it looks like this doesn't happen unless both of your duplicately-named jobs have been run at least once. Will dig in and see if we can get a fix for this out.

**Comment by adam-bloom** [comment] 2022-09-14 16:25
@bengotow should I split out the first part of this issue (assets/run links from individual job pages) into its own issue?

**Comment by bengotow** [comment] 2022-09-14 23:03
Hey @adam-bloom I'm not sure I follow that part - right now, there are asset / run links on the individual job pages in the tags at the top here. (If there are more than 3 assets it displays a modal with the links rather than making individual tags for them all). Does that do the trick?

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/1037212/190277860-d2308b42-db6a-442a-a508-a5902ff8be94.png">
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/1037212/190277895-69d7161f-
db42-4f0d-afa3-5ee3b22f18c1.png">

**Comment by adam-bloom** [comment] 2022-09-14 23:14
@bengotow I think the issue I was seeing there was addressed by a recent change - the issue I was seeing for that behavior in a previous release is no longer present. Apologies for that - I hadn't recheck that behavior since I originally noticed it.

**Comment by bengotow** [comment] 2022-09-14 23:15
Oh awesome! That sounds good - going to go ahead and close this since the https://github.com/dagster-io/dagster/pull/9684 PR has merged and will ship in tomorrow's release 👋

**Closed** 2022-09-14 23:15 UTC
Labels: bug
