### ISSUE TITLE
Dagster nofile leak with multiprocess executor and job with many steps

### ISSUE THREAD

**Issue by paul-savarskyy-simplisafe** [dagster-io/dagster#25132] opened 2024-10-08 15:15 UTC
### What's the issue?

We recently upgraded our Dagster version to 1.8.1 and some of our large pipelines been running into a
```
OSError: [Errno 24] Too many open files
```
We use S3 as our I/O manager and in our pipelines, and we run these specific jobs on [AWS Fargate](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html#fargate-considerations) which specifies:
```
The default nofile and nproc soft limit is 1024 and the hard limit is 65535 for Fargate Pods.
``` 
So somewhere dagster is has a resource leak where it's opening too many files and not closing them. We additional exec'd into these running pods and saw the number of open files was continually increased until the job failed

### What did you expect to happen?

Dagster `1.6.3` didn't run into this issue even with over 500 steps

### How to reproduce?

Run a pipeline with over 500 steps with S3 as the I/O manager

### Dagster version

1.8.1

### Deployment type

Dagster Helm chart

### Deployment details

Running these jobs on EKS Fargate

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by garethbrickman** [comment] 2024-10-18 20:22
Is this when using the [s3_pickle_io_manager](https://docs.dagster.io/deployment/guides/aws#using-s3-for-io-management)?

**Comment by paul-savarskyy-simplisafe** [comment] 2024-10-28 14:20
Hey Gareth, sorry for the late response. Yes we're using the s3_pickle_io_manager

**Comment by zaneselvans** [comment] 2024-11-08 23:38
I have been running into the "Too many open files" repeatedly too, but I'm running Dagster locally on a MacBook Pro, and an IO Manager that writes out Parquet files or pickled pandas dataframes depending on the asset.

**Comment by jamiedemaria** [comment] 2024-11-13 18:14
hi @zaneselvans and @paul-savarskyy-simplisafe  would you be able to provide a full stack trace for the "too many open files" error?

**Comment by zaneselvans** [comment] 2024-11-14 03:52
Here's an example @jamiedemaria. The DAG has ~400 assets in it. This is running on a MacOS 15.1 machine with 10 cores, using postgres for the Dagster event logging database.

```
2024-11-13 21:47:41 -0600 - dagster - DEBUG - etl_full - e72f2380-fa92-4c3a-9f63-a992899c0be0 - 19261 - ENGINE_EVENT - Unexpected exception while steps were still in-progress - terminating running steps:

OSError: [Errno 24] Too many open files

Stack Trace:
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/executor/multiprocess.py", line 256, in execute
    event_or_none = next(step_iter)
                    ^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/executor/multiprocess.py", line 388, in execute_step_out_of_process
    for ret in execute_child_process_command(multiproc_ctx, command):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/executor/child_process_executor.py", line 155, in execute_child_process_command
    process.start()
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.12/multiprocessing/util.py", line 454, in spawnv_passfds
    errpipe_read, errpipe_write = os.pipe()
                                  ^^^^^^^^^
```

**Comment by jamiedemaria** [comment] 2024-11-14 16:55
I was able to reproduce this issue and narrow it down to this commit https://github.com/dagster-io/dagster/pull/22839. 

@gibsondan Based on the PR it seems like this may be a longer-standing issue that we are only now showing because the steps are getting terminated

**Comment by gibsondan** [comment] 2024-11-14 22:16
Thanks for reporting this - we've landed a fix for the resource leak here which will go out in our 1.9.3 release next week.

**Comment by zaneselvans** [comment] 2024-11-14 22:33
Awesome @gibsondan! Thanks for giving it some attention.

**Closed** 2024-12-16 21:31 UTC
Labels: type: bug, area: io-manager
