### ISSUE TITLE
Crash on empty AssetSelection.groups

### ISSUE THREAD

**Issue by C0DK** [dagster-io/dagster#14150] opened 2023-05-08 05:16 UTC
### Dagster version

1.0.16

### What's the issue?

When creating an empty AssetSelection (I did so by mistake) dagster crashes, and does not show which selection was empty, which is annoying if you have multiple. 

```
UserWarning: Error loading repository location kredslob_dagster:TypeError: reduce() of empty iterable with no initial value

[...]

  File "/home/cdk/.local/share/virtualenvs/kredslob-dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/definitions/decorators/repository_decorator.py", line 336, in repository
    return _Repository()(definitions_fn)
  File "/home/cdk/.local/share/virtualenvs/kredslob-dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/definitions/decorators/repository_decorator.py", line 129, in __call__
    else CachingRepositoryData.from_list(
  File "/home/cdk/.local/share/virtualenvs/kredslob-dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/definitions/repository_definition/repository_data.py", line 468, in from_list
    return build_caching_repository_data_from_list(
  File "/home/cdk/.local/share/virtualenvs/kredslob-dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/definitions/repository_definition/repository_data_builder.py", line 218, in build_caching_repository_data_from_list
    resolved_job = unresolved_job_def.resolve(
  File "/home/cdk/.local/share/virtualenvs/kredslob-dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/definitions/unresolved_asset_job_definition.py", line 206, in resolve
    asset_selection=self.selection.resolve(asset_graph),
  File "/home/cdk/.local/share/virtualenvs/kredslob-dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/definitions/asset_selection.py", line 176, in resolve
    return self.resolve_inner(asset_graph)
  File "/home/cdk/.local/share/virtualenvs/kredslob-dagster-XfxY7WKa/lib/python3.10/site-packages/dagster/_core/definitions/asset_selection.py", line 316, in resolve_inner
    reduce(
 ```
 
 I seem more sure that this is a bug, not a feature, as it fails due to the structure of the reduce, not anything before.

### What did you expect to happen?

Ideally, I'd think it would run but the job be empty. Alternatively, it should throw an exception, ie. `group ABC is empty! cannot build job`.

### How to reproduce?

```python
blah = define_asset_job(
        name="failing_job",
        selection=AssetSelection.groups(f"foobar").upstream(),
    )
```

### Deployment type

Local

### Deployment details

N/A

### Additional information

N/A

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by C0DK** [comment] 2023-05-11 04:18
Hmm i'll give an update a go when possible, and see if it fixes it. Thanks!

**Comment by C0DK** [comment] 2023-05-11 04:18
Btw got to be said that i am using repositories, not Definitions (yet)

**Comment by sryza** [comment] 2024-01-05 16:24
Closing this because of @smackesey 's failure to reproduce. Please reopen if you encounter this again!

**Closed by sryza** 2024-01-05 16:24 UTC
Labels: type: bug, type: good first issue
