### ISSUE TITLE
Render URLs as Clickable Links in Run Logs in the UI

### ISSUE THREAD

**Issue by jadenhpark** [dagster-io/dagster#16183] opened 2023-08-29 19:21 UTC
### What's the use case?

In our workflow, we often log URLs, specifically for Databricks runs, within our internal logs. Navigating between Dagster and other platforms, such as Databricks, is a common task. Currently, to access these URLs from the logs, we have to manually select the entire URL with the cursor, which is not only tedious but also time-consuming.

### Ideas of implementation

- Implement a URL detection mechanism within the Run logs viewer in the UI. This can be achieved using regular expressions or other string parsing techniques.
- Clickable Links: Once a URL is detected, render it as a clickable link. Users should be able to click these links, which should open in a new browser tab/window.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment] 2023-08-29 20:03
Duplicate of https://github.com/dagster-io/dagster/issues/15862. Closing to consolidate the issues.

**Closed by rexledesma** 2023-08-29 20:03 UTC
Labels: type: feature-request
