### ISSUE TITLE
Tags option for assets/graph_assets

### ISSUE THREAD

**Issue by domantasm96** [dagster-io/dagster#16440] opened 2023-09-12 07:55 UTC
### Dagster version

1.4.12

### What's the issue?

It is not possible to pass tags for  `@graph_asset` and `@asset` in the code.

However, by using Dagster UI, this functionality is presented:
![image](https://github.com/dagster-io/dagster/assets/16419703/178d8af8-092a-457f-ac22-3e7567ba0d29)

### What did you expect to happen?

Allow pass custom `tags` to assets.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-09-29 22:03
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/8979. Let me know if this is not the case.

**Closed** 2023-10-02 00:01 UTC
Labels: type: bug
