### ISSUE TITLE
[Dagit] Inspect resource config from within pipeline definition view?

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#2893] opened 2020-09-10 17:22 UTC
Not sure if I missed this or there's some obvious reason why this wouldn't work (exposing secrets?) but could be nice to inspect resource config schema from dagit. Also, for resources that are configured at definition-time (ie via configured(...)), it could be nice to see the configured config values in dagit.

Additional context: I am exploring ways to launch new pipeline runs from within a solid via a configured resource. The (often pre-configured) resource config values details the repository name / repository location / pipeline name of the pipeline to be launched and it could be nice to know for users to see those values esp. when trying to explore a pipeline's side effects

https://www.loom.com/share/15005e468e1e42d68809dd47ac7604df

**Comment by schrockn** [comment] 2020-09-10 17:24
This is just pure oversight. Would be good to get it done.

**Comment by catherinewu** [comment] 2020-09-21 21:31
https://github.com/dagster-io/dagster/issues/2736

**Comment by hellendag** [comment] 2022-01-19 21:43
Duplicate of #2736.

**Closed by hellendag** 2022-01-19 21:43 UTC
Labels: good second issue, dagit
