### ISSUE TITLE
Just-computed software-defined assets show up as stale

### ISSUE THREAD

**Issue by Bonnevie** [dagster-io/dagster#11442] opened 2022-12-30 16:30 UTC
### Dagster version

1.1.7

### What's the issue?

When using "materialize all" from the Dagit UI using an asset job, the first assets show up correctly as materialized, but any downstream assets show up as stale (yellow) with a success status.

### What did you expect to happen?

Running a materialization job, I would not expect to see any stale assets as they were computed simultaneously. 
If this is due to a missing setting on my part, I'd expect this behaviour to not be the default.
These are fast DBT assets, so I hope it's not just that they completed in the same minute that is causing this.

### How to reproduce?

I just have a couple of DBT models, with the downstream assets only using SELECT and WHERE clauses.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-01-03 19:52
@Bonnevie are these partitioned assets by any chance?

**Comment by Bonnevie** [comment] 2023-01-06 14:57
Hi @sryza, no they were fairly regular assets. But I haven't experienced it lately, so maybe it got fixed.

**Comment by tha23rd** [comment] 2023-01-06 20:17
I experienced this today, same exact issue/reproducibility. I've run the backfill multiple times and had at least one or more assets still show up as stale.

**Comment by sryza** [comment] 2023-01-06 20:56
Staleness for partitioned assets has never actually worked correctly. In 1.1.8, we included a fix for partitioned assets that never shows them as stale. In a few weeks, we're going to include a change that shows the # of stale / missing / fresh partitions.

**Comment by sryza** [comment] 2023-01-30 17:26
Going to close this because I believe it may have been fixed.  Please reopen if you observe otherwise.

**Closed by sryza** 2023-01-30 17:26 UTC
Labels: bug
