### ISSUE TITLE
Partitioned job backfills do not respect backfill policies of respective assets

### ISSUE THREAD

**Issue by derHeinzer** [dagster-io/dagster#19505] opened 2024-01-31 10:56 UTC
### Dagster version

1.5.13

### What's the issue?

When materializing multiple partitiones of multiple assets via a partitioned asset job the backfill policies of the assets are not being respected. Instead a run for every single partitioned is launched.

### What did you expect to happen?

The materialize all modal of the job indicates that dagster will use varying backfill polices of the assets. 
![image](https://github.com/dagster-io/dagster/assets/43210452/4a13d4e0-1d55-4bda-b2fb-a6d8752cbdf3)
And even the preview indicates, that if the backfill policy of each asset to be materialized is "single_run" only one run per asset is being launched:
![image](https://github.com/dagster-io/dagster/assets/43210452/54aebcbd-8f59-42db-8e35-aebf74ad8c0d)
However this does not seem to be true. Instead a job run for every single partition in the backfill is being launched, which in my case is very inefficient.

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2024-01-31 20:18
Going to close this as a duplicate of https://github.com/dagster-io/dagster/issues/17404

**Closed by sryza** 2024-01-31 20:18 UTC
Labels: type: bug
