### ISSUE TITLE
[dagster-polars] storage_options=None overridden to storage_options={}

### ISSUE THREAD

**Issue by paul-godhouse** [dagster-io/dagster#26312] opened 2024-12-06 12:51 UTC
### What's the issue?

I have Dagster deployed on Kubernetes. I'm using `PolarsParquetIOManager` to read and write parquet files between my different assets. These files are stored on an S3 bucket.

The pods related to the code location and the runs have the right to retrieve files in the S3 bucket. Therefore when I'm connected on a pod, I can launch
```
ldf = pl.scan_parquet("s3://path/to/my/parquet/file")
ldf.collect()
```
and everything is working fine.

However, the IOManager is throwing the following error:
```
polars.exceptions.ComputeError: Generic S3 error: Client error with status 403 Forbidden: No Body
```

After some investigations, it turns out that the IOManager is using the following command (in function `scan_parquet` in `python_modules/libraries/dagster-polars/dagster_polars/io_managers/parquet.py`):
```
ldf = pl.scan_parquet("s3://path/to/my/parquet/file", storage_options={})
...
ldf.collect()
```

`storage_options={}` is overriding the IAM credentials from my pod.

This is problematic because I am instantiating the IOManager this way:
```
PolarsParquetIOManager(
                base_dir=EnvVar("POLARS_PARQUET_IO_MANAGER__S3_BASE_DIR"),
            )
```
So we should have `storage_options == None` since I don't pass any `storage_options`

### What did you expect to happen?

`storage_options` should remain `None` and not an empty dict

### How to reproduce?

Code location:
```
from dagster import (
    Definitions,
)
from dagster_polars import PolarsParquetIOManager

@asset(io_manager_key="polars_parquet_io_manager")
def dummy_polars_writing() -> pl.DataFrame:
    return pl.DataFrame(
        {
            "a": [1, 2, 3],
            "b": [4, 5, 6],
        }
    )


@asset
def dummy_polars_reading(dummy_polars_writing: pl.DataFrame) -> str:
    print(dummy_polars_writing.head())
    return "OK"

defs = Definitions(
    resources={
        "polars_parquet_io_manager": PolarsParquetIOManager(
                base_dir="s3://path/to/directory",
            ),
    },
    assets=[dummy_polars_writing, dummy_polars_reading],
)
```

Ona forked version of dagster, print storage_options in `scan_parquet` function in `python_modules/libraries/dagster-polars/dagster_polars/io_managers/parquet.py`:

```
def scan_parquet(path: "UPath", context: InputContext) -> pl.LazyFrame:
    """Scan a parquet file and return a lazy frame (uses polars native reader).

    :param path:
    :param context:
    :return:
    """
    context_metadata = context.definition_metadata or {}

    storage_options = cast(
        Optional[Dict[str, Any]],
        (
            path.storage_options
            if hasattr(path, "storage_options")
            else None
        ),
    )

    kwargs = dict(
        n_rows=context_metadata.get("n_rows", None),
        cache=context_metadata.get("cache", True),
        parallel=context_metadata.get("parallel", "auto"),
        rechunk=context_metadata.get("rechunk", True),
        low_memory=context_metadata.get("low_memory", False),
        use_statistics=context_metadata.get("use_statistics", True),
        hive_partitioning=context_metadata.get("hive_partitioning", True),
        retries=context_metadata.get("retries", 0),
    )
    if Version(pl.__version__) >= Version("0.20.4"):
        kwargs["row_index_name"] = context_metadata.get("row_index_name", None)
        kwargs["row_index_offset"] = context_metadata.get("row_index_offset", 0)
    else:
        kwargs["row_count_name"] = context_metadata.get("row_count_name", None)
        kwargs["row_count_offset"] = context_metadata.get("row_count_offset", 0)

   #####
    print(f"{storage_options=}")
   #####
    return pl.scan_parquet(str(path), storage_options=storage_options, **kwargs)  # type: ignore

```

### Dagster version

1.9.3

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
By submitting this issue, you agree to follow Dagster's [Code of Conduct](https://github.com/dagster-io/dagster/blob/master/.github/CODE_OF_CONDUCT.md).

**Comment by danielgafni** [comment] 2024-12-09 14:03
This looks like a regression to me, otherwise we would have noticed it long time ago. I don't think I've encountered it before. Probably something has changed in `polars`. @paul-godhouse could you please verify this issue exists with the latest `polars` version? In this case I will submits an issue describing this interaction to `polars`.

**Comment by paul-godhouse** [comment] 2024-12-09 14:12
@danielgafni I was on version 1.14.0. I tried with the latest (1.17.1). Same issue but the message is a bit more detailed:

```
polars.exceptions.ComputeError: The operation lacked the necessary privileges to complete for path ********* Client error with status 403 Forbidden: No Body
```

**Comment by danielgafni** [comment] 2024-12-09 14:19
If it's easy please also try some older versions so we can understand if this wasn't a problem previously (my guess).
Meanwhile I've left a comment on your PR regarding the possible improvement on our side.

**Comment by paul-godhouse** [comment] 2024-12-09 15:36
I tried on previous versions of polars (1.0.0 and 0.19.18). It turns out that in that case, the script fails at 

```
ldf = pl.scan_parquet("s3://path/to/my/parquet/file")
```
(regardless of the `storage_options` variable). It seems that in that case, polars is using the credentials from my node and not from my pod.

So overall, things have changed on polars' side


Regarding the PR, thank you for the comment :)
On my side, I found a workaround: if I set in the env variable `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, everything is working as expected. So I don't know, if we should continue or close the PR.
Wdyt?

**Comment by danielgafni** [comment] 2024-12-09 19:03
> It seems that in that case, polars is using the credentials from my node and not from my pod.

Not entirely sure what do you mean here? In what form are you providing the AWS credentials and how can the "node" credentials be exposed to your pod? Are you explicitly mounting them somehow? 

In general, the best way to provide AWS credentials for Kubernetes pods is to use [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). EKS will automatically set correct environment variables (`AWS_ROLE_ARN`) for you. 

Anyway, you should provide some credentials to the pod. Is it possible that actually no credentials have been provided previously?

**Comment by paul-godhouse** [comment] 2024-12-10 10:36
I'm using the pod identity feature and I'm not mounting the role from the node to the pod.
It's like if the old versions of polars are not understanding this identity and use the role from the node where the pod is running. 
It's a bit weird but if polars is unable to use the pod identity, I'm not extremely surprised that the assumed role fallbacks to the node's role

I guess it's coming from the fact that pod identity is fairly new and was not supported by polars at that time.
Does that makes sense?

> Setting AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY is another alternative (it's less secure since you need to manage a permanent service account and it's keys). Is it possible that actually no credentials have been provided previously?

No, the pod identity has always been set. Otherwise, I wouldn't be able to do a `pl.read_parquet('s3://...')` or `ldf = pl.scan_parquet('s3://...') .... ldf.collect()` on my pod.

I agree with you that it is less secure (and also less handy). To me, it's just a temporary solution until the root problem is fixed on polars' side

**Comment by danielgafni** [comment] 2024-12-10 10:55
Alright, makes sense! 

Feel free to close the issue in this case and open a new one in `polars`. 

P.S. IRSA has been working for me, you might want to try it until pod identity is supported by `polars`

**Closed** 2024-12-11 17:23 UTC
Labels: type: bug
