### ISSUE TITLE
I can't seem to copy paste config from Playground when using the Firefox browser

### ISSUE THREAD

**Issue by zzztimbo** [dagster-io/dagster#2183] opened 2020-02-20 17:35 UTC
Copy/paste works for me when I use:

- Chrome
- Vivaldi
- Safari

But when I'm using Firefox 73.0, I can't copy anything out of the config IDE. I also feel like I've been able to do this in the past.

**Comment by mgasner** [comment] 2020-02-20 18:37
i think #2138 is a dupe of this

**Closed** 2020-02-21 01:54 UTC
