### ISSUE TITLE
Using parameters to define a pipeline  

### ISSUE THREAD

**Issue by AdamDorwart** [dagster-io/dagster#2077] opened 2020-01-22 02:40 UTC
I'm currently evaluating using Dagster. Really love the framework so far. Great work!

I think I've discovered an unsupported use case that's unfortunately a show stopper for me. If I want a pipeline that takes a set of parameters to build the pipeline it doesn't seem possible. Here's a more concrete example of what I would like to do.
```python
# Solids: task(), analyze(), join_metrics()

@pipeline(
    config = {
        'parameters': Field(List)
    }
)
def my_pipeline(context):
    metrics = []
    for parameter in context.config['parameters']:
        artifact = task(parameter)
        metric = analyze(artifact)
        metrics.append(metric)
    join_metrics(metrics)
```

An alternative solution would be if a solid could output a list and the pipeline could iterate over it. Neither of these seem to be supported. The closest thing I can get to this that works right now is:
```python
# Solids: task(), analyze(), join_metrics()
parameters = [1, 2, 3]

@pipeline
def my_pipeline():
    metrics = []
    for parameter in parameters:
        artifact = task(parameter)
        metric = analyze(artifact)
        metrics.append(metric)
    join_metrics(metrics)
```

Which would require wrapping dagster and seems wrong.

I see some existing issues that are related:
Dynamic Pipelines are not supported - https://github.com/dagster-io/dagster/issues/2002
Sequence Type - https://github.com/dagster-io/dagster/issues/462

My questions to the team are:
1. Are you opposed to this feature?
2. If not, is it already in progress or planned on a roadmap?
3. Would you consider a contribution? How big of a change do you expect it to be? Would Dagit break?

I believe these patterns are possible in alternatives like Kubeflow, Metaflow, Flyte, Prefect, etc. I really enjoy how clean and simple Dagster is and there seems to be a pretty clear path to more advanced execution runtimes that the other frameworks have. I would like to adopt and help if possible, but I need to figure out how far out this change is.

**Comment by schrockn** [comment] 2020-01-22 02:52
Hey @AdamDorwart thank you for the kind words and for the thoughtful issue!

So in terms of config at pipeline *construction* time, that is not currently supported. However if you want to dynamically create pipelines you can do so with vanilla python

```
def generate_pipeline(parameters):
    def my_pipeline():
      # same code as your example
    
    return my_pipeline
```

Other, more dynamic constructions are on our roadmap for later in Q1 and Q2. We are currently working on a release 0.7.0 which should be out in Feb 7. We'll assess our next set of objectives after that.

Injecting an additional order of dynamism -- and in particular I am talking about exposing parallelism based on data computed at *runtime* -- will be a large, invasive change with many implications and will have to be implemented by the core team.

It would be helpful to understand your exact use case as well. If "parameters" is a value that can be known before execution begins, then the higher-order function above should suffice. You could also enqueue N runs of a pipeline via the GraphQL API. (We could easily assist you by writing a wrapper script for that or advising you and then accepting a contribution). More complex patterns will likely have to wait until we have more framework support!

Thanks again for the kind words. Feel free to hop in our slack and say hello! Would love to hear more about what you're working on and other feedback.

**Comment by AdamDorwart** [comment] 2020-01-22 04:19
Thank you for the quick response!

In my example "parameters" would be known before execution begins, but ideally the user could start the run with GraphQL or Dagit. Different users would have different parameter values.

Pipeline generation could work or at least be a stop gap. Ideally the pipeline definition is "fixed" (Like a built container or pypi package), and then another consumer could use it by providing parameters. So providing the generator to consumers in your example works, but (I think) wouldn't allow someone that only has access to Dagit or Graphql to parameterize the pipeline. This could be an acceptable interface for now.

For your suggestion to use GraphQL to enqueue N runs the issue then is having the `join_metrics` solid in my example to combine the outputs of each pipeline. I'm guessing I could separate this solid out into another pipeline that would consume the N outputs as resources (?), and I would need to listen to pipeline events to trigger this `join_metrics_pipeline`. Do you have a better idea how to go about this route using just GraphQL?

I'm trying to imagine a persistent deployment of Dagit where different users want to parameterize this pipeline differently without redeployment.

**Comment by schrockn** [comment] 2020-01-22 14:21
For generated pipelines, you can join N outputs of type T to a single input with type List[T].

The join in the yet-to-be-supported dynamic execution path is going to be the difficult part of this for sure. Our general position so far is that if one is doing these map reduce computations, one should be delegating the actual compute to a framework designed for distributed computation like Spark, Ray, pywren, Dask, or similar, leaving Dagster purely as an orchestration layer. However this certainly seems to be a common request so we may end up supporting it in some way. I would like to come up with some grand unifying theory of what should reside in orchestration versus compute before we do it. :-)

**Comment by mgasner** [comment] 2020-01-23 21:05
#462

**Comment by catherinewu** [comment] 2021-03-03 03:35
Closing; duplicate of https://github.com/dagster-io/dagster/issues/462

**Closed by catherinewu** 2021-03-03 03:35 UTC
Labels: core
