### ISSUE TITLE
Tag values should be allowed if they are serializable

### ISSUE THREAD

**Issue by rexledesma** [dagster-io/dagster#3921] opened 2021-03-22 17:41 UTC
## Summary
We should allow tag values that are json serializable. Some tag arguments are marked as `(Optional[Dict[str, str]])` when they should be `(Optional[Dict[str, Any]])` with a serialization check.

See https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/core/definitions/decorators/schedule.py#L53:9

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by yuhan** [comment] 2021-04-13 20:50
@rexledesma what's the use case of having serializable json in tag values? can you put a serialized json string in the value instead? imo it's safe to only allow str in the values as opposed to allow Any

**Comment by yuhan** [comment] 2021-05-14 05:28
bumping cc @rexledesma ^ wanted to make sure if there's any reasonable use case for us to ever loose this constraint. If not, we will likely close this issue as a "won't do"

**Comment by alangenfeld** [comment] 2021-05-17 15:47
> what's the use case of having serializable json in tag values? can you put a serialized json string in the value instead? imo it's safe to only allow str in the values as opposed to allow Any

I think its convenient - especially when defining tags in python directly - to just be able to use `dict`, `list` & scalars directly.

To be clear this is functionality we already support with this validation method 
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/definitions/utils.py#L80-L108

So I believe the issue is mostly about being consistent since we are not consistent with when the APIs allow/disallow this

**Comment by sryza** [comment] 2021-05-17 22:20
One thing this makes me think of: in InputDefinition and OutputDefinition, we went with `metadata` because we wanted to support deep nested structure.  If tags support this kind of structure, maybe we should call those tags as well?

**Closed** 2024-03-20 18:02 UTC
