### ISSUE TITLE
Partition UI resets status of OPs upon step subset backfill

### ISSUE THREAD

**Issue by yeachan153** [dagster-io/dagster#10294] opened 2022-11-01 16:33 UTC
### Dagster version

1.0.12

### What's the issue?

Backfills that are launched with a step-subset for a specific partition in a partitioned job run successfully, but the corresponding UI appears to reset the status of the OPs that were not part of the step selection. Only the OP that was selected turns green. The partition itself still shows as successful:

![image](https://user-images.githubusercontent.com/30076090/199285492-83b84ce3-a78b-4a98-8be5-de540d37dc98.png)

### What did you expect to happen?

Each row (OP) that did not run as part of the step-subset partitioned backfill should remain green.

### How to reproduce?

1. Create a partitioned job
2. Run a partition to success
3. Click launch backfill to backfill the successful partition. In the step subset section, add an OP to re-run.

### Deployment type

Other Docker-based deployment

### Deployment details

Running 1.22.12-gke.2300.

Deployments of:
- Dagit
- Daemon
- Repository

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment] 2022-11-04 17:14
Thanks for the report-- cc @bengotow @hellendag

**Comment by sryza** [comment] 2022-11-07 18:53
I think this may be a duplicate of https://github.com/dagster-io/dagster/issues/10159.

**Comment by yeachan153** [comment] 2022-11-08 11:23
@sryza indeed could be related, difference is that in this case the different steps are normal OPs within a Job, whereas #10159 involves assets tied together as a job. 

I thought this was a bug based on https://dagster.slack.com/archives/C02LJ7G0LAZ/p1666790936482669?thread_ts=1655223028.397569&cid=C02LJ7G0LAZ and https://dagster.slack.com/archives/C01U954MEER/p1666797289064099

Happy to close this and discuss there if you think it's a duplicate?

**Comment by sryza** [comment] 2022-11-08 16:03
@prha is this the intended behavior?

**Comment by prha** [comment] 2022-11-08 17:15
I'm not sure if "intended" is the right word here, but this UI was designed to communicate the step status of the last run.  We used to have a tiered history, where we would show little historical triangles to indicate what the historical status was in the past (to distinguish from the last run's status).  But it was kind of a confusing UI and it took a really long time for the page to load.
 
In order to display the composite step status, we'd need to potentially fetch every step status for every run for all time.  This is prohibitively expensive unless we start writing some partition summary state on run completion.

We could potentially patch this by loading the last N runs (for some arbitrary N) instead of the last 1 run and then come up with some composite UI for this (cc @braunjj)

**Comment by yeachan153** [comment] 2022-11-09 08:11
Thanks @prha, that's clear.

For our use case, it'd be useful to still have this. For example, we have ETL jobs that have individual OPs for the extract, transformation and loading process. If the loading OP fails, we'd like to selectively re-run this OP (we haven't put a blanket retry because we don't have a way of distinguishing from genuine errors that need to be addressed and ad-hoc infrastructure related errors) and see that all the OPs for the ETL succeeded. If the other OPs now reset their status, it's a bit unclear why/how that happened.

Also, with the understanding that the partition UI is run based, it still feels slightly strange that the top partition circle is green after running just one OP, since this is a UI for the partitioned job/asset, not a specific OP. I would probably have expected the top partition circle to only be green if all the OPs in that partitioned job succeeded.

> In order to display the composite step status, we'd need to potentially fetch every step status for every run for all time. This is prohibitively expensive unless we start writing some partition summary state on run completion.

Yes, we ran into issues where the partition view was very slow the more partitions there were: https://github.com/dagster-io/dagster/issues/10330. Might indeed benefit from some optimisations.

**Comment by prha** [comment] 2022-11-11 16:49
Just did more code spelunking... We actually are fetching more data than I realized before.  We should be able to display some past state that would communicate that a step was previously successful.  Stay tuned - should be able to get somthing in for next week's release.

**Comment by simonvanderveldt** [comment] 2022-11-14 14:50
> Also, with the understanding that the partition UI is run based, it still feels slightly strange that the top partition circle is green after running just one OP, since this is a UI for the partitioned job/asset, not a specific OP. I would probably have expected the top partition circle to only be green if all the OPs in that partitioned job succeeded.

I guess this would depend on which information this overview is supposed to communicate?
- If it's the status of the latest Run for the partition and only a subset of Ops were included in this Run then I can imagine it would only aggregate over the Ops that were included in the latest run. And only the status of the Ops that were included in the latest run should be shown when showing the per-step status.
- If it's the status of the Partition then it should be an aggregate of all Ops, including ones that weren't included in the latest run. And the status for all Ops, including ones that weren't included in the latest run, should be shown when showing the per-step status.

Also if there were a similar overview with per partition and per-step/Op status for Assets it would make this question regarding Runs for Jobs pretty much irrelevant for us since the Assets are the entities we actually care about. But this would obviously need similar choices/decisions to be made.

**Comment by prha** [comment] 2022-11-14 17:02
I just landed https://github.com/dagster-io/dagster/pull/10478, which should communicate with green vs red color what the aggregate state is (the last non-missing state).  The bright green / bright red state should indicate what the last run contained, to indicate that the last run for the partition had a partial selection.

**Comment by simonvanderveldt** [comment] 2022-11-15 08:31
@prha So the green dot at the top is only showing the aggregate status of the last Run?

**Comment by simonvanderveldt** [comment] 2022-11-15 18:50
@prha OK, clear, thanks for the clarification.

**Comment by prha** [comment] 2022-11-18 19:22
This should now be out as part of `1.1.1`

**Closed by prha** 2022-11-18 19:22 UTC
Labels: bug, backfills, dagit

**Comment by yeachan153** [comment] 2022-11-18 20:46
Thank you @prha!
