### ISSUE TITLE
unified watchdog

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#2095] opened 2020-01-28 22:00 UTC
In the compute log manager we have some machinery to keep tabs on subprocesses and ensure things are killed in unexpected exit conditions. Evaluate if it makes sense to build a better abstraction around doing this in one place so that we don't have divergent implementations of effectively the same idea.

**Comment by mgasner** [comment] 2020-05-27 21:21
going to close this as a duplicate of #1906

**Closed by mgasner** 2020-05-27 21:21 UTC
Labels: core
