### ISSUE TITLE
typing.Union type annotation results in DagsterInvalidDefinitionError

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#6994] opened 2022-03-09 18:42 UTC
Repro from https://dagster.slack.com/archives/C01U954MEER/p1646846296586009:
```python
import random
from dagster import job, op
from typing import Union


@op
def foo() -> Union[str, int]:  # fails here
    return random.choice([1, "one"])


@job
def bar():
    foo()

```

**Comment by sryza** [comment] 2022-03-11 16:19
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/5115.

**Closed by sryza** 2022-03-11 16:19 UTC
Labels: bug
