### ISSUE TITLE
overview's path collision

### ISSUE THREAD

**Issue by WHYTEWYLL** [dagster-io/dagster#11650] opened 2023-01-11 22:45 UTC
### Dagster version

dagster --1.1.7

### What's the issue?

If you define an asset with the name 'overview,.' You are sent to an empty window when you click the asset in the UI. 

### What did you expect to happen?

As overview is a subpath in some places, so that might be the issue here. 

### How to reproduce?

Create an asset name 'overview' and click it.

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-01-12 00:43
I added this to the Dagit project, so the frontend team will take a look at this in their next round of prioritization.

**Comment by sryza** [comment] 2023-01-12 00:43
Thanks for discovering and reporting it!

**Comment by hellendag** [comment] 2023-01-17 22:08
Unfortunately I'm not able to reproduce this at all. I checked out 1.1.7 to try it there, and I can't find any way to get to this error state with an asset named "overview".

- Can you try this again in the latest version?
- If you're still able to reproduce it, which asset graph UI are you viewing when you click it? Can you provide the exact URL path that you see when you're looking at that graph?

**Comment by WHYTEWYLL** [comment] 2023-01-19 19:20
https://dagster.slack.com/archives/C01U5LFUZJS/p1673459387561249?thread_ts=1673445962.763689&cid=C01U5LFUZJS

Here is the threat, I recreated it using 1.1.7

**Comment by hellendag** [comment] 2023-04-18 20:03
Does this still break for you in more recent versions?

**Comment by hellendag** [comment] 2023-05-18 15:55
Closing this because we weren't able to repro in more recent versions. Please feel free to reopen if you're still seeing this issue on the latest version.

**Closed by hellendag** 2023-05-18 15:55 UTC
Labels: bug
