### ISSUE TITLE
Enable filtering on `target asset` in the runs page

### ISSUE THREAD

**Issue by ion-elgreco** [dagster-io/dagster#21212] opened 2024-04-15 09:42 UTC
### What's the use case?

I want to see all runs that targeted specific assets. Currently we cant filter on a target asset yet.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by garethbrickman** [comment] 2024-11-19 16:29
Closing as duplicate of older issue: https://github.com/dagster-io/dagster/issues/17245

**Closed by garethbrickman** 2024-11-19 16:29 UTC
Labels: type: feature-request, area: UI/UX
