### ISSUE TITLE
observable_source_asset should not require materialization to update DataVersion

### ISSUE THREAD

**Issue by nmajumdar** [dagster-io/dagster#16647] opened 2023-09-20 12:04 UTC
### Dagster version

dagster, version 1.4.13

### What's the issue?

When creating an `observable_source_asset` that outputs a `DataVersion`, Dagster processes the output like a materialization using an IO manager. I want to be able to report an observation of a source asset without Dagster trying to write the output using IO manager
 
 See [Slack thread](https://dagster.slack.com/archives/C01U954MEER/p1695155711103019)

### What did you expect to happen?

Returning a DataVersion on an `observable_source_asset`, and maybe even normal assets, should just update the data version without that DataVersion being handled as an output to handle with an IO manager

### How to reproduce?

Using this `definitions.py`:
 
 ```python
 import random
 from dagster import (
     Definitions,
     DataVersion,
     OpExecutionContext,
     observable_source_asset,
 )
 
 
 @observable_source_asset
 def source_asset(context: OpExecutionContext) -> None:
     context.log.info("askjdaljkd")
     return DataVersion(str(random.randint(0, 1)))
 
 
 # Definitions
 defs = Definitions(
     assets=[source_asset]
 )
 ```
 
 Run an observation in the UI, and the default IO manager will write the DataVersion output.

### Deployment type

Docker Compose

### Deployment details

Testing on a Docker Compose file, though this happens in the production use case on Helm as well

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-09-21 12:33
I agree. I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/16234, which I'm currently working on a fix for: https://github.com/dagster-io/dagster/pull/16294.

**Closed** 2023-09-21 12:33 UTC
Labels: type: bug
