### ISSUE TITLE
Converting a schedule to a sensor (same name) doesn't work

### ISSUE THREAD

**Issue by adam-bloom** [dagster-io/dagster#11053] opened 2022-12-12 21:56 UTC
### Dagster version

1.0.15

### What's the issue?

The schedule job/instigator are not converted to sensors.

Sensor displays as enabled in dagit. In dagster-daemon logs, you'll see the following:
```[dagster-daemon-559fb67f7f-4rhv8 dagster] 2022-10-19 22:04:52 +0000 - dagster.daemon.SchedulerDaemon - WARNING - Could not find schedule <schedule/sensor name> in repository <repo>. If this schedule no longer exists, you can turn it off in the Dagit UI from the Status tab.```

Of course, this schedule doesn't exist (it shows as a sensor in dagit), so the error isn't intuitive

### What did you expect to happen?

Sensor runs successfully, old schedule removed correctly.

### How to reproduce?

Create a schedule and start dagster with the schedule enabled. Then, convert the schedule to a sensor of the same name. The sensor will show enabled, but no runs will be triggered. You should see a log similar to the one above.

### Deployment type

Dagster Helm chart

### Additional information

There is a workaround, although it requires some database manipulation. If you delete the schedule from the `jobs` and `instigators` tables, the sensor will create correctly.

First, confirm that you'll be deleting the correct instigator with this query:
```
select * from instigators i where instigator_body like '%<sensor/schedule name>%' and instigator_type ='SCHEDULE';
```
If that returns your enabled (and problematic) schedule...and ONLY that schedule, then you can delete it:
```
delete from instigators i where instigator_body like '%<sensor/schedule name>%' and instigator_type ='SCHEDULE';
```

Now, in dagit, your sensor will show as disabled. Try to enable it (expect failure). You should get an exception about a duplicate job already existing. Right at the top of that exception (sorry, no example handy while I'm writing this up), you'll get a job origin ID. We just need to delete that.
```
delete from jobs where job_origin_id = '<job origin id from exception>';
```

Now, you can enable the sensor in dagit, it will enable correctly, and you should see it being triggered.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by adam-bloom** [comment] 2022-12-12 21:58
Similar to:
#7349, #7018

**Comment by rexledesma** [comment] 2023-12-20 15:43
Duplicate of https://github.com/dagster-io/dagster/issues/7018, closing to consolidate.

**Closed by rexledesma** 2023-12-20 15:43 UTC
Labels: type: bug
