### ISSUE TITLE
Installation of dagit in clean virtual environment yields 'ImportError: cannot import name 'SubscriptionObserver' from 'graphql_ws.gevent'' when running

### ISSUE THREAD

**Issue by Josipmrden** [dagster-io/dagster#4631] opened 2021-08-25 16:08 UTC
## Summary
After installing dagit on my local machine with a clean virtualenv, I got the error below:
```
Traceback (most recent call last):
  File ".../.venv/bin/dagit", line 5, in <module>
    from dagit.cli import main
  File ".../.venv/lib/python3.8/site-packages/dagit/cli.py", line 22, in <module>
    from .app import create_app_from_workspace_process_context
  File ".../.venv/lib/python3.8/site-packages/dagit/app.py", line 23, in <module>
    from .subscription_server import DagsterSubscriptionServer
  File ".../.venv/lib/python3.8/site-packages/dagit/subscription_server.py", line 4, in <module>
    from graphql_ws.gevent import GeventSubscriptionServer, SubscriptionObserver
ImportError: cannot import name 'SubscriptionObserver' from 'graphql_ws.gevent' (.../.venv/lib/python3.8/site-packages/graphql_ws/gevent.py)
```

It seems like `graphql-ws` was recently bumping versions to 0.4.4 which doesn't include `SubscriptionObserver` anymore. 
After downgrading graphql-ws to 0.3.1 it worked fine.

## Reproduction
Run these commands in sequence
```
python3 -m venv .venv
source .venv/bin/activate
pip3 install dagit
dagit
```

## Additional Info about Your Environment
OS: Ubuntu 20.04 LTS
Python Version: 3.8.10

**Comment by jmatak** [comment] 2021-08-25 16:09
I am experiencing the same issue as here. Seems like the dependency should be frozen to some stable `graphql-ws` version.

**Comment by alangenfeld** [comment] 2021-08-25 16:11
dupe of
https://github.com/dagster-io/dagster/issues/4628
where a workaround is described and status of the fix is commented

**Closed by alangenfeld** 2021-08-25 16:11 UTC
Labels: bug
