### ISSUE TITLE
Minutely schedules render poorly

### ISSUE THREAD

**Issue by johannkm** [dagster-io/dagster#3754] opened 2021-03-02 03:52 UTC
![image](https://user-images.githubusercontent.com/22018973/109594426-c3224c80-7ae0-11eb-82a7-2df993f3ceb9.png)

`7 days` is too zoomed out, and it's hard to scroll the view to actually see the ticks

**Comment by hellendag** [comment] 2021-03-02 21:30
Duplicate of #3729.

**Closed by hellendag** 2021-03-02 21:30 UTC
Labels: bug, dagit
