### ISSUE TITLE
Make op retry policies still work when the op process crashes

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#16168] opened 2023-08-29 14:07 UTC
### What's the use case?

Op retries are useful for retrying when an exception happens: https://docs.dagster.io/concepts/ops-jobs-graphs/op-retries#op-retries

But since they are managed within the op process, when that process crashes, they don't trigger. The request here is to ensure that the run worker that is controlling the op process considers the op retry policy and restarts the op process.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by alangenfeld** [comment] 2023-08-29 14:39
related:
https://github.com/dagster-io/dagster/issues/11221
https://github.com/dagster-io/dagster/issues/15026

the crux of the issue is adding support to the various executors to apply retry policies in the exceptional conditions like process crash that are currently just marked as failure

**Comment by zaneselvans** [comment] 2024-04-06 19:59
Also experiencing this problem randomly due to transient spikes in memory usage when several high memory assets happen to materialize simultaneously. Would be great to be able to retry instead of ultimately failing the whole run!

**Closed** 2024-09-16 22:29 UTC
Labels: type: feature-request, area: execution
