### ISSUE TITLE
Loop pipeline use case

### ISSUE THREAD

**Issue by lucavignali** [dagster-io/dagster#2078] opened 2020-01-22 11:17 UTC
Hello,

I have the following use case:

I need to read all TimeSeries (TS) from a DB and perform calculation over all TimeSeries. I can't load all TimeSeries at once, but I have to **loop over ALL TimeSeries** with a pipeline like this: 

Read 1 TS -> Calculate statistics over 1 TS -> Calculate Thresholds for alarms -> Save on target DB 

This pipeline must be looped over ALL TimeSeries.

I tried to setup a DAGSTER pipeline (see example below), just to figure out how to implement such **loop** in DAGSTER.
The pipeline is not working with the following error: 
_dagster.core.errors.DagsterInvariantViolationError: Attempted to iterate over an InvokedSolidOutputHandle. This object represents the output "result" from the solid "generate_tuple". Consider yielding multiple Outputs if you seek to pass different parts of this output to different solids._

How can I implement such loop use case in DAGSTER? 

Thanks!
Luca

**EXAMPLE**
@solid
def generate_tuple(context):
    out = (1,2,3,4,5,6,7,8,9)
    return(out)

@solid
def divide_by2(context,num):
    out = num/2
    return(out)

-# The idea is to loop the divide_by2 @solid on the elements generated by the generate_tuple @solid
-# USE CASE: the generate_tuple @solid provides "vec" a list of timeseries identifier in a TS database
-# the divide_by2 @solid read one single TS, index "i" from "vec" and compute some stat on it.
-# the loop_pipeline simply loop over all TS in the "vec" list.
@pipeline
def loop_pipeline():
    vec = generate_tuple()
    for i in vec:
        divide_by2(i)

**Comment by schrockn** [comment] 2020-01-22 14:24
The code in `@pipeline` is run at pipeline construction time, not at execution time, so `loop_pipeline` does not have access to the output of generate tuple.

One could do:

```
def loop_pipeline():
   vec = (1, 2, 3, 4, 5)
   for i in vec:
      create_some_solid(i)
```

However in the current system one cannot take the output of a solid and then dynamically generate downstream solids from that.

**Comment by lucavignali** [comment] 2020-01-23 13:31
Thanks for the answer.
Hope something to manage loops among @solids will come in future releases.
Anyway thanks for creating DAGSTER I appreciate it, easy and fast to deploy and use.
Luca

**Comment by mgasner** [comment] 2020-01-23 21:05
#462

**Comment by catherinewu** [comment] 2021-03-03 03:36
closing; duplicate of https://github.com/dagster-io/dagster/issues/462

**Closed by catherinewu** 2021-03-03 03:36 UTC
Labels: core, project
