### ISSUE TITLE
Executor config doesn't seem to take affect with a config mapping

### ISSUE THREAD

**Issue by steffyd** [dagster-io/dagster#15061] opened 2023-06-30 17:39 UTC
### Dagster version

1.3.10

### What's the issue?

When trying to specify the multiprocess executor max_concurrency inside of a config_mapping, it doesn't seem to take affect. Our code specified a max_concurrency of 1, but any jobs spawned from it would still process the fanned-out op at a much higher concurrency.

### Deployment type

Docker Compose

### Additional information

Slack thread here: https://dagster.slack.com/archives/C01U954MEER/p1687990338815749

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by smackesey** [comment] 2023-06-30 21:16
Thanks for reporting, I'll take a look.

**Comment by smackesey** [comment] 2023-07-01 18:47
So whatever the issue is with `max_concurrent` and your setup, it doesn't appear to be related to using a config mapping. I just tried varying the config in this example and it works:

```
from time import sleep
from typing import List

from dagster import config_mapping, job, op
from dagster._core.definitions.events import DynamicOutput
from dagster._core.definitions.output import DynamicOut


@op
def my_op():
    sleep(1)
    return 1


@op(out=DynamicOut())
def foo():
    for idx in range(4):
        yield DynamicOutput(idx, mapping_key=str(idx))


@op
def bar(x: int):
    sleep(1)
    return x


@op
def baz(x: List[int]):
    return sum(x)


@config_mapping(config_schema={"max_concurrent": int})
def job_config(val):
    return {"execution": {"config": {"multiprocess": {"max_concurrent": val["max_concurrent"]}}}}


@job(config=job_config)
def my_job():
    parts = foo()
    parts_2 = parts.map(bar)
    baz(parts_2.collect())
```

I'm going to close the issue and we can continue in the slack thread if there's still a problem.

**Closed** 2023-07-01 18:47 UTC
Labels: bug
