### ISSUE TITLE
Dagit Schedules Label getting cut off

### ISSUE THREAD

**Issue by asingh16** [dagster-io/dagster#2090] opened 2020-01-28 03:04 UTC
See cell 3, Almost mistook it for 2 instead of 27 (which is todays date). We ought to either add more padding or make it a bit more responsive. 

<img width="1574" alt="Screen Shot 2020-01-27 at 7 01 40 PM" src="https://user-images.githubusercontent.com/4219809/73232288-96f70800-4137-11ea-8ae6-32e7d43af7a4.png">

**Comment by helloworld** [comment] 2020-01-28 09:20
Duplicate of https://github.com/dagster-io/dagster/issues/2008

**Closed by helloworld** 2020-01-28 09:20 UTC
Labels: dagit
