### ISSUE TITLE
No way to cancel/delete in progress and requested backfills

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#12334] opened 2023-02-14 21:08 UTC
Requested in [slack](https://dagster.slack.com/archives/C01U5LFUZJS/p1676390707265019)

There is currently no way to cancel a backfill from the UI.

**Comment by hellendag** [comment] 2023-02-21 21:09
This might be specific to these being asset backfills, and some limitation on cancelability as defined in Python.

**Comment by sryza** [comment] 2023-03-01 21:58
Closing this as a duplicate of https://github.com/dagster-io/dagster/issues/11530

**Closed** 2023-03-01 21:58 UTC
Labels: dagit
