### ISSUE TITLE
Asset Plot Chart Datapoints not connected

### ISSUE THREAD

**Issue by davidz-1** [dagster-io/dagster#5045] opened 2021-10-06 16:33 UTC
## Summary
When writing datapoints from a dynamic DAG to the same asset, the datapoints in the chart are not connected. Note that each dynamic solid feeds it's own `EventMetadataEntry` within that asset, which label is constructed from the dynamic output mapping key of the creating dynamic solid.

I'm not a 100% sure if it's a bug oder the bug sits in front of the computer while using the feature wrong. 

## Dagit UI/UX Issue Screenshots
I've removed the mapping key/  `EventMetadataEntry` label from the screenshot since it contains sensitive data.

![lines_missing_chart](https://user-images.githubusercontent.com/26926902/136245707-ab5ec288-eb80-4377-803f-e84681965071.PNG)

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment] 2021-11-04 17:40
Hey! This is definitely worth some investigation on our side. I think that for this rendering to happen, the data feed for the graph must include null datapoints in between the numeric datapoints. I'm not sure offhand how that could have happened though.

**Comment by hellendag** [comment] 2021-11-16 21:22
@sryza Any ideas how we might be able to reproduce a situation like this?

**Comment by sryza** [comment] 2021-11-17 15:28
Alas, I have no idea

**Comment by bengotow** [comment] 2022-03-01 22:55
Hey folks! I'm going to go ahead and close this since we don't have steps to reproduce.

I think there are a couple of things that could have been happening here. Broadly speaking, it's ok for materialization metadata to be provided "sparsely" (only half the time, etc), and Dagit will not show gaps in the charts. I think that in this case, the value might have been present-but-empty (null, undefined, "", false maybe?).

**Closed by bengotow** 2022-03-01 22:55 UTC
Labels: bug, flow:monitor-system, page:asset-materialization, dagit
