### ISSUE TITLE
MultiPartitioning Asset not working on Windows  

### ISSUE THREAD

**Issue by mananpmutinex** [dagster-io/dagster#12236] opened 2023-02-09 23:28 UTC
### Dagster version

1.1.17

### What's the issue?

If an Asset has a MultiPartitionsDefinition, the materialization fails on Windows. 

This seems to be due to the '|' used by dagster for multipartition keys is invalid in Windows file paths.

### What did you expect to happen?

The asset should materialize successfully. 

### How to reproduce?

`from dagster import Definitions, asset, MultiPartitionsDefinition, StaticPartitionsDefinition

# Asset for external tables
@asset( 
    partitions_def=MultiPartitionsDefinition({
        "customer_code": StaticPartitionsDefinition(['abc','youi']),
        "datasource_name": StaticPartitionsDefinition(['tv','search']),
    })
)
def external_table(context):
    parition_keys = context.log.info(context.partition_key.keys_by_dimension)
    return_val = f"materialized external table for {parition_keys=}"
    context.log.info(return_val)
    return return_val

defs = Definitions(
    assets= [external_table]
)`

Trying to Materialize the 'abc|tv' partition for this asset through the UI will cause a failure. 

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-02-09 23:31
@clairelin135 heads up I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/11865

**Comment by pdavidsonFIA** [comment] 2023-02-17 11:37
multi partition runs fine on my windows pc (as well as my team) -> but we're using a custom IOManager so maybe it is due to the default fs io manager

**Closed** 2023-03-01 16:38 UTC
Labels: bug
