### ISSUE TITLE
Explore adding a union type

### ISSUE THREAD

**Issue by alangenfeld** [dagster-io/dagster#1697] opened 2019-08-28 17:55 UTC
I think this could leverage a lot of the same stuff the other wrapper types like `List` and `Optional` do.

Example from user:
```
from type import Union



### The reason why I'd like to have something like this is that I want to acts a combiner function that accepts both types of 
### values. I don't want to have to attach config parameters to descriminate the input and output type but it may the direction that I would need to go?
@solid(
    input_defs=[InputDefinition('provider_partials', List[Union[ProviderDataFrame, ProviderSeries]])],
    output_defs=[OutputDefinition(ProviderPartialDataFrame)],
)
def merge_provider_partials(context, provider_partials):
    context.log.info('Merging provider partials to providers')
    partial = pd.concat(provider_partials, axis=1)
    return partial
```

**Comment by mgasner** [comment] 2019-10-08 22:37
closing #1718 as a dupe of this

**Comment by mgasner** [comment] 2019-10-08 22:38
See comment on #1718 for implementation notes

**Comment by natekupp** [comment] 2020-06-01 23:12
@mgasner anything else to do here?

**Comment by kinghuang** [comment] 2020-06-28 03:08
I'm also interested in a Union type. For example, I'm trying to create a field that can take in either a string or a list of strings, which will be fed into the `path` argument of [dask.dataframe.read_parquet](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_parquet). I can't find a way to define a field like this in Dagster.

**Example:**

```
Field(Union[str, List[str]], is_required=True, description="Path to read from.")
```

**Comment by schrockn** [comment] 2020-06-28 13:02
We do support unions in the config system. see ScalarUnion

Sent via Superhuman iOS ( https://sprh.mn/?vip=schrockn@elementl.com )

**Comment by kinghuang** [comment] 2020-06-28 14:34
@schrockn Where can I learn about ScalarUnion? I can't find anything about it on the [docs site](https://docs.dagster.io).

**Comment by natekupp** [comment] 2020-11-09 22:18
For runtime types, we now have unions via PythonObjectDagsterType. Also looks like ScalarUnion is documented now, but @kinghuang please let us know if you need more info there

**Closed by natekupp** 2020-11-09 22:18 UTC
Labels: core
