### ISSUE TITLE
import error in IOManager docs

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3573] opened 2021-01-22 05:46 UTC
## Summary

<img width="896" alt="Screen Shot 2021-01-21 at 9 40 39 PM" src="https://user-images.githubusercontent.com/6024687/105451465-74f07280-5c31-11eb-99ec-18f0b4b15277.png">

https://docs.dagster.io/overview/io-managers/io-managers

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment] 2021-01-22 18:26
I suspect the cause of this is that azure and snowflake have a dependency conflict, so, in dev setups, we avoid installing both of them at the same time.  We typically install snowflake, not azure.  Presumably, wherever these docs were built, this was the case.

This is reflected in the fact that https://docs.dagster.io/_apidocs/libraries/dagster_azure is empty.

@yuhan or @helloworld - do you have thoughts on what the right approach is here?

**Comment by yuhan** [comment] 2021-01-22 22:24
yes, @sryza you are right. i think the solution is when deploying the docs site, the env should have installed all the packages listed in the api docs. i manually fixed it for 0.10.0 by pip install dagster-azure locally when i was the one deploying, but this isn't scalable. will figure out a way to address it soon

**Comment by yuhan** [comment] 2021-02-02 06:21
this should be resolved by https://dagster.phacility.com/D6246 because the docs build process will have its own requirements

**Closed by yuhan** 2021-02-02 06:21 UTC
Labels: IO manager, bug, docs:content-overview, good first issue
