### ISSUE TITLE
dagster core: undeclared runtime dependency to setuptools

### ISSUE THREAD

**Issue by rafalkrupinski** [dagster-io/dagster#6155] opened 2022-01-08 20:44 UTC
## Summary
I have a simple client app that uses dagster-graphql. graphql client depends on core dagster witch at runtime attempts to import pkg_resources, a package from setuptools, which is not declared as a dependency and might be not installed.

## Reproduction
1. create a project with poetry (or any way not involving setuptools)
2. add dependency to dagster-graphql
3. in __main__ call client.submit_job_execution
4. run dagster
5. run the client app

## Additional Info about Your Environment
Poetry 1.1.12
dagster 0.13.13

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by rexledesma** [comment] 2022-04-29 20:40
Duplicate of https://github.com/dagster-io/dagster/issues/7396

**Closed by rexledesma** 2022-04-29 20:40 UTC
Labels: bug
