### ISSUE TITLE
Asset job for partitioned upstream asset graph fails

### ISSUE THREAD

**Issue by memignone** [dagster-io/dagster#18155] opened 2023-11-20 16:56 UTC
### Dagster version

dagster, version 1.5.9

### What's the issue?

I created an asset_job for an asset and its upstream dependency (both partitioned daily) that are mapped with a TimeWindow partition_mapping from day X on one asset to be mapped to days [X-1, X, X+1] on the upstream asset
When running the job, the TimeWindow partition mapping is not taken into consideration, causing the materialization of the main asset to fail

### What did you expect to happen?

Since the job was created from the asset_2, I would expect for the job to use the date partition mappings to materialize first the asset_2 upstream dependencies on the correct partitions and then to materialize the asset_2 on the input date partition

### How to reproduce?

```python
from dagster import Definitions, asset, DailyPartitionsDefinition, AssetIn, TimeWindowPartitionMapping, define_asset_job

partition_def = DailyPartitionsDefinition(start_date="2023-10-01")
@asset(partitions_def=partition_def)
def asset_1():
    return {}

@asset(partitions_def=partition_def, ins={
    "asset_1_list": AssetIn(key="asset_1", partition_mapping=TimeWindowPartitionMapping(start_offset=-1, end_offset=1))
})
def asset_2(context, asset_1_list):
    context.log.info(asset_1_list)
    return {}


asset_2_job = define_asset_job("my_job", selection="*asset_2", partitions_def=partition_def)

defs = Definitions(
    assets=[asset_1, asset_2],
    jobs=[asset_2_job]
)
````

Run "my_job" for date "2023-10-10"
You will end up with one successful materialization for asset_1 and a failed materialization for assert_2

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-11-21 21:45
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/11962.

**Closed** 2023-11-21 21:45 UTC
Labels: type: bug
