### ISSUE TITLE
Local Asset Graph Not Updating

### ISSUE THREAD

**Issue by skalepp** [dagster-io/dagster#19104] opened 2024-01-09 18:24 UTC
### Dagster version

1.5.4

### What's the issue?

I'm having issues with my asset graph and properly updating locally. I went through the steps of clearing browser cache and checking the toggle 'Disable Asset Graph caching'. Essentially - If I delete an asset or create a new asset it's not properly displaying after the above steps.

### What did you expect to happen?

Here's what the asset graph should be displaying:
- The `snapshot_geocoding_latitude_longitude` table should be in the `Geocoding` group. 
- You can see the `snapshot_geocoding` is properly grouped, however the `snapshot_geocoding_latitude_longitude` is being grouped under the default group. (I'll screenshot my sources.yml file)

![asset graph](https://github.com/dagster-io/dagster/assets/40646811/1c25c532-818e-44c7-814a-0808680ee1b7)

![sources](https://github.com/dagster-io/dagster/assets/40646811/9c331457-dfe5-443c-8293-a21c12864b8c)

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by OwenKephart** [comment] 2024-01-09 18:32
Hi @skalepp -- looks like you're using the dbt integration here, which means you'll likely need to regenerate your dbt manifest (`dbt parse`) in order for the new metadata about this project to be usable by dagster.

**Comment by skalepp** [comment] 2024-01-09 19:17
Thanks for your response @OwenKephart. That didn't fix it. I ran dbt compile as well and it still isn't properly loading the asset graph.

**Comment by OwenKephart** [comment] 2024-01-09 19:18
@skalepp and what happens if you hit the refresh icon at the top of the screen (to the right of `quickstart_snowflake`)?

**Comment by skalepp** [comment] 2024-01-09 19:33
@OwenKephart Here's my `dbt parse` command:
`(.venv) PS quickstart_snowflake\dbt_project> dbt parse
19:30:12  Running with dbt=1.5.1
19:30:13  Performance info: target\perf_info.json`

Then after clearing cache, rerunning `dagster dev`, it still isn't listing that snapshot table in the Geocoding group.

**Comment by OwenKephart** [comment] 2024-01-11 00:29
My suspicion here is that this is much more likely to be an issue with the manifest.json file that's being read by your `@dbt_assets` not getting updated, rather than an issue with the UI or something like that. Are you able to double check the paths that are being updated by that dbt parse command and reference them against the manifest file that you're using in dagster?

**Comment by BartBaddeley** [comment] 2024-02-21 16:14
I had a similar problem. For me

**Comment by rexledesma** [comment] 2024-06-03 12:24
Closing, since I can't reproduce. Feel free to file another issue if you're still seeing this problem.

**Closed by rexledesma** 2024-06-03 12:24 UTC
Labels: type: bug
