### ISSUE TITLE
Scheduler Execution Skipped

### ISSUE THREAD

**Issue by nuruladroady** [dagster-io/dagster#3121] opened 2020-10-18 06:46 UTC
When I try the documentation about the scheduler in this link https://docs.dagster.io/tutorial/advanced_scheduling , I get a message like the following, how to solve this problem?
![image](https://user-images.githubusercontent.com/52478220/96360531-3b96fb00-1148-11eb-85e1-7ba3227e54bd.png)

**Comment by helloworld** [comment] 2020-10-18 07:40
The example has a `should_excute` filter on the schedule definition that skips execution on the weekends.

```
    should_execute=weekday_filter,
```

```
def weekday_filter():
    weekno = datetime.today().weekday()
    # Returns true if current day is a weekday
    return weekno < 5
```

Since today is a weekend day, the schedule execution is being skipped :) 

Just remove the filter and your schedule should run as expected.

**Comment by nuruladroady** [comment] 2020-10-19 01:04
yes i know, i don't use filters for weekdays, but i get those logs

**Comment by gibsondan** [comment] 2020-10-19 01:19
Could you post the code of the schedule that’s running into this? With that we should be able to figure out what’s going on here.

**Comment by nuruladroady** [comment] 2020-10-19 01:22
thanks i solved my problem with export dags home. but i got another problem. if I have several python files how to configure workspace.yaml?

**Comment by gibsondan** [comment] 2020-10-19 01:33
Great, glad that worked out - let us know if there's anything that dagster could have done to make the root cause there more clear.

If you have repositories in multiple python files, you have a couple of options. You can have one file that's the main file that is referenced in the workspace.yaml and have that file import each of the repositories from the other files, or you can put all of the files into an installed python package and use the 'python_package' option instead of the 'python_file' option (there's an example here if you search for 'python_package': https://docs.dagster.io/overview/repositories-workspaces/workspaces). Would either of those work for you here?

**Comment by nuruladroady** [comment] 2020-10-19 02:01
Thanks, if I have two pipelines and two python files the configuration is like this.
load_from:
  - python_file: hello_world_repository.py
  - python_file: hello_world_repository2.py

?

**Comment by gibsondan** [comment] 2020-10-19 02:07
Not exactly - the change would be in your python code, not in the workspace configuration. hello_world_repository.py would need to import the repository defined in hello_world_repository2.py, and then the workspace could just reference hello_world_repository.py like before. Or you could have a third file that just imports the repositories from both files (as well as any more files that you add later), and reference that third file in your workspace.yaml.

Alternatively, you could expose both the repository in hello_world_repository.py and the repository in hello_world_repository2.py in an installed python package, and reference that package within your workspace using the 'python_package' option.

**Comment by nuruladroady** [comment] 2020-10-19 02:19
I mean I have two pipelines, two schedulers, and separated by two different python files, how do I configure the workspace, can they be combined and how?

**Comment by gibsondan** [comment] 2020-10-19 02:30
They can definitely be combined, but your workspace.yaml can only reference a single file. That single file can import repositories or pipelines from other files though.


For example, the file that your workspace.yaml references could look something like:


```
from .hello_world_repository import first_repository
from .hello_world_repository2 import second_repository
```

That would be enough for the workspace to include both repositories.

Or if you have two pipelines in different files, that you want to combine them into a single repository, the file included in your workspace.yaml could look like:

```
from .hello_world_pipeline import first_pipeline, first_schedule
from .hello_world_pipeline2 import second_pipeline, second_schedule

@repository
def combined_repository()
  return [first_pipeline, first_schedule, second_pipeline, second_schedule]
```

**Comment by nuruladroady** [comment] 2020-10-19 02:32
Ok got it, thank you anyway.

**Comment by gibsondan** [comment] 2020-10-19 02:35
no problem! I'll close this out for now, feel free to ask here or on Slack if anything else comes up.

**Closed by gibsondan** 2020-10-19 02:35 UTC
