### ISSUE TITLE
Nightly publishing failing

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1780] opened 2019-10-01 16:40 UTC
https://buildkite.com/dagster/dagster-nightly/builds/98#206c4f3e-481c-421f-9b19-b1e87aa6ace1

**Comment by natekupp** [comment] 2019-10-01 17:19
I think the root cause of this issue is related to introducing new library modules. When those are added, the nightly publish job gets into a bad state for some reason; I haven't had a chance to debug it yet.

In the past I've corrected this by wiping the nightly tag from github which seems to fix the issue

**Comment by natekupp** [comment] 2019-10-01 17:21
```
git push origin --delete nightly
git checkout -b nightly
git push -u origin nightly
```

**Comment by natekupp** [comment] 2019-10-01 17:26
^ I just did this, so tomorrow should work, but we should keep this bug open to address the underlying issue of the nightlies breaking for every new module

**Comment by mgasner** [comment] 2019-12-16 19:15
closing in favor of #1512

**Closed by mgasner** 2019-12-16 19:15 UTC
Labels: systems
