### ISSUE TITLE
`AutoMaterializePolicy`ies should allow for single-run materializations of multiple partitions

### ISSUE THREAD

**Issue by askvinni** [dagster-io/dagster#18460] opened 2023-12-03 09:51 UTC
### What's the use case?

Say there is an asset with a `MultiPartitionsDefinition`, partitioned by `TimeWindowPartitionsDefinition` and by a Static or Dynamic set of partitions. Upon a new TimeWindowPartition showing up, the AMP would kick off one run for each static or dynamic partition.

I feel like users should be able to specify that those runs follow the backfill pattern (or they should follow the pattern by default? Though changing default behavior is risky) and if wished for, are all materialized in a single run with a range of partitions.

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-12-04 19:39
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/18237

**Closed by sryza** 2023-12-04 19:39 UTC
Labels: type: feature-request
