### ISSUE TITLE
Auto-materialize + AutoMaterializePolicy.eager() doesn't work as expected

### ISSUE THREAD

**Issue by PierreDubrulle** [dagster-io/dagster#15414] opened 2023-07-20 15:28 UTC
### Dagster version

dagster, version 1.3.14

### What's the issue?

I have two assets: if the first is materialised then the materialisation of the other must start.
I've enabled Auto-materialize.
I expect the second asset to materialise only if the first is materialised. In reality, both assets materialise automatically.
![image](https://github.com/dagster-io/dagster/assets/114570596/5815ac9d-1289-45a3-91a7-667eb214888c)

### Deployment type

Local

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-08-07 21:40
Going to close this for now because, based on the above, I believe what you're observing is the expected behavior, but feel free to reopen if I'm misunderstanding.

**Closed by sryza** 2023-08-07 21:40 UTC
Labels: bug, auto-materialize
