### ISSUE TITLE
FR: access resources from sensors

### ISSUE THREAD

**Issue by mosynaq** [dagster-io/dagster#4402] opened 2021-07-25 13:30 UTC
I am writing an ETL. It needs to start the process when a new record is added to the source database. I want to check for a new record in the source database periodically using sensors. I need to access the resource of the currently selected mode. 
Please add resource access to the context of a sensor object.
```python
...
@sensor
def my_sensor(context):
    should_run = context.resources.source_db.has_new_record()
    ...
```

**Comment by sryza** [comment] 2021-07-26 05:52
@mosynaq thanks for your suggestion. One tricky question we’d need to deal with to make this work is how resource configuration is provided. Currently, sensors provide configuration to the pipeline run that they’re kicking off - including resource configuration. For sensors to be able to use resources, those resources would already need to be configured, which could create a circular dependency.

Are the resources that you’re envisioning accessing from your sensor function configurable? If so, how do you ideally envision configuring them?

**Comment by mosynaq** [comment] 2021-07-26 08:18
> Are the resources that you’re envisioning accessing from your sensor function configurable?

Yes.
> If so, how do you ideally envision configuring them?

As expected, I am using the config for the pipeline which is provided by the sensor through the `run_config` parameter for `RunRequest` as below:
```python
...
@sensor
def my_sensor(context):
    should_run = context.resources.source_db.has_new_record()
    if should_run:
        yield RunRequest(
            run_key=some_key,
            run_config={
                "solids": {...},
                "resources": {
                    "source_db": {
                        "config": {
                            "conn_str": "some_conn_str"
                        }
                    }
                }
            },
        )
```
But If it creates a circular dependency, it would be a good idea to make the sensors configrable and then the config should have a section for resources that can be accessed from both the solids and the sensor itself.

**Comment by VladX09** [comment] 2021-09-10 13:39
Looks like a duplicate of #3794

**Comment by sryza** [comment] 2021-09-13 14:56
@VladX09 thanks for catching the duplicate. I'm going to close this one.

**Closed by sryza** 2021-09-13 14:56 UTC
Labels: feature-request, practitioner, sensors
