### ISSUE TITLE
Asset dependencies not resolved correctly in an asset job containing dagster_dbt and standard assets

### ISSUE THREAD

**Issue by derHeinzer** [dagster-io/dagster#22196] opened 2024-05-31 11:33 UTC
### Dagster version

1.7.4

### What's the issue?

I defined an asset job including 2 assets dagster_dbt_asset_A and dagster_asset_C.

the dependency graph is as follows:
dagster_dbt_asset_A -> dagster_dbt_asset_B -> dagster_asset_C

The dependency is defined as non_argument_dep in asset decorator of dagster_asset_C.

Since dagster_dbt_asset_B is a view I do not need to explicitly materialize it everytime I materialize dagster_dbt_asset_A and dagster_asset_C, unless the view definition has changed. 

However when executing the asset job both assets (dagster_dbt_asset_A , dagster_asset_C) materialize simultanously. The dependency wont be respected.

I consider this a bug even if it is ok to solve it by materializing dagster_dbt_asset_B  in the same job as well or by changing the dependency of dagster_asset_C directly to dagster_dbt_asset_A (which is kind of ugly though) or ultimateley by having two jobs where one is triggered by the other via a run_status_sensor.

### Deployment type

None

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by rexledesma** [comment] 2024-06-03 12:13
This is a duplicate of https://github.com/dagster-io/dagster/issues/6474.

For now, you'll have to ensure that your view (`dagster_dbt_asset_B`) is materialized alongside your desired assets (`dagster_dbt_asset_A` and `dagster_asset_C`) to ensure the dependency is respected.

**Closed by rexledesma** 2024-06-03 12:13 UTC
Labels: type: bug, area: ops/graphs/jobs
