### ISSUE TITLE
Regression: OBJECT_STORE_OPERATION events in terminal do not include relevant path

### ISSUE THREAD

**Issue by catherinewu** [dagster-io/dagster#3368] opened 2020-12-08 20:37 UTC
## Summary
When running a pipeline in Dagit, Dagit shows the path at which intermediates are stored. Running the same pipeline in the terminal (via `execute_pipeline`) shows OBJECT_STORE_OPERATION events which do not include the path at which the intermediate is stored. This makes it very cumbersome for the user to figure out where to inspect the intermediate. 

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment] 2020-12-10 17:13
We are planning to replace ObjectStoreOperation with LoadedInput and HandledOutput.  The regression will still stand in that case, because the new events don't even have fields to track the paths that objects are being written to / read from.

Three different ways we could tackle this:
* Augment the new LoadedInput and HandledOutput events to include fields with the addresses that they're reading from / writing to.
* Yield AssetMaterializations.
* Log it.

I think logging makes the most sense in the short term, because:
* The input/output events are focused on the logical outputs, not the physical assets.  Also, it's unclear what the right data type is for representing addresses.  A string might work in many cases, but not all of them. 
* Yielding AssetMaterializations pollutes the asset catalog.  We've discussed coming up with a namespacing plan that would isolate "system" assets from user assets.  But we don't want to rush that.  We also don't know whether the asset catalog can handle this from a performance perspective if every step of every run generates a new asset.

In the long term, it likely makes sense to handle this with AssetMaterializations.  Thoughts @schrockn @yuhan ?

**Comment by yuhan** [comment] 2020-12-10 18:03
in the long term, it'd be AssetMaterializations to handle this. But in the short term, the problem with using AssetMaterializations is that we don't want to pollute the asset catalog.

How about, instead removing ObjectStoreOperation now, we preserving ObjectStoreOperation until we are done with intermediate storage deprecation cycle (i.e. remove the ObjectStoreOperation in 0.11.0)? So we could yield ObjectStoreOperation in the old path and remove them all at once in 0.11.0. 
- As for "old path", there will be `ObjectManagerIntermediateStorage` which is backcompat layer of `IntermediateStorage`. we can yield ObjectStoreOperation there.
- Some power users would still use their custom IntermediateStorage which means the set path (https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/core/execution/plan/execute_step.py#L380:1) and get path (https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/core/execution/plan/inputs.py#L167) won't go away until 0.11.0. So preserving ObjectStoreOperation isn't complicating the deprecation.

A less conservative approach would be to introduce a subclass of AssetMaterialization which logs information that in the current ObjectStoreOperation and remove ObjectStoreOperation now. This way satisfies the return type of Input/Output Manager (it's an AssetMaterialization) and logs the info to avoid regression. But it kinda pushes us to think ahead about the asset catalog concern

**Comment by sryza** [comment] 2020-12-10 18:19
@yuhan are you imagining that ObjectManagers that are not the ObjectManagerIntermediateStorage would yield ObjectStoreOperations as well?  If a user uses the `fs_object_manager`, I believe they would also want to be able to see the file path.

Separately, is there a concern you have about communicating the file path with a log message?

**Comment by yuhan** [comment] 2020-12-10 18:26
> are you imagining that ObjectManagers that are not the ObjectManagerIntermediateStorage would yield ObjectStoreOperations as well

No. ObjectManagerIntermediateStorage is an IntermediateStorage. ObjectManagers only yield the two new events

> is there a concern you have about communicating the file path with a log message?

Yes, I share your concern. Logging file path isn't applicable to all object managers because object managers are focused on logic objects, i.e. objects won't necessarily have file path. That's why I'm suggesting introducing a new subclass of AssetMaterialization (or maybe a subclass of Input/Output events) which deals with system objects as well as physical paths

**Comment by sryza** [comment] 2020-12-10 18:43
@yuhan if we believe that reporting file paths is important when someone uses `fs_intermediate_store`, then it should also be important when someone uses `fs_object_manager`.  I think both are important in the short term, i.e. people will want to immediately switch to `fs_object_manager` in 0.10.0 to avoid deprecation warnings, and they'll be unhappy if that means they can no longer see the paths that are being written to.

For fs_object_manager, I think that leaves us a few options:
* Use ObjectStoreOperation to report the file path.
* Use AssetMaterialization to report the file path.  This might be a good idea in the long term, but I don't think it's a good idea in the short term, for the reasons I laid out in my original comment.
* Include the file path on HandledOutput/LoadedInput.  I don't think this is a good idea, for the reasons I laid out in my original comment.
* Log the file path inside the methods of fs_object_manager. (@dpeng817 is working on adding log to the context.)

Do you have thoughts on which of these options is the best?

**Comment by schrockn** [comment] 2020-12-10 19:01
To me it's pretty clear we should allow managers to put custom event metadata entries on LoadedInput and HandledOutput events. That would be very flexible

**Comment by schrockn** [comment] 2020-12-10 19:02
We absolutely need to report file paths where stuff is stored in a structured way if the managers involved are creating files on the file system.

**Comment by yuhan** [comment] 2020-12-10 19:03
how about SystemLoadedInput and SystemHandledOutput to log file paths and replace ObjectStoreOperation?

**Comment by schrockn** [comment] 2020-12-10 19:04
I don't see need to make special System variants. I think ObjectStoreOperation should be deleted and that something like a legacy intermediate filestore store should emit LoadedInput and HandledOutput with appropriate metadata attached.

**Comment by yuhan** [comment] 2020-12-10 20:01
re: "allow managers to put custom event metadata entries on LoadedInput and HandledOutput events"
I guess the question is whether ObjectManager should yield AssetMaterialization or LoadedInput/HandledOutput?

Note that AssetStore yields AssetMaterialization only and AssetStoreOperation is constructed internally for feature parity with ObjectStoreOperation. 

In the new object manager world, currently ObjectManager would yield AssetMaterialization and LoadedInput/HandledOutput is constructed internally in execute_step by Dagster machinery which is completely operational. (https://dagster.phacility.com/D5474). 

The question is where the metadata entries go. the options are:
1) yield both AssetMaterialization and LoadedInput/HandledOutput
  - AssetMaterialization indicates the user wants the asset to show up in asset catalog
  - LoadedInput/HandledOutput events with event metadata would not result in asset catalog
2) yield LoadedInput/HandledOutput only - and have a way to let the user choose if they want the event show up in asset catalog, if yes, Dagster machinery construct an AssetMaterialization with the metadata provided via LoadedInput/HandledOutput
3) yield AssetMaterialization only - and have a way to let the user choose if they don't want the event show up in asset catalog.

**Comment by yuhan** [comment] 2021-01-08 20:11
As for stopgap, we decided to 
- introduce HandledOutput/LoadedInput to log the completion of IO manager's handle_output/load_input operations
- replace ObjectStoreOperation with HandledOutput/LoadedInput + context.log the path to avoid regression

**Comment by yuhan** [comment] 2021-08-04 22:44
closing in favor of https://github.com/dagster-io/dagster/issues/4452

**Closed by yuhan** 2021-08-04 22:44 UTC
Labels: bug, core, practitioner
