### ISSUE TITLE
Run for-real prod queries in dagit in dagster-graphql tests.

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#1394] opened 2019-05-28 17:43 UTC
Have an automated (or at least semi-automated way) to extract queries out of dagit and run them in dagster-graphql tests

Best way is probably to use `` apollo client:extract`` to generate queries and then run those queries in dagster-graphql

**Comment by mgasner** [comment] 2019-10-08 18:18
Duplicate of #1361

**Closed by mgasner** 2019-10-08 18:18 UTC
Labels: core, enhancement, test
