### ISSUE TITLE
Executing just a single op from a job raises dagster.core.errors.DagsterInvariantViolationError

### ISSUE THREAD

**Issue by aafendi** [dagster-io/dagster#5589] opened 2021-11-09 20:53 UTC
## Summary

When I select a single OP which calls `context.run_id`, dagster runs the OP fine. 
However, when I select just that OP to run it "not in the job", so Execute just "my-op", it errors. The error I get is as follows.

I expect the OP to be able to run and get the run_id with the same line of code, regardless of if its in a job or not.

## Reproduction

Create a simple job with a couple OPs. A middle OP should call `context.run_id` and print that to the logger. Try running it by selecting just that OP from the jobs playground. It should work. Then repeat it by double clicking on the OP in dagit and re-executing just that OP, this fails.

## Dagit UI/UX Issue Screenshots

`dagster.core.errors.DagsterInvariantViolationError: Attempting to access run_id, but it was not provided when constructing the OutputContext`

Pass -> Failed for different reasons, but failure is non-reproducible
![image](https://user-images.githubusercontent.com/85198156/141002341-18eb172d-d647-491a-b8fa-2eb0f6daa904.png)

Failed
![image](https://user-images.githubusercontent.com/85198156/141002208-16cdfdb6-9e97-4b56-b83b-dbcf6e76be6c.png)

## Additional Info about Your Environment

Python: 3.7.12
Dagster: 0.13.4
Dagstermill: 0.13.4
Dagit: 0.13.4

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by clairelin135** [comment] 2022-02-22 18:40
Hi @aafendi, I'm attempting to reproduce the error with a job that looks like this:
```
@op
def my_first_op():
    return


@op
def other_op():
    return


@op
def my_second_op(context, op_1, op_2):
    context.log.info(context.run_id)


@op
def my_third_op(op_2):
    pass


@job
def my_job():
    my_third_op(my_second_op(my_first_op(), other_op()))
```
But so far accessing `context.run_id` is working on the initial execute and the re-execution. Would you mind providing a code sample so I can try to reproduce this?

**Comment by aafendi** [comment] 2022-02-24 21:40
Hi @clairelin135 thanks for looking into this. Its not a issue for me anymore, we've moved on from using dagster for this project - mostly because it was a bit overkill. Also if you can't reproduce it then its a non-issue now.

**Comment by clairelin135** [comment] 2022-02-24 22:46
Thanks for the response @aafendi. Got it--I'll close the issue now.

**Closed by clairelin135** 2022-02-24 22:46 UTC
Labels: bug
