### ISSUE TITLE
Be able to schedule selections of assets without providing a job

### ISSUE THREAD

**Issue by dpeng817** [dagster-io/dagster#12862] opened 2023-03-09 22:23 UTC
When specifying a run request with an asset selection, you are still required to provide a job_name / job def in order to use it. This is cumbsersome, and purely a result of the way that assets work under the hood. The user experience would be better if it wasn't necessary.

This could be solved relatively easily if the default job name on a schedule was that of the underlying asset mega job.

Thread: https://dagster.slack.com/archives/C01U954MEER/p1678368929707519

**Comment by sryza** [comment] 2023-03-09 23:39
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/11997

> This could be solved relatively easily if the default job name on a schedule was that of the underlying asset mega job.

This gets a little hairy because sometimes there are multiple implicit asset jobs. But not too hairy - we already do it for sensors.

**Closed by sryza** 2023-03-09 23:39 UTC
