### ISSUE TITLE
Labels/Partition Keys cutoff in partition set viewer

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#3502] opened 2021-01-06 16:15 UTC
## Summary

In the presence of long partition keys, they get cutoff in the partition set viewer.

## Dagit UI/UX Issue Screenshots

![Screen Shot 2021-01-06 at 9 13 48 AM](https://user-images.githubusercontent.com/28738937/103791366-9c272d00-4fff-11eb-9ed2-fd185e79d8f5.png)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by hellendag** [comment] 2021-01-08 15:58
Duplicate of #3457.

**Closed by hellendag** 2021-01-08 15:58 UTC
Labels: bug, partitions view
