### ISSUE TITLE
Schedules and sensors that reference a pipeline mode that doesn't exist should raise an error at definition time

### ISSUE THREAD

**Issue by gibsondan** [dagster-io/dagster#4102] opened 2021-04-29 16:09 UTC
## Summary
Similar to how they raise an error if you reference a pipeline that doesn't exist

## Reproduction
Create a schedule that references a non-existant mode. It will fail at execution plan generation time instead of definition time

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by sryza** [comment] 2021-07-14 23:52
This is actually pretty hairy.  The issue is that a repository definition can include pipelines that are instantiated lazily.  We know the pipeline name, but we don't know the pipeline's modes until the pipeline definition is loaded.

With the new graph/job APIs, this will no longer be an issue, because schedules and sensors will hold direct object references to the jobs that they're going to trigger.

I'm going to close this as "Won't Fix", because it won't be a problem with the new APIs, and it's not obvious how to address it in a consistent way.  Anyone, feel free to re-open if you feel otherwise.

**Closed by sryza** 2021-07-14 23:52 UTC
Labels: bug, good first issue, practitioner
