### ISSUE TITLE
Migration errror: column "partition" of relation "runs" does not exist

### ISSUE THREAD

**Issue by kinghuang** [dagster-io/dagster#3649] opened 2021-02-04 23:54 UTC
## Summary

I'm upgrading from Dagster 0.9.19 to 0.10.3. Running `dagster instance migrate`, I'm getting the following error

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "partition" of relation "runs" does not exist
LINE 1: ...on": "refine_text,extract_info,encode_facets"}}', partition=...
```

## Reproduction

N/A

## Dagit UI/UX Issue Screenshots

Here's the full output from running `dagster instance migrate`.

```
root@76c9413f31a8:/opt/dagster/home# dagster instance migrate
$DAGSTER_HOME: /opt/dagster/home

Updating run storage...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
  0%|                                                                                                                                                     | 0/108 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "partition" of relation "runs" does not exist
LINE 1: ...on": "refine_text,extract_info,encode_facets"}}', partition=...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dagster", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/__init__.py", line 43, in main
    cli(auto_envvar_prefix=ENV_PREFIX)  # pylint:disable=E1123
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dagster/cli/instance.py", line 47, in migrate_command
    instance.upgrade(click.echo)
  File "/usr/local/lib/python3.8/site-packages/dagster/core/instance/__init__.py", line 473, in upgrade
    self._run_storage.build_missing_indexes()
  File "/usr/local/lib/python3.8/site-packages/dagster/core/storage/runs/sql_run_storage.py", line 582, in build_missing_indexes
    migration_fn()(self, print_fn)
  File "/usr/local/lib/python3.8/site-packages/dagster/core/storage/runs/migration.py", line 24, in migrate_run_partition
    instance.add_run_tags(run.run_id, run.tags)
  File "/usr/local/lib/python3.8/site-packages/dagster/core/storage/runs/sql_run_storage.py", line 280, in add_run_tags
    conn.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "partition" of relation "runs" does not exist
LINE 1: ...on": "refine_text,extract_info,encode_facets"}}', partition=...
                                                             ^

[SQL: UPDATE runs SET run_body=%(run_body)s, partition=%(partition)s, partition_set=%(partition_set)s, update_timestamp=%(update_timestamp)s WHERE runs.run_id = %(run_id_1)s]
[parameters: {'run_body': '{"__class__": "PipelineRun", "execution_plan_snapshot_id": "d115246c15fbd32cfba80ffa476ae3fd53476729", "external_pipeline_origin": {"__class__": "Ext ... (1757 characters truncated) ... }", "dagster/partition": "2020", "dagster/partition_set": "coding_recs_yearly", "dagster/solid_selection": "refine_text,extract_info,encode_facets"}}', 'partition': '2020', 'partition_set': 'coding_recs_yearly', 'update_timestamp': datetime.datetime(2021, 2, 4, 23, 49, 3, 422750), 'run_id_1': '25f2001c-8726-468f-9577-e662f589347c'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

## Additional Info about Your Environment

* Python 3.8.7
* Dagster 0.10.3 (upgrading from 0.9.19).

Dagster is running a container. Database is PostgreSQL (using AWS RDS Aurora Serverless).

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by prha** [comment] 2021-02-05 00:48
This is odd.  The `dagster instance migrate` command should run the schema migration to add the `partition` column.

Can you paste the output for the following commands:
```select * from alembic_version;```
```\d+ runs```

**Comment by kinghuang** [comment] 2021-02-05 01:49
Here's the output.

```
postgres=> select * from alembic_version;
 version_num
--------------
 4ea2b1f6f67b
(1 row)

postgres=> \d+ runs
                                                               Table "dagster.runs"
      Column      |            Type             | Collation | Nullable |             Default              | Storage  | Stats target | Description
------------------+-----------------------------+-----------+----------+----------------------------------+----------+--------------+-------------
 id               | integer                     |           | not null | nextval('runs_id_seq'::regclass) | plain    |              |
 run_id           | character varying(255)      |           |          |                                  | extended |              |
 snapshot_id      | character varying(255)      |           |          |                                  | extended |              |
 pipeline_name    | character varying           |           |          |                                  | extended |              |
 status           | character varying(63)       |           |          |                                  | extended |              |
 run_body         | character varying           |           |          |                                  | extended |              |
 create_timestamp | timestamp without time zone |           |          | CURRENT_TIMESTAMP                | plain    |              |
 update_timestamp | timestamp without time zone |           |          | CURRENT_TIMESTAMP                | plain    |              |
Indexes:
    "runs_pkey" PRIMARY KEY, btree (id)
    "runs_run_id_key" UNIQUE CONSTRAINT, btree (run_id)
Foreign-key constraints:
    "fk_runs_snapshot_id_snapshots_snapshot_id" FOREIGN KEY (snapshot_id) REFERENCES snapshots(snapshot_id)
Referenced by:
    TABLE "run_tags" CONSTRAINT "run_tags_run_id_fkey" FOREIGN KEY (run_id) REFERENCES runs(run_id) ON DELETE CASCADE
```

**Comment by prha** [comment] 2021-02-05 04:07
We're honestly fairly confused how your database got into this state, but we have a command that you should be able to run to get back to a good state.

One thing I wanted to ask - are you confident the output from 'dagster instance migrate' that you posted in the issue is from the first time you ran it and it hit the issue?

Either way - here are the steps I'd recommend to complete the migration. This should be completely safe, but out of an abundance of caution if might be worth saving a dump of your DB first if there's data on there that you want to be 100% certain about.
* Run `DROP TABLE alembic_version;` on your postgres DB (this tells our migrate script to start from the beginning)
* Run `dagster instance migrate` again. It should complete successfully now.

**Comment by kinghuang** [comment] 2021-02-05 04:25
Just confirming that dropping the `alembic_version` table and redoing the migration worked.

I don't have a snapshot of the database from before the error handy, but I think I can recreate the conditions. I'll file an issue if I can reproduce the error.

**Comment by prha** [comment] 2021-02-05 16:35
King, I'm going to close this out.  Please file another issue if you can recreate it.

**Closed by prha** 2021-02-05 16:35 UTC
Labels: bug
