### ISSUE TITLE
Allow assets to accept config via `.configured()`

### ISSUE THREAD

**Issue by clairelin135** [dagster-io/dagster#9459] opened 2022-08-23 20:27 UTC
### What's the use case?

We already allow run config/default config on assets, it would be an ergonomic improvement to allow configuration via `.configured()`

**Comment by sryza** [comment] 2022-08-23 21:38
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/9359

**Closed by sryza** 2022-08-23 21:38 UTC
Labels: feature-request, config, asset-defs
