### ISSUE TITLE
Asset Catalog can get into a state where materializations do not expand

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#6418] opened 2022-01-31 03:49 UTC
## Summary

See this video. This is with SDA turned on.

You'll see that I'm able to expand the first asset materialization, but then when I try to do that another one I get into a bad state where it not expanding.

https://user-images.githubusercontent.com/28738937/151736252-0c18901e-364a-49e2-9a34-ecfb078d3162.mov

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment] 2022-02-02 05:49
I /think/ this is addressed in https://github.com/dagster-io/dagster/pull/6392 (not able to reproduce it on top of the latest changes there) but will re-test once all the open PRs are merged.

**Comment by bengotow** [comment] 2022-04-08 20:33
Hey folks! Looks like this was assumed fixed and no-one has complained since Feb 1, so I think we're set here. 👍

**Closed by bengotow** 2022-04-08 20:33 UTC
Labels: bug, asset-defs, dagit
