### ISSUE TITLE
Dagit Favicon not switching between light and dark mode in chrome

### ISSUE THREAD

**Issue by braunjj** [dagster-io/dagster#10546] opened 2022-11-16 14:59 UTC
Reported in Slack [here](https://dagster.slack.com/archives/C01U5LFUZJS/p1668595887768949).

I think the issue is just that chrome is switching between dark and light mode and not swapping out the favicon correctly until after a page refresh. There might not be much we can do about this, but we should look into it. 

The user who reported this is on a M1 Mac using Chrome.

**Comment by hellendag** [comment] 2022-11-23 21:07
Does this happen in other browsers?

**Comment by bengotow** [comment] 2022-12-06 21:14
Hey folks! I am able to reproduce this in the latest version of Chrome, but it looks like the problem is that Chrome doesn't re-render the favicons after the system prefer-dark-mode setting changes. We can't really do anything about this from our Javascript because tabs in the background probably won't get the media query change event -- it'd need to be fixed at the browser level. (I use Firefox and it handles this fine, so hopefully this is something they fix!)

**Comment by bengotow** [comment] 2022-12-06 21:15
update: it looks like the Chromium folks are on it! https://bugs.chromium.org/p/chromium/issues/detail?id=1208277&q=prefers-color-scheme%20favicon&can=2

**Comment by bengotow** [comment] 2022-12-16 15:17
Closing as blocked on upstream 👋

**Closed by bengotow** 2022-12-16 15:17 UTC
Labels: dagit
