### ISSUE TITLE
Seeing stalls in the Gantt Chart

### ISSUE THREAD

**Issue by schrockn** [dagster-io/dagster#6415] opened 2022-01-31 03:21 UTC
## Summary

I'm reliably seeing stalls in the Gantt Viewer appears to lock. Here is an example:

https://user-images.githubusercontent.com/28738937/151734495-0e24689f-35ee-4374-b8e9-b57695e7d556.mov

This is actually one the *better* runs, but the stall still happens in the 2nd and 3rd step. In most runs the 1st step locks up.

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by bengotow** [comment] 2022-02-22 22:32
Hey folks! Will try to reproduce this later today. My guess is that this is caused by the front-end receiving a ton of data all at once or us rendering a log row with a large amount of collapsed metadata...

**Comment by bengotow** [comment] 2022-02-22 22:44
Hmm, I'm not able to get this to happen actually - I tried examples/bollinger a bunch of times and I see the same graph but it completes in roughly 10s and I don't get any stalling. @smackesey do you know if a previous version of that job (from ~20 days ago) could have been a problem? The version I'm running looks like it was committed 7 days ago.

**Comment by smackesey** [comment] 2022-02-22 22:50
@bengotow There was a previous version of this job that did have some problems at one time, but IIRC the issue wasn't like what's in the screencast. It's more that the Bollinger step would never finish running. I've never seen the GANTT stalling thing either.

At the time that this was reported, Nick was preparing for a demo and I believe was using Chrome Canary/Beta because his stable Chrome install had issues with crashing. Can't tell if that's Chrome Beta in that screencast though. 

@sryza Did you ever encounter GANTT stalling like this?

**Comment by sryza** [comment] 2022-02-23 00:13
I encountered some gantt problems of the form that @smackesey mentioned above, but not the kind that's shown in Nick's video.

**Comment by hellendag** [comment] 2022-04-05 20:16
No reliable repro on this, let's reopen if we're able to nail down a repro.

**Closed by hellendag** 2022-04-05 20:16 UTC
Labels: bug, dagit
