### ISSUE TITLE
How to add Ray as an executor? Are there any examples as references?

### ISSUE THREAD

**Issue by markqiu** [dagster-io/dagster#2830] opened 2020-08-19 11:56 UTC

**Comment by alangenfeld** [comment] 2020-08-19 15:06
https://docs.dagster.io/overview/run-launchers-executors/executor

https://docs.dagster.io/_apidocs/internals#executors

multi process: https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/executor/multiprocess.py
dask: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-dask/dagster_dask/executor.py
celery: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-celery/dagster_celery/executor.py

**Comment by markqiu** [comment] 2020-08-20 04:56
Thank you very much. I will try to add a Ray Executor. @alangenfeld

**Comment by yuhan** [comment] 2021-03-22 22:30
Closing in favor of https://github.com/dagster-io/dagster/issues/3924

**Closed by yuhan** 2021-03-22 22:30 UTC
Labels: docs:content-how-to, documentation, integrations

**Comment by Irvenae** [comment] 2022-03-07 07:27
@markqiu did it work out to add the ray executor?
Would like to use Ray over Dagster :)

**Comment by markqiu** [comment] 2022-03-07 07:29
> @markqiu did it work out to add the ray executor? Would like to use Ray over Dagster :)

Sorry, I didn't.

**Comment by Nintorac** [comment] 2022-06-22 11:37
Hey I had a very rough crack at this. Will post code in case anyone else want's to take a look. Mostly stolen from the dask executor.

I think would need to implement the IO manager so I did, also rough ><

In the executor I haven't solved dependencies so all the tasks run at once -- not sure how to go about that, will need to dig deeper into how dagster represents this.

For the IOManager I am not sure what's happening, the only thing being written to the `PinningActor` is a `result` key and Dagit it looks like all ops are writing their results to that same results key. Not sure what I'm missing here, thought they should be saved as the asset names. Seems to work though otherwise.


```
import asyncio
import ray

from dagster import Executor, Field, Permissive, Selector, StringSource
from dagster import _check as check
from dagster import multiple_process_executor_requirements, seven
from dagster.core.definitions.executor_definition import executor
from dagster.core.errors import raise_execution_interrupts
from dagster.core.events import DagsterEvent
from dagster.core.execution.api import create_execution_plan, execute_plan
from dagster.core.execution.context.system import PlanOrchestrationContext
from dagster.core.execution.plan.plan import ExecutionPlan
from dagster.core.execution.retries import RetryMode
from dagster.core.instance import DagsterInstance
from dagster.utils import frozentags, iterate_with_context

# Dask resource requirements are specified under this key
DASK_RESOURCE_REQUIREMENTS_KEY = "dagster-dask/resource_requirements"


@executor(
    name="ray",
    requirements=multiple_process_executor_requirements(),
    config_schema={},
)
def ray_executor(init_context):
    """Ray(Dask)-based executor.

    """
    
    return RayExecutor()


@ray.remote
def query_on_ray_worker(
    dependencies,
    recon_pipeline,
    pipeline_run,
    run_config,
    step_keys,
    mode,
    instance_ref,
    known_state,
):  # pylint: disable=unused-argument
    """Note that we need to pass "dependencies" to ensure Dask sequences futures during task
    scheduling, even though we do not use this argument within the function.
    """

    with DagsterInstance.from_ref(instance_ref) as instance:
        subset_pipeline = recon_pipeline.subset_for_execution_from_existing_pipeline(
            pipeline_run.solids_to_execute
        )

        execution_plan = create_execution_plan(
            subset_pipeline,
            run_config=run_config,
            step_keys_to_execute=step_keys,
            mode=mode,
            known_state=known_state,
        )

        return execute_plan(
            execution_plan, subset_pipeline, instance, pipeline_run, run_config=run_config
        )


def get_dask_resource_requirements(tags):
    check.inst_param(tags, "tags", frozentags)
    req_str = tags.get(DASK_RESOURCE_REQUIREMENTS_KEY)
    if req_str is not None:
        return seven.json.loads(req_str)

    return {}


class RayExecutor(Executor):
    def __init__(self):
        # self.cluster_type = check.opt_str_param(cluster_type, "cluster_type", default="local")
        # self.cluster_configuration = check.opt_dict_param(
        #     cluster_configuration, "cluster_configuration"
        # )
        pass
    
    @property
    def retries(self):
        return RetryMode.DISABLED

    def execute(self, plan_context, execution_plan):
        check.inst_param(plan_context, "plan_context", PlanOrchestrationContext)
        check.inst_param(execution_plan, "execution_plan", ExecutionPlan)
        check.param_invariant(
            isinstance(plan_context.executor, RayExecutor),
            "plan_context",
            "Expected executor to be DaskExecutor got {}".format(plan_context.executor),
        )

        check.invariant(
            plan_context.instance.is_persistent,
            "Dask execution requires a persistent DagsterInstance",
        )

        step_levels = execution_plan.get_steps_to_execute_by_level()

        pipeline_name = plan_context.pipeline_name

        instance = plan_context.instance

        if not ray.is_initialized():
            ray.init("ray://localhost:10001",
                runtime_env = {
                    "working_dir": "/home/oliver/datarwe/extubation_risk_experiments/data_eng",
                    "pip": ["dagster==0.15.0"]
                }
            )
        execution_futures = []
        execution_futures_dict = {}

        for step_level in step_levels:
            for step in step_level:
                # We ensure correctness in sequencing by letting Dask schedule futures and
                # awaiting dependencies within each step.
                dependencies = []
                for step_input in step.step_inputs:
                    for key in step_input.dependency_keys:
                        dependencies.append(execution_futures_dict[key])

                if plan_context.pipeline.get_definition().is_job:
                    run_config = plan_context.run_config
                else:
                    run_config = dict(plan_context.run_config, execution={"in_process": {}})

                dask_task_name = "%s.%s" % (pipeline_name, step.key)

                recon_pipeline = plan_context.reconstructable_pipeline


                future = query_on_ray_worker.remote(
                    dependencies,
                    recon_pipeline,
                    plan_context.pipeline_run,
                    run_config,
                    [step.key],
                    plan_context.pipeline_run.mode,
                    instance.get_ref(),
                    execution_plan.known_state,
                    # key=dask_task_name,
                    # resources=get_dask_resource_requirements(step.tags)
                )

                execution_futures.append(future)
                execution_futures_dict[step.key] = future

        # This tells Dask to awaits the step executions and retrieve their results to the
        # master
        futures = ray.get(execution_futures)
        
        # refs = [fun.remote() for _ in range(4)]
        futures = [ref.future() for ref in execution_futures]

        def thing():
            not_ready = execution_futures
            while True: 
                ready, not_ready = ray.wait(not_ready)

                result = ray.get(ready)
                for r in result:
                    yield ready, r
                if not not_ready:
                    break


        # Allow interrupts while waiting for the results from Dask
        for future, result in iterate_with_context(raise_execution_interrupts, thing()):
            for step_event in result:
                if isinstance(step_event, list): raise Exception(step_event)
                check.inst(step_event, DagsterEvent)
                yield step_event

    def build_dict(self, pipeline_name):
        """Returns a dict we can use for kwargs passed to dask client instantiation.

        Intended to be used like:

        with dask.distributed.Client(**cfg.build_dict()) as client:
            << use client here >>

        """
        if self.cluster_type in ["yarn", "pbs", "moab", "sge", "lsf", "slurm", "oar", "kube"]:
            dask_cfg = {"name": pipeline_name}
        else:
            dask_cfg = {}

        if self.cluster_configuration:
            for k, v in self.cluster_configuration.items():
                dask_cfg[k] = v

        # if address is set, don't add LocalCluster args
        # context: https://github.com/dask/distributed/issues/3313
        if (self.cluster_type == "local") and ("address" not in dask_cfg):
            # We set threads_per_worker because Dagster is not thread-safe. Even though
            # environments=True by default, there is a clever piece of machinery
            # (dask.distributed.deploy.local.nprocesses_nthreads) that automagically makes execution
            # multithreaded by default when the number of available cores is greater than 4.
            # See: https://github.com/dagster-io/dagster/issues/2181
            # We may want to try to figure out a way to enforce this on remote Dask clusters against
            # which users run Dagster workloads.
            dask_cfg["threads_per_worker"] = 1

        return dask_cfg

```

and the IO manager is needed

```
from time import sleep
from unicodedata import name
from dagster import IOManager, io_manager
import ray
import logging

@ray.remote
class PinningActor():

    def __init__(self):
        self.objects = {}

    def keys(self):
        return list(self.objects.keys())

    def handle_output(self, context, obj):
        # write_csv("some/path")
        self.objects[context] = obj

    def load_input(self, context):
        # return read_csv("some/path")
        return self.objects[context]


class RayIOManager(IOManager):
    def __init__(self):
        assert ray.is_initialized(), 'ray not initialised'
          
            # PinningActor.options(name="io", namespace="dagster").remote()
            # sleep(100000000)
        # else:
        #     1/0

        try:
            self.pinning_actor = ray.get_actor("io", namespace="dagster")

        except ValueError:
            
            # 1/0
            self.pinning_actor = PinningActor.options(name="io", namespace="dagster", lifetime="detached").remote()


    def handle_output(self, context, obj):
        
        assert ray.is_initialized(), 'ray not initialised'

        name = context.name
        ray.get(self.pinning_actor.handle_output.remote(name, obj))

    def load_input(self, context):
        
        assert ray.is_initialized(), 'ray not initialised'

        name = context.upstream_output.name
        return ray.get(self.pinning_actor.load_input.remote(name))

@io_manager
def ray_io_manager(init_context):

    return RayIOManager()
```

**Comment by Nintorac** [comment] 2022-06-22 13:20
@yuhan I cannot figure out how to add more executors to the dagster instance, the only way I can find is through `@jobs` but can't find a path for assets to use a custom executor

**Comment by Nintorac** [comment] 2022-06-23 00:29
OK figured out how to set executors properly. 

Current state seems to be:
- Ray IO Manager/Multiprocess executor
   - Experienced a few crashes initially but haven't been able to reproduce since
- Ray Executor
   - Does not seem to like dynamic outputs.
   - works fine on simple job without dynamic output, don't have any more complex jobs to try out
   
   
simple job I used for testing

```python
@op
def a(a):
    from time import sleep
    sleep(len(a))
    return a + [1]

@graph
def g():
    data = []

    for i in range(100):
        data = a(data)

job =  g.to_job(
            'raypickle',
            executor_def=ray_executor
        )
```

**Comment by Nintorac** [comment] 2022-06-24 03:28
Copied from the multiprocess executor this time and it's working :) basically a monkey hitting things with sticks so there's some issues

current known issues:
- termination doesn't work properly
- some Dagster step events have been commented as they don't exist in my version (`0.15.0`)

unknown number of unknown issues :P

```python
import multiprocessing
from multiprocessing.sharedctypes import Value
import os
import sys
from typing import List, Optional

from dagster import MetadataEntry, executor
from dagster import _check as check
from dagster.core.errors import (
    DagsterExecutionInterruptedError,
    DagsterSubprocessError,
    DagsterUnmetExecutorRequirementsError,
)
from dagster.core.events import DagsterEvent, EngineEventData
from dagster.core.execution.api import create_execution_plan, execute_plan_iterator
from dagster.core.execution.context.system import PlanOrchestrationContext
# from dagster.core.execution.context_creation_pipeline import create_context_free_log_manager
from dagster.core.execution.context_creation_pipeline import _create_context_free_log_manager as create_context_free_log_manager
from dagster.core.execution.plan.objects import StepFailureData
from dagster.core.execution.plan.plan import ExecutionPlan
from dagster.core.execution.retries import RetryMode
from dagster.core.executor.base import Executor
from dagster.core.instance import DagsterInstance
from dagster.utils import start_termination_thread
from dagster.utils.error import serializable_error_info_from_exc_info
from dagster.utils.timing import format_duration, time_execution_scope
from ray import remote
import ray

# from .child_process_executor import (
#     ChildProcessCommand,
#     ChildProcessCrashException,
#     ChildProcessEvent,
#     ChildProcessSystemErrorEvent,
#     execute_child_process_command,
# )

DELEGATE_MARKER = "multiprocess_subprocess_init"


@remote
class RayProcessCommand():
    def __init__(
        self,
        run_config,
        pipeline_run,
        step_key,
        instance_ref,
        recon_pipeline,
        retry_mode,
        known_state,
    ):
        self.run_config = run_config
        self.pipeline_run = pipeline_run
        self.step_key = step_key
        self.instance_ref = instance_ref
        self.recon_pipeline = recon_pipeline
        self.retry_mode = retry_mode
        self.known_state = known_state

        self.events = []
        self.execution_complete = False

    def start(self):
        for event in self.execute():
            self.events.append(event)

    def next(self):
        if self.events:
            return self.events.pop(0)
        return None

    def execute(self):
        pipeline = self.recon_pipeline
        with DagsterInstance.from_ref(self.instance_ref) as instance:
            # start_termination_thread(self.term_event)
            execution_plan = create_execution_plan(
                pipeline=pipeline,
                run_config=self.run_config,
                mode=self.pipeline_run.mode,
                step_keys_to_execute=[self.step_key],
                known_state=self.known_state,
            )

            # log_manager = create_context_free_log_manager(instance, self.pipeline_run)
            log_manager = None

            # yield DagsterEvent.step_worker_started(
            #     log_manager,
            #     self.pipeline_run.pipeline_name,
            #     message='Executing step "{}" in subprocess.'.format(self.step_key),
            #     metadata_entries=[
            #         MetadataEntry("pid", value=str(os.getpid())),
            #     ],
            #     step_key=self.step_key,
            # )

            yield from execute_plan_iterator(
                execution_plan,
                pipeline,
                self.pipeline_run,
                run_config=self.run_config,
                retry_mode=self.retry_mode.for_inner_plan(),
                instance=instance,
            )


class RayExecutor(Executor):
    def __init__(
        self,
        retries: RetryMode,
        max_concurrent: int,
    ):
        self._retries = check.inst_param(retries, "retries", RetryMode)
        max_concurrent = max_concurrent if max_concurrent else multiprocessing.cpu_count()
        self._max_concurrent = check.int_param(max_concurrent, "max_concurrent")

        
        
        
    @property
    def retries(self):
        return self._retries

    def execute(self, plan_context, execution_plan):
        check.inst_param(plan_context, "plan_context", PlanOrchestrationContext)
        check.inst_param(execution_plan, "execution_plan", ExecutionPlan)

        pipeline = plan_context.reconstructable_pipeline
        # multiproc_ctx = multiprocessing.get_context(self._start_method)
        # if self._start_method == "forkserver":
        #     # if explicitly listed in config we will use that
        #     if self._explicit_forkserver_preload is not None:
        #         preload = self._explicit_forkserver_preload

        #     # or if the reconstructable pipeline has a module target, we will use that
        #     elif pipeline.get_module():
        #         preload = [pipeline.get_module()]

        #     # base case is to preload the dagster library
        #     else:
        #         preload = ["dagster"]

        #     # we import this module first to avoid user code like
        #     # pyspark.serializers._hijack_namedtuple from breaking us
        #     if "dagster.core.executor.multiprocess" not in preload:
        #         preload = ["dagster.core.executor.multiprocess"] + preload

        #     # multiproc_ctx.set_forkserver_preload(preload)

        limit = self._max_concurrent

        yield DagsterEvent.engine_event(
            plan_context,
            "Executing steps using multiprocess executor: parent process (pid: {pid})".format(
                pid=os.getpid()
            ),
            event_specific_data=EngineEventData.multiprocess(
                os.getpid(), step_keys_to_execute=execution_plan.step_keys_to_execute
            ),
        )

        # It would be good to implement a reference tracking algorithm here so we could
        # garbage collect results that are no longer needed by any steps
        # https://github.com/dagster-io/dagster/issues/811
        with time_execution_scope() as timer_result:
            with execution_plan.start(retry_mode=self.retries) as active_execution:
                active_iters = {}
                errors = {}
                term_events = {}
                stopping = False

                while (not stopping and not active_execution.is_complete) or active_iters:
                    if active_execution.check_for_interrupts():
                        yield DagsterEvent.engine_event(
                            plan_context,
                            "Multiprocess executor: received termination signal - "
                            "forwarding to active child processes",
                            EngineEventData.interrupted(list(term_events.keys())),
                        )
                        stopping = True
                        active_execution.mark_interrupted()
                        for key, event in term_events.items():
                            event.set()

                    # start iterators
                    while len(active_iters) < limit and not stopping:
                        steps = active_execution.get_steps_to_execute(
                            limit=(limit - len(active_iters))
                        )

                        if not steps:
                            break

                        for step in steps:
                            step_context = plan_context.for_step(step)
                            # term_events[step.key] = multiproc_ctx.Event()
                            active_iters[step.key] = execute_step_out_of_process(
                                pipeline,
                                step_context,
                                step,
                                errors,
                                term_events,
                                self.retries,
                                active_execution.get_known_state(),
                            )

                    # process active iterators
                    empty_iters = []
                    for key, step_iter in active_iters.items():
                        try:
                            event_or_none = next(step_iter)
                            if event_or_none is None:
                                continue
                            else:
                                yield event_or_none
                                active_execution.handle_event(event_or_none)

                        # except ChildProcessCrashException as crash:
                        #     serializable_error = serializable_error_info_from_exc_info(
                        #         sys.exc_info()
                        #     )
                        #     step_context = plan_context.for_step(
                        #         active_execution.get_step_by_key(key)
                        #     )
                        #     yield DagsterEvent.engine_event(
                        #         step_context,
                        #         (
                        #             "Multiprocess executor: child process for step {step_key} "
                        #             "unexpectedly exited with code {exit_code}"
                        #         ).format(step_key=key, exit_code=crash.exit_code),
                        #         EngineEventData.engine_error(serializable_error),
                        #     )
                        #     step_failure_event = DagsterEvent.step_failure_event(
                        #         step_context=plan_context.for_step(
                        #             active_execution.get_step_by_key(key)
                        #         ),
                        #         step_failure_data=StepFailureData(
                        #             error=serializable_error, user_failure_data=None
                        #         ),
                        #     )
                        #     active_execution.handle_event(step_failure_event)
                        #     yield step_failure_event
                        #     empty_iters.append(key)
                        except StopIteration:
                            # raise Exception()
                            empty_iters.append(key)

                    # clear and mark complete finished iterators
                    for key in empty_iters:
                        del active_iters[key]
                        active_execution.verify_complete(plan_context, key)

                    # process skipped and abandoned steps
                    yield from active_execution.plan_events_iterator(plan_context)

                errs = {pid: err for pid, err in errors.items() if err}

                # After termination starts, raise an interrupted exception once all subprocesses
                # have finished cleaning up (and the only errors were from being interrupted)
                if (
                    stopping
                    and (not active_iters)
                    and all(
                        [
                            err_info.cls_name == "DagsterExecutionInterruptedError"
                            for err_info in errs.values()
                        ]
                    )
                ):
                    yield DagsterEvent.engine_event(
                        plan_context,
                        "Multiprocess executor: interrupted all active child processes",
                        event_specific_data=EngineEventData(),
                    )
                    raise DagsterExecutionInterruptedError()
                elif errs:
                    raise DagsterSubprocessError(
                        "During multiprocess execution errors occurred in child processes:\n{error_list}".format(
                            error_list="\n".join(
                                [
                                    "In process {pid}: {err}".format(pid=pid, err=err.to_string())
                                    for pid, err in errs.items()
                                ]
                            )
                        ),
                        subprocess_error_infos=list(errs.values()),
                    )

        yield DagsterEvent.engine_event(
            plan_context,
            "Multiprocess executor: parent process exiting after {duration} (pid: {pid})".format(
                duration=format_duration(timer_result.millis), pid=os.getpid()
            ),
            event_specific_data=EngineEventData.multiprocess(os.getpid()),
        )


def execute_step_out_of_process(
    pipeline,
    step_context,
    step,
    errors,
    term_events,
    retries,
    known_state,
):
    command = RayProcessCommand.options(max_concurrency=2).remote(
        run_config=step_context.run_config,
        pipeline_run=step_context.pipeline_run,
        step_key=step.key,
        instance_ref=step_context.instance.get_ref(),
        # term_event=term_events[step.key],
        recon_pipeline=pipeline,
        retry_mode=retries,
        known_state=known_state,
    )
    # engine_event
    # yield DagsterEvent.step_worker_starting(
    #     step_context,
    #     'Launching ray actor for "{}".'.format(step.key),
    #     metadata_entries=[],
    # )
    # raise Exception(command.__dir__())
    finished = [command.start.remote()]
    # ray.get(finished)
    while True:
        
        # check finished before getting any events
        is_finished, _ = ray.wait(finished, timeout=0)
        ret = ray.get(command.next.remote())
        
        if ret is None and is_finished:
            return
        if ret is None or isinstance(ret, DagsterEvent):
            yield ret
        else:
            check.failed("Unexpected return value from child process {}".format(type(ret)))


@executor(
    name="ray",
)
def ray_executor(init_context):
    """Ray(mp)-based executor.

    """
    return RayExecutor(
        retries=RetryMode.DISABLED,
        max_concurrent=10    
    )


```

**Comment by mkleinbort** [comment] 2024-03-31 18:01
Adding that I came across this: https://github.com/danielgafni/dagster-ray

**Comment by mkleinbort** [comment] 2024-03-31 18:02
Would love to see a working ray executor, it'd add an easy way to scale compute beyond one machine without getting into a kubernetes deployment.
