### ISSUE TITLE
AssetSensor doesn't work when monitored asset is dbt asset and output is SensorResult

### ISSUE THREAD

**Issue by michaelwang1994-olo** [dagster-io/dagster#17957] opened 2023-11-13 16:21 UTC
### Dagster version

dagster, version 1.4.6

### What's the issue?

We materialize a dbt asset weekly and have an `asset_sensor` monitor it to run a downstream multi-partitioned job. We noticed that at each sensor tick, the code within the sensor was executing even though there were no new materializations of the upstream dbt asset. 

### What did you expect to happen?

I expected that the sensor code would not execute if there were no new materializations of the upstream dbt asset. 

### How to reproduce?

1. Clone this repo: https://github.com/michaelwang1994-olo/tutorial-dbt-dagster-with-sensors
2. `cd jaffle_dagster`
3. `DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=0 dagster dev`
4. Turn on the `customer_sensor` in the UI
5. Materialize all dbt assets upstream of the `customers` asset
6. View sensor status

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by alangenfeld** [comment] 2023-11-13 16:50
You need to progress the `cursor` to avoid the sensor repeatedly firing for the same upstream materialization event. 

Here https://github.com/michaelwang1994-olo/tutorial-dbt-dagster-with-sensors/blob/main/jaffle_dagster/jaffle_dagster/sensors.py#L31
needs to be updated to `cursor=event.storage_id`

**Comment by michaelwang1994-olo** [comment] 2023-11-13 17:21
@alangenfeld, thanks for the reply. I tried using that code but got the following error: `AttributeError: 'EventLogEntry' object has no attribute 'storage_id'`

Here's the stdout of `event`:

```
EventLogEntry(error_info=None, level=10, user_message='Materialized value customers.', run_id='b4579977-ca8d-4706-ac5b-5196e72a429d', timestamp=1699895833.112798, step_key='jaffle_shop_dbt_assets', job_name='__ASSET_JOB_0', dagster_event=DagsterEvent(event_type_value='ASSET_MATERIALIZATION', job_name='__ASSET_JOB_0', step_handle=StepHandle(node_handle=NodeHandle(name='jaffle_shop_dbt_assets', parent=None), key='jaffle_shop_dbt_assets'), node_handle=NodeHandle(name='jaffle_shop_dbt_assets', parent=None), step_kind_value='COMPUTE', logging_tags={'job_name': '__ASSET_JOB_0', 'op_name': 'jaffle_shop_dbt_assets', 'resource_fn_name': 'None', 'resource_name': 'None', 'run_id': 'b4579977-ca8d-4706-ac5b-5196e72a429d', 'step_key': 'jaffle_shop_dbt_assets'}, event_specific_data=StepMaterializationData(materialization=AssetMaterialization(asset_key=AssetKey(['customers']), description=None, metadata={'unique_id': TextMetadataValue(text='model.jaffle_shop.customers'), 'Execution Duration': FloatMetadataValue(value=0.05328)}, partition=None, tags={'dagster/code_version': '03426b7771a414093eb8e051e97a05b5277656c5', 'dagster/data_version': '27370110c0bb72d8f2a2e0587a1e76eaae672bb442ee29c75ce48f65cfcb4cb3', 'dagster/input_data_version/stg_customers': '5efef3ed0b9a67a69b8a8f97bfe8e51ae2c8338630a73628ef56b18cf92ff49e', 'dagster/input_data_version/stg_orders': '1c971735a025753b7913f97ba455fc70d743d64a351f7ca1e6033ea0a4e81ec2', 'dagster/input_data_version/stg_payments': 'd580d6f30b9e1d9d0f54d373e4179d97af88e534abda334f62455486e6d8869f', 'dagster/input_event_pointer/stg_customers': '12', 'dagster/input_event_pointer/stg_orders': '14', 'dagster/input_event_pointer/stg_payments': '13'}), asset_lineage=[]), message='Materialized value customers.', pid=82561, step_key='jaffle_shop_dbt_assets'))
```

**Comment by alangenfeld** [comment] 2023-11-13 17:41
Ah yep my bad.

It appears we actually try to prevent users from setting `cursor` in this context 
https://github.com/dagster-io/dagster/blame/master/python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py#L178-L184

since it should be managed for you https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py#L153

Can you try to remove `cursor` from the `SensorResult` you return?

**Comment by alangenfeld** [comment] 2023-11-13 18:09
Do you have an older `cursor` value persisted for your sensor from iterating on this? If you have a backlog of materializations events turning on the sensor will resume going through them from where ever the cursor is. You can see the cursor value in the UI on the sensor page, and also edit it there to clear it. 

When I went through the repro I see
![Screenshot 2023-11-13 at 11 59 49 AM](https://github.com/dagster-io/dagster/assets/202219/6ad72269-ac10-47d5-8589-a86448f75e63)

**Comment by michaelwang1994-olo** [comment] 2023-11-13 18:15
@alangenfeld I don't think I have an older `cursor` value. As indicated in your screenshot, the cursor value is `None`. Since I'm running `dagster dev`, it creates a fresh DAGSTER_HOME directory each time.

**Comment by michaelwang1994-olo** [comment] 2023-11-13 18:37
@alangenfeld 

The code in my decorated `@asset_sensor` is executing. I've verified this because the SkipReason that I get isn't `No new asset materializations of AssetKey(['customers'])`, but `Attempted to materialize 9 partitions, but didn't because no new run_keys`. Also the `context.log.info(event)` is being called. 

I expect ticks to occur, but I do not expect the code in the decorated `@asset_sensor` to be executed.

**Comment by alangenfeld** [comment] 2023-11-13 19:19
Alright, I was having some trouble getting the materializing runs from the repro working due to some DuckDB compatibility issues but after having found a workaround I am now able to reproduce and am investigating further.

**Comment by michaelwang1994-olo** [comment] 2023-11-13 19:36
Thanks! Keep me updated!

**Comment by alangenfeld** [comment] 2023-11-13 20:53
Should be resolved by https://github.com/dagster-io/dagster/pull/17970, thanks for bearing with the run around on questions while i got a repro figured out.

**Closed** 2023-11-13 23:14 UTC
Labels: type: bug

**Comment by michaelwang1994-olo** [comment] 2023-11-14 16:08
This is awesome! Look forward to its release!
