### ISSUE TITLE
Partitioned assets are not marked as stale when upstream has new materializations

### ISSUE THREAD

**Issue by mkleinbort-ic** [dagster-io/dagster#18062] opened 2023-11-16 12:21 UTC
### What's the issue or suggestion?

This may be more of a limitation than a documentation issue - but I feel it needs clarifying. 

When you have partitioned assets that depend on upstream assets - these are not marked as stale when those upstream assets are materialized.

Here is some sample code:
```python

@asset
def all_of_the_latest_ocean_data()->pd.DataFrame:
    data = pd.read_sql('SELECT * FROM worldsOceans', ...).set_index('ocean')
    return data 

oceans_partitions_def = StaticPartitionsDefinition(
    ["arctic", "atlantic", "indian", "pacific", "southern"]
)

@asset(partitions_def=oceans_partitions_defs)
def model_of_ocean_temperature(context, all_of_the_latest_ocean_data):

    ocean_name = context.asset_partition_key_for_output()
    ocean_data = all_of_the_latest_ocean_data.loc[ocean_name]

    ml_model = train_ml_model(ocean_data)
    return ml_model 

```

When `all_of_the_latest_ocean_data` is updated, the `model_of_ocean_temperature` materializations are not marked as stale. 

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by sryza** [comment] 2023-11-16 17:17
I believe this is a duplicate of https://github.com/dagster-io/dagster/issues/9374

**Closed by sryza** 2023-11-16 17:17 UTC
Labels: area: docs
